/* Finite fictional teaching paths, shared by React and the portable guide.
 * Sources and independently expected outcomes: docs/coup-lesson-sources.md.
 * No session model, random deals, timers, storage, or real secret assignments. */
const COUP_LESSON = (() => {
  const T = (en, es) => ({en, es});
  const choice = (to, en, es) => ({to, label:T(en,es)});
  const players = (coins=2, ana=[], bruno=[], brunoCoins=2, proof=null) => [
    {name:'Ana', coins, hidden:2-ana.length, lost:ana, proof:proof?.player===0?proof.card:null},
    {name:'Bruno', coins:brunoCoins, hidden:2-bruno.length, lost:bruno, proof:proof?.player===1?proof.card:null},
    {name:'Cami', coins:2, hidden:2, lost:[], proof:null},
  ];
  const node = (phase, title, explanation, table, choices=[], next=null) => ({phase,title,explanation,players:table,choices,next});
  return {
    copy: {
      title:T('Say it. Challenge it. See what changes.','Declara, desafía y mira qué cambia.'),
      intro:T('A claim means saying you have a character. You may tell the truth or bluff: holding that card is not required to announce an action or a block. Influence is your remaining active character cards: each one is like a life. Keep them face down unless a rule calls for a reveal.','Declarar un personaje es decir que lo tienes. Puedes decir la verdad o mentir: no necesitas tener esa carta para anunciar una acción o un bloqueo. Tu influencia son las cartas de personaje que siguen activas: cada una funciona como una vida. Déjalas boca abajo salvo que una regla pida mostrarlas.'),
      distinction:T('A block says “I stop that action with this character.” A challenge says “Prove you have the character you claimed.” Any other active player may challenge an action claim or a block claim, even if they are not the target.','Un bloqueo dice: «Freno esa acción con este personaje». Un desafío dice: «Demuestra que tienes el personaje que declaraste». Cualquier otra persona que siga en juego puede desafiar una acción o un bloqueo, aunque no sea el objetivo.'),
      order:T('Announce → challenge the action claim → block (and possibly challenge the block) → resolve → next player.','Anunciar → desafiar la declaración de la acción → bloquear (y quizá desafiar el bloqueo) → resolver → siguiente jugador.'),
      fiction:T('Fictional practice, base Coup rules. Order: Ana → Bruno → Cami. Everyone begins with 2 influence; the assassination example starts later in a game with Ana at 5 coins. Branches compare different fictional hands. Nothing here changes your scoreboard.','Práctica ficticia con reglas de Coup base. Orden: Ana → Bruno → Cami. Todos comienzan con 2 influencias; el ejemplo de asesinato empieza más adelante en una partida, con Ana en 5 monedas. Las ramas comparan distintas manos ficticias. Nada de esto cambia tu marcador.'),
      examples:T('Choose an example','Elige un ejemplo'), tax:T('1 · Tax claim','1 · Declarar Duque'), assassination:T('2 · Assassination','2 · Asesinato'),
      announce:T('Announcement','Anuncio'), respond:T('Who can respond?','¿Quién puede responder?'), reveal:T('Reveal for the challenge','Mostrar por el desafío'), resolve:T('Resolution','Resolución'),
      table:T('Public table','Mesa pública'), coins:T('coins','monedas'), influence:T('influence remaining','influencias restantes'),
      hidden:T('Face down · identity hidden','Boca abajo · identidad oculta'), proof:T('Shown as proof · still active','Mostrada como prueba · sigue activa'),
      lost:T('Face up · influence lost','Boca arriba · influencia perdida'), out:T('Eliminated · coins returned to the bank','Fuera de juego · monedas devueltas al banco'),
      next:T('Next player','Siguiente jugador'), back:T('Back one step','Volver un paso'), replay:T('Replay this example','Repetir este ejemplo'),
      result:T('End of this turn','Fin de este turno'), reference:T('Characters, actions & blocks','Personajes, acciones y bloqueos'),
      referenceIntro:T('These portraits identify characters; they do not show anyone’s hand. Costs below are paid for the action, not for making a block. A block costs no coins.','Estos retratos identifican personajes; no muestran la mano de nadie. Los costos de abajo corresponden a la acción, no al bloqueo. Bloquear no cuesta monedas.'),
      action:T('Action / cost / result','Acción / costo / resultado'), block:T('Block / who may use it','Bloqueo / quién puede usarlo'),
      general:T('Actions with no character claim','Acciones sin declarar personaje'),
      generalCopy:T('Income: take 1 coin; no block or challenge. Foreign Aid: take 2 coins; no challenge to the action itself, but any opponent may claim Duke to block (and that Duke claim can be challenged). Coup: pay 7 coins; the target loses 1 influence; no block or challenge. At 10+ coins at the start of your turn, you must Coup.','Ingreso: toma 1 moneda; sin bloqueo ni desafío. Ayuda extranjera: toma 2 monedas; no se desafía la acción en sí, pero cualquier rival puede declarar Duque para bloquearla (y se puede desafiar ese Duque). Golpe: paga 7 monedas; el objetivo pierde 1 influencia; sin bloqueo ni desafío. Si empiezas el turno con 10 monedas o más, debes dar un Golpe.'),
      reformation:T('Reformation selected: these examples teach base Coup. In your game, allegiance restricts Coup, Assassinate, Steal, Examine and blocking Foreign Aid against your own side unless everyone has the same allegiance. Conversion and Embezzlement are separate actions; see the complete variant rules.','Reformation seleccionado: estos ejemplos enseñan Coup base. En tu partida, el bando restringe Golpe, Asesinar, Robar, Examinar y bloquear Ayuda extranjera contra tu propio bando, salvo que todos pertenezcan al mismo. Conversión y Malversar son acciones aparte; consulta las reglas completas de la variante.'),
      limit:T('Lose only influence you still have. If your last card is revealed, you leave immediately and return your coins; you cannot block afterward. Proving a claim is different: shuffle that card into the deck and draw a hidden replacement without losing influence.','Solo pierdes influencias que todavía tienes. Si revelas tu última carta, sales de inmediato y devuelves tus monedas; ya no puedes bloquear. Demostrar un personaje es distinto: mezcla esa carta en el mazo y toma otra boca abajo sin perder influencia.'),
      rules:T('Full rules & exceptions','Reglas completas y excepciones'), sources:T('Sources for these examples','Fuentes de estos ejemplos'),
      baseSource:T('Coup rulebook · Actions, Counteractions, Challenges, Double Dangers (pp. 2–7)','Reglamento de Coup · acciones, bloqueos, desafíos y pérdidas dobles (págs. 2–7)'),
      variantSource:T('Reformation rulebook · Inquisitor variant (p. 2)','Reglamento de Reformation · variante Inquisidor (pág. 2)'),
    },
    roles: [
      {id:'coup-duke',action:T('Tax · 0 coins. Take 3 coins if the claim survives any challenge. Tax cannot be blocked.','Impuestos · 0 monedas. Toma 3 monedas si la declaración supera cualquier desafío. No se puede bloquear.'),block:T('Foreign Aid · any opponent may claim Duke to stop it.','Ayuda extranjera · cualquier rival puede declarar Duque para frenarla.')},
      {id:'coup-assassin',action:T('Assassinate · pay 3 coins. The target loses 1 influence if the action succeeds. Only the target may claim Contessa to block.','Asesinar · paga 3 monedas. El objetivo pierde 1 influencia si la acción tiene éxito. Solo el objetivo puede declarar Condesa para bloquear.'),block:T('Assassin blocks no action. The cost stays spent if Contessa blocks, but is refunded if the Assassin claim loses a challenge.','Asesino no bloquea acciones. El costo se mantiene si bloquea la Condesa, pero se devuelve si la declaración de Asesino pierde un desafío.')},
      {id:'coup-captain',action:T('Steal · 0 coins. Take up to 2 coins from a target. Only the target may block with Captain or the selected exchange character.','Robar · 0 monedas. Toma hasta 2 monedas de un objetivo. Solo el objetivo puede bloquear con Capitán o el personaje de intercambio elegido.'),block:T('Steal against you · claim Captain.','Un robo contra ti · declara Capitán.')},
      {id:'coup-contessa',action:T('No character action on your turn. You may still choose other actions or make other character claims.','No tiene una acción propia para tu turno. Puedes elegir otras acciones o declarar otros personajes.'),block:T('Assassination against you · only its target may claim Contessa. The attacker still pays 3 coins.','Un asesinato contra ti · solo su objetivo puede declarar Condesa. Quien ataca igual paga 3 monedas.')},
      {id:'coup-ambassador',exchange:'ambassador',action:T('Exchange · 0 coins. Draw 2 cards, choose from them and your hidden cards, then return 2. Keep the same influence count. Cannot be blocked.','Intercambiar · 0 monedas. Toma 2 cartas, elige entre ellas y tus cartas ocultas, y devuelve 2. Conserva la misma cantidad de influencias. No se puede bloquear.'),block:T('Steal against you · claim Ambassador.','Un robo contra ti · declara Embajador.')},
      {id:'coup-inquisitor',exchange:'inquisitor',action:T('Exchange or Examine · 0 coins; choose one. Exchange: draw 1, choose, return 1; keep your influence count. Examine: the target privately shows one chosen hidden card; you may require them to draw a replacement before returning it. Neither action can be blocked.','Intercambiar o Examinar · 0 monedas; elige una. Intercambiar: toma 1, elige y devuelve 1; conserva tus influencias. Examinar: el objetivo te muestra en privado una carta oculta que elige; puedes exigir que tome un reemplazo antes de devolverla. Ninguna acción se puede bloquear.'),block:T('Steal against you · claim Inquisitor. It replaces Ambassador, independently of Reformation’s side rules.','Un robo contra ti · declara Inquisidor. Reemplaza al Embajador, independientemente de las reglas de bandos de Reformation.')},
    ],
    scenarios: [
      {id:'tax',start:'tax-start',art:'coup-duke'},
      {id:'assassination',start:'assassin-start',art:'coup-assassin'},
    ],
    nodes: {
      'tax-start':node('announce',T('Ana: “Duke. I take Tax.”','Ana: «Duque. Cobro Impuestos».'),T('Ana claims Duke but shows no card. Bruno or Cami may challenge. Nobody can block Tax. The 3 coins arrive only after the claim is resolved.','Ana declara Duque sin mostrar cartas. Bruno o Cami pueden desafiar. Nadie puede bloquear Impuestos. Las 3 monedas llegan una vez resuelta la declaración.'),players(),[
        choice('tax-pass','Nobody challenges','Nadie desafía'),choice('tax-challenge','Bruno challenges the Duke claim','Bruno desafía la declaración de Duque')]),
      'tax-pass':node('resolve',T('The claim goes unchallenged','Nadie desafía la declaración'),T('Ana takes 3 coins: 2 + 3 = 5. Truth or bluff, the action succeeds when nobody challenges. Every card stays hidden; the example does not reveal whether Ana held Duke.','Ana toma 3 monedas: 2 + 3 = 5. Verdad o mentira, la acción tiene éxito si nadie desafía. Todas las cartas siguen ocultas; el ejemplo no revela si Ana tenía Duque.'),players(5),[],1),
      'tax-challenge':node('respond',T('Bruno: “Prove Duke.”','Bruno: «Demuestra Duque».'),T('Compare two fictional hands. Ana must show Duke to win this challenge. If she cannot or chooses not to prove it, she loses. Making the claim was allowed in either case.','Compara dos manos ficticias. Ana debe mostrar Duque para ganar este desafío. Si no puede o elige no demostrarlo, pierde. En ambos casos estaba permitido hacer la declaración.'),players(),[
        choice('tax-proof','Truthful branch: Ana shows Duke','Rama verdadera: Ana muestra Duque'),choice('tax-caught','Bluff branch: Ana cannot prove Duke','Rama de mentira: Ana no puede demostrar Duque')]),
      'tax-proof':node('reveal',T('Duke proves the claim','Duque demuestra la declaración'),T('Ana shows Duke as proof, not as lost influence. Bruno loses the challenge and chooses Captain to leave face up permanently. Ana must now shuffle her shown Duke into the deck and draw a replacement.','Ana muestra Duque como prueba, no como influencia perdida. Bruno pierde el desafío y elige dejar Capitán boca arriba de forma permanente. Ahora Ana debe mezclar el Duque mostrado en el mazo y tomar un reemplazo.'),players(2,[],['coup-captain'],2,{player:0,card:'coup-duke'}),[choice('tax-true','Replace Duke, then collect Tax','Reemplazar Duque y cobrar Impuestos')]),
      'tax-true':node('resolve',T('Replacement hidden; Tax collected','Reemplazo oculto; Impuestos cobrados'),T('Ana shuffled Duke into the deck, drew a hidden replacement and took 3 coins: 2 + 3 = 5. She still has 2 influence. Bruno has 1 influence and keeps his 2 coins. The replacement identity is unknown.','Ana mezcló Duque en el mazo, tomó un reemplazo oculto y cobró 3 monedas: 2 + 3 = 5. Sigue con 2 influencias. Bruno tiene 1 influencia y conserva sus 2 monedas. No se conoce la identidad del reemplazo.'),players(5,[],['coup-captain']),[],1),
      'tax-caught':node('resolve',T('The bluff fails; no Tax','La mentira falla; no hay Impuestos'),T('Ana cannot prove Duke. She chooses Captain to leave face up and loses 1 influence. Cancel Tax: Ana stays at 2 coins. Bruno loses nothing. Ana’s other card remains hidden.','Ana no puede demostrar Duque. Elige dejar Capitán boca arriba y pierde 1 influencia. Se cancela Impuestos: Ana queda en 2 monedas. Bruno no pierde nada. La otra carta de Ana sigue oculta.'),players(2,['coup-captain']),[],1),
      'assassin-start':node('announce',T('Ana: “Assassin. I target Bruno.”','Ana: «Asesino. Mi objetivo es Bruno».'),T('Ana has 5 coins, enough to pay 3. All hands are hidden. The character picture identifies her claim; it is not proof that she holds Assassin.','Ana tiene 5 monedas, suficientes para pagar 3. Todas las manos están ocultas. El retrato identifica su declaración; no demuestra que tenga Asesino.'),players(5),[choice('assassin-response','Announce and pay 3 coins','Anunciar y pagar 3 monedas')]),
      'assassin-response':node('respond',T('3 coins paid; hear responses','3 monedas pagadas; se escuchan respuestas'),T('Ana: 5 − 3 = 2 coins. Bruno or Cami may challenge Assassin first. If that claim stands, only Bruno may claim Contessa to block. A block claim can then be challenged by Ana or Cami.','Ana: 5 − 3 = 2 monedas. Primero Bruno o Cami pueden desafiar Asesino. Si esa declaración se mantiene, solo Bruno puede declarar Condesa para bloquear. Luego Ana o Cami pueden desafiar ese bloqueo.'),players(2),[
        choice('assassin-hit','No challenge and no block','Sin desafío ni bloqueo'),choice('assassin-challenge','Bruno challenges Assassin','Bruno desafía Asesino'),choice('block-claim','No action challenge; Bruno claims Contessa','Nadie desafía la acción; Bruno declara Condesa')]),
      'assassin-hit':node('resolve',T('The assassination succeeds','El asesinato tiene éxito'),T('Bruno chooses Captain to leave face up and loses 1 influence. Ana’s 3 coins remain spent (5 → 2). Neither Ana’s claimed Assassin nor Bruno’s remaining card is revealed.','Bruno elige dejar Capitán boca arriba y pierde 1 influencia. Las 3 monedas de Ana siguen gastadas (5 → 2). No se revela el Asesino declarado por Ana ni la carta restante de Bruno.'),players(2,[],['coup-captain']),[],1),
      'assassin-challenge':node('respond',T('Resolve the Assassin challenge first','Primero se resuelve el desafío al Asesino'),T('Compare a truthful claim and a bluff. Do not resolve a Contessa block or the assassination’s influence loss before this challenge.','Compara una declaración verdadera con una mentira. No resuelvas un bloqueo de Condesa ni la pérdida de influencia del asesinato antes de este desafío.'),players(2),[
        choice('assassin-proof','Truthful branch: Ana shows Assassin','Rama verdadera: Ana muestra Asesino'),choice('assassin-caught','Bluff branch: Ana cannot prove Assassin','Rama de mentira: Ana no puede demostrar Asesino')]),
      'assassin-caught':node('resolve',T('Action canceled; 3 coins refunded','Acción cancelada; se devuelven 3 monedas'),T('Ana cannot prove Assassin. She reveals Captain as lost influence. The action fails, so refund its cost: 5 − 3 + 3 = 5 coins. Bruno loses no influence and does not need a block.','Ana no puede demostrar Asesino. Revela Capitán como influencia perdida. La acción falla y se devuelve su costo: 5 − 3 + 3 = 5 monedas. Bruno no pierde influencia ni necesita bloquear.'),players(5,['coup-captain']),[],1),
      'assassin-proof':node('reveal',T('Assassin proved; Bruno loses the challenge','Asesino demostrado; Bruno pierde el desafío'),T('Ana shows Assassin as proof. Bruno chooses Captain as his lost influence. This is the challenge penalty, not yet the assassination. Replace Ana’s shown Assassin before continuing.','Ana muestra Asesino como prueba. Bruno elige Capitán como influencia perdida. Esta es la penalización del desafío, todavía no la del asesinato. Reemplaza el Asesino mostrado por Ana antes de seguir.'),players(2,[],['coup-captain'],2,{player:0,card:'coup-assassin'}),[choice('assassin-after-proof','Shuffle Assassin back and draw a hidden replacement','Mezclar Asesino en el mazo y tomar un reemplazo oculto')]),
      'assassin-after-proof':node('respond',T('Bruno still has a chance to block','Bruno todavía puede bloquear'),T('Ana has replaced Assassin and keeps 2 influence. Bruno has 1 influence left, so he may still claim Contessa. Any other active player may challenge that block. If no block stops the action, he loses his remaining influence to the assassination.','Ana reemplazó Asesino y conserva 2 influencias. A Bruno le queda 1 influencia, así que todavía puede declarar Condesa. Cualquier otra persona activa puede desafiar ese bloqueo. Si ningún bloqueo frena la acción, pierde su influencia restante por el asesinato.'),players(2,[],['coup-captain']),[
        choice('assassin-double','Bruno does not block','Bruno no bloquea'),choice('late-block','Bruno claims Contessa; nobody challenges','Bruno declara Condesa; nadie desafía')]),
      'assassin-double':node('resolve',T('Two losses in one turn','Dos pérdidas en un turno'),T('First Bruno lost Captain for his failed challenge. Now the unblocked assassination reveals his last card, Duke. Bruno is eliminated and returns his 2 coins to the bank. Ana keeps 2 coins; Cami plays next because Bruno is out.','Primero Bruno perdió Capitán por su desafío fallido. Ahora el asesinato sin bloquear revela su última carta, Duque. Bruno queda eliminado y devuelve sus 2 monedas al banco. Ana queda con 2 monedas; sigue Cami porque Bruno está fuera.'),players(2,[],['coup-captain','coup-duke'],0),[],2),
      'late-block':node('resolve',T('The later block saves Bruno’s last influence','El bloqueo posterior salva la última influencia de Bruno'),T('No one challenges Bruno’s Contessa claim, so the block succeeds without revealing it. Bruno keeps 1 hidden card and 2 coins. Ana’s 3-coin cost stays spent. Losing a challenge did not prevent Bruno from blocking while still active.','Nadie desafía la Condesa declarada por Bruno, así que el bloqueo tiene éxito sin mostrarla. Bruno conserva 1 carta oculta y 2 monedas. El costo de 3 monedas de Ana sigue gastado. Perder un desafío no le impedía bloquear mientras siguiera activo.'),players(2,[],['coup-captain']),[],1),
      'block-claim':node('respond',T('Bruno: “Contessa. I block.”','Bruno: «Condesa. Bloqueo».'),T('This is a new character claim, not a challenge to Ana. Bruno may be truthful or bluffing. Ana or Cami may challenge Contessa. If neither does, the block works with no reveal.','Esta es una nueva declaración de personaje, no un desafío a Ana. Bruno puede decir la verdad o mentir. Ana o Cami pueden desafiar Condesa. Si nadie lo hace, el bloqueo funciona sin mostrar cartas.'),players(2),[
        choice('block-pass','Nobody challenges the block','Nadie desafía el bloqueo'),choice('block-challenge','Ana challenges Contessa','Ana desafía Condesa')]),
      'block-pass':node('resolve',T('Blocked; the fee stays spent','Bloqueado; el costo sigue gastado'),T('Truthful or bluffing, Bruno’s unchallenged block stops the assassination. Everyone keeps 2 hidden influence. Ana has 2 coins, not 5: a successful block does not refund the 3-coin fee.','Verdadero o falso, el bloqueo de Bruno sin desafío frena el asesinato. Todos conservan 2 influencias ocultas. Ana tiene 2 monedas, no 5: un bloqueo exitoso no devuelve el costo de 3 monedas.'),players(2),[],1),
      'block-challenge':node('respond',T('Can Bruno prove Contessa?','¿Puede Bruno demostrar Condesa?'),T('Compare two fictional hands. The loser of this challenge loses 1 influence. A failed block lets the original assassination continue.','Compara dos manos ficticias. Quien pierda este desafío pierde 1 influencia. Si el bloqueo falla, el asesinato original continúa.'),players(2),[
        choice('block-proof','Truthful branch: Bruno shows Contessa','Rama verdadera: Bruno muestra Condesa'),choice('block-caught','Bluff branch: Bruno cannot prove Contessa','Rama de mentira: Bruno no puede demostrar Condesa')]),
      'block-proof':node('reveal',T('Contessa proves the block','Condesa demuestra el bloqueo'),T('Bruno shows Contessa. Ana loses her challenge and chooses Duke to leave face up. Bruno keeps his influence: next he shuffles Contessa into the deck and draws a hidden replacement.','Bruno muestra Condesa. Ana pierde su desafío y elige dejar Duque boca arriba. Bruno conserva su influencia: ahora mezcla Condesa en el mazo y toma un reemplazo oculto.'),players(2,['coup-duke'],[],2,{player:1,card:'coup-contessa'}),[choice('block-true','Replace Contessa and finish the blocked action','Reemplazar Condesa y terminar la acción bloqueada')]),
      'block-true':node('resolve',T('Block upheld; replacement stays hidden','Bloqueo confirmado; el reemplazo queda oculto'),T('Bruno replaced Contessa and keeps 2 influence and 2 coins. Ana has 1 influence and 2 coins: the lost challenge costs influence, and the blocked assassination still costs its 3 coins.','Bruno reemplazó Condesa y conserva 2 influencias y 2 monedas. Ana tiene 1 influencia y 2 monedas: el desafío perdido cuesta influencia y el asesinato bloqueado igual cuesta sus 3 monedas.'),players(2,['coup-duke']),[],1),
      'block-caught':node('reveal',T('False block: first lose the challenge','Bloqueo falso: primero se pierde el desafío'),T('Bruno cannot prove Contessa. He chooses Captain to leave face up for losing the challenge. The block fails. The original assassination still has to resolve; Bruno has 1 influence left.','Bruno no puede demostrar Condesa. Elige dejar Capitán boca arriba por perder el desafío. El bloqueo falla. Todavía falta resolver el asesinato original; a Bruno le queda 1 influencia.'),players(2,[],['coup-captain']),[choice('block-double','Resolve the assassination','Resolver el asesinato')]),
      'block-double':node('resolve',T('Failed block, then assassination','Bloqueo fallido, después asesinato'),T('Bruno lost Captain for the false Contessa claim, then reveals Duke for the assassination. With 0 influence, he returns his 2 coins to the bank and leaves. Ana stays at 2 coins; Cami plays next. There is no refund for successfully challenging a block.','Bruno perdió Capitán por la Condesa falsa y después revela Duque por el asesinato. Con 0 influencias, devuelve sus 2 monedas al banco y sale. Ana queda en 2 monedas; sigue Cami. Ganar un desafío contra un bloqueo no devuelve el costo.'),players(2,[],['coup-captain','coup-duke'],0),[],2),
    },
  };
})();

// Portable renderer. State is deliberately memory-only and separate from Coup sessions.
const coupLessonPractice = {selected:'tax', paths:{}};
function coupLesson() {
  const data=COUP_LESSON, t=key=>e(data.copy[key]);
  const scenario=data.scenarios.find(s=>s.id===coupLessonPractice.selected);
  const path=coupLessonPractice.paths[scenario.id]||[], current=path.at(-1)||scenario.start;
  const step=data.nodes[current], name=id=>e(LESSON_CARD_FACTS[id].name||OFFICIAL[id].title);
  const art=id=>officialButton(id,'lesson-card-art');
  const rule=section=>`<a class="coup-rule" href="#coup/full/${section}">${t('rules')} →</a>`;
  const hand=player=>`<ul class="coup-hand">${Array.from({length:player.hidden-(player.proof?1:0)},()=>`<li class="coup-hidden"><span aria-hidden="true">?</span>${t('hidden')}</li>`).join('')}${player.proof?`<li class="coup-revealed" data-coup-proof="${player.proof}">${art(player.proof)}<strong>${name(player.proof)}</strong><span>${t('proof')}</span></li>`:''}${player.lost.map(id=>`<li class="coup-revealed coup-lost" data-coup-lost="${id}">${art(id)}<strong>${name(id)}</strong><span>${t('lost')}</span></li>`).join('')}</ul>`;
  return `<section id="coup-lesson" class="block coup-lesson" aria-labelledby="coup-lesson-title">
    <h2 id="coup-lesson-title">${t('title')}</h2><p>${t('intro')}</p><p>${t('distinction')}</p>
    <p class="coup-order">${t('order')}</p><p class="image-note">${t('fiction')}</p>
    <div class="coup-example-picker" role="group" aria-label="${t('examples')}">${data.scenarios.map(s=>`<button type="button" data-coup-example="${s.id}" aria-pressed="${scenario.id===s.id}">${t(s.id)}</button>`).join('')}</div>
    <div class="coup-scene" data-coup-node="${current}">
      <div class="coup-claim-art">${art(current.startsWith('block-')||current==='late-block'?'coup-contessa':scenario.art)}<p>${tr('Reference portrait for the claim; this does not show anyone’s hand.','Retrato de referencia para la declaración; no muestra la mano de nadie.')}</p></div>
      <p class="eyebrow">${t(step.phase)}</p><h3 id="coup-step-heading" tabindex="-1">${e(step.title)}</h3>
      <div class="coup-explanation" role="status" aria-atomic="true"><p>${e(step.explanation)}</p></div>
      <h4>${t('table')}</h4><ul class="coup-public-table">${step.players.map((p,i)=>`<li data-coup-example-player="${i}" data-coins="${p.coins}" data-influence="${p.hidden}"><h5>${p.name}</h5><p class="coup-counts"><strong>${p.coins} ${t('coins')}</strong><span>${p.hidden} ${t('influence')}</span></p>${hand(p)}${!p.hidden?`<p class="coup-eliminated">${t('out')}</p>`:''}</li>`).join('')}</ul>
      ${step.next!==null?`<p class="coup-outcome"><strong>${t('result')} · ${t('next')}: ${step.players[step.next].name}.</strong></p>`:''}
      <div class="coup-choices">${step.choices.map(c=>`<button type="button" data-coup-choice="${c.to}">${e(c.label)} →</button>`).join('')}</div>
      <nav class="coup-controls" aria-label="${t('examples')}"><button type="button" data-coup-back ${!path.length?'disabled':''}>${t('back')}</button><button type="button" data-coup-replay>${t('replay')}</button></nav>
    </div><p>${t('limit')}</p>${rule('challenges')}
    <h3>${t('reference')}</h3><p>${t('referenceIntro')}</p>
    <div class="coup-role-grid">${data.roles.filter(r=>!r.exchange||r.exchange===state.exchange).map(r=>`<article class="coup-role" data-coup-role="${r.id}">${art(r.id)}<div><h4>${name(r.id)}</h4><p><strong>${t('action')}: </strong>${e(r.action)}</p><p><strong>${t('block')}: </strong>${e(r.block)}</p><small>${e(LESSON_CARD_FACTS[r.id].note)}</small>${rule(LESSON_CARD_FACTS[r.id].rule)}</div></article>`).join('')}</div>
    <h3>${t('general')}</h3><p>${t('generalCopy')}</p>
    ${state.reformation?`<aside class="coup-variant"><p>${t('reformation')}</p><a class="coup-rule" href="#coup/full/reformation">Reformation →</a></aside>`:''}
    <details class="coup-sources"><summary>${t('sources')}</summary><p><a href="https://officialgamerules.org/wp-content/uploads/2025/02/Coup-Rulebook.pdf">${t('baseSource')}</a></p><p><a href="https://www.spelhuis.be/Files/7/112000/112353/Attachments/Product/aD1jf4U81u46a97ia1719S97Nm9925v8.pdf">${t('variantSource')}</a></p></details>
  </section>`;
}
function bindCoupLesson() {
  const root=document.getElementById('coup-lesson');if(!root)return;
  function refresh() {
    const live=root.querySelector('.coup-explanation'), template=document.createElement('template');
    const sourcesOpen=root.querySelector('.coup-sources').open;
    template.innerHTML=coupLesson();
    const nextLive=template.content.querySelector('.coup-explanation'), message=nextLive.innerHTML;
    nextLive.replaceWith(live);root.replaceWith(template.content);
    bindCoupLesson();live.innerHTML=message;
    document.querySelector('#coup-lesson .coup-sources').open=sourcesOpen;
    document.getElementById('coup-step-heading').focus();
  }
  const id=coupLessonPractice.selected, path=coupLessonPractice.paths[id]||[];
  root.querySelectorAll('[data-coup-example]').forEach(b=>b.onclick=()=>{coupLessonPractice.selected=b.dataset.coupExample;refresh();});
  root.querySelectorAll('[data-coup-choice]').forEach(b=>b.onclick=()=>{coupLessonPractice.paths[id]=[...path,b.dataset.coupChoice];refresh();});
  root.querySelector('[data-coup-back]').onclick=()=>{coupLessonPractice.paths[id]=path.slice(0,-1);refresh();};
  root.querySelector('[data-coup-replay]').onclick=()=>{coupLessonPractice.paths[id]=[];refresh();};
}
