/* Original, bilingual explanations. Rule references live with each game. */
const L = (en, es) => ({ en, es });
const section = (id, title, paragraphs) => ({ id, title, paragraphs });
const GAMES = {
  coup: {
    name: L('Coup', 'Coup'), subtitle: L('A little influence. A very good bluff.', 'Un poco de influencia. Un gran farol.'),
    category: L('Bluffing & deduction', 'Faroles y deducción'), players: '2–6', time: '15', icon: 'crown', color: 'peach',
    description: L('Claim power, call a bluff, and be the last one standing.', 'Reclama poder, descubre mentiras y sé la última persona en pie.'),
    goal: L('Be the last player with at least one face-down influence card. You can claim any role—even one you do not have.', 'Gana si eres la última persona con al menos una carta de influencia boca abajo. Puedes afirmar que tienes cualquier personaje, aunque sea mentira.'),
    basics: [
      L('Shuffle 3 copies of each of the 5 roles. Deal 2 secret cards and 2 coins to each player; leave the rest as the court deck and bank. With 2 players, the first player starts with only 1 coin.', 'Baraja 3 copias de cada uno de los 5 personajes. Reparte 2 cartas secretas y 2 monedas por persona; el resto forma la corte y la banca. Con 2 jugadores, quien empieza recibe solo 1 moneda.'),
      L('Take one action on your turn, then pass clockwise. Claim a role when the action requires it. Give everyone time to challenge, then allow a legal block.', 'Haz una acción por turno y sigue en sentido horario. Declara el personaje si la acción lo requiere. Da tiempo para desafiar y luego para un bloqueo válido.'),
      L('A challenge means “prove that role.” The loser reveals one of their own cards permanently. A truthful claimant shuffles the proved card into the deck and draws a replacement.', 'Un desafío significa «demuestra que tienes ese personaje». Quien pierde revela una carta propia de forma permanente. Si demuestras tu personaje, lo mezclas en el mazo y robas otro.'),
      L('Pay 7 coins to make someone lose an influence with a coup. At 10 or more coins at the start of your turn, you must coup. Lose both influences and you are out.', 'Paga 7 monedas para quitar una influencia con un golpe. Si empiezas tu turno con 10 monedas o más, el golpe es obligatorio. Al perder ambas influencias quedas fuera.')
    ],
    reminder: L('A block and a challenge are different. A block claims a defensive role; a challenge questions whether a claimed role is real.', 'Bloquear y desafiar son cosas distintas. Un bloqueo declara un personaje defensivo; un desafío pone en duda un personaje declarado.'),
    sections: [
      section('setup', L('Setup & influence', 'Preparación e influencia'), [
        L('Use Duke, Assassin, Captain, Contessa and either Ambassador or Inquisitor. For the standard 2–6 player game use 3 of each chosen role, 15 cards total. Give each player 2 cards face down and 2 coins. The previous winner starts; agree on a first player for your first game. In a 2-player game the first player receives only 1 coin.', 'Usa Duque, Asesino, Capitán, Condesa y Embajador o Inquisidor. Para 2–6 jugadores usa 3 copias de cada personaje elegido: 15 cartas. Reparte 2 cartas boca abajo y 2 monedas a cada persona. Empieza quien ganó la partida anterior; en la primera, acuerden quién empieza. Con 2 jugadores, quien empieza recibe solo 1 moneda.'),
        L('Keep your money visible and your living influence secret. Whenever you lose influence, choose one of your hidden cards and turn it face up permanently. It has no further power and cannot be exchanged. With no hidden cards left, you leave the game and return your coins to the bank. The last remaining player wins.', 'Mantén tus monedas a la vista y tus influencias activas en secreto. Al perder influencia, elige una carta oculta y déjala boca arriba para siempre. Ya no tiene poder ni se puede intercambiar. Si no te quedan cartas ocultas, quedas fuera y devuelves tus monedas a la banca. Gana la última persona que conserve influencia.')
      ]),
      section('turn', L('Turn order, actions & blocks', 'Turnos, acciones y bloqueos'), [
        L('On your turn choose exactly one affordable action; you cannot pass. Announce the action, target and any required role. Resolve a challenge to that role first, then a legal block and any challenge to the block. Finally apply the surviving action and pass clockwise. Once play has moved on, no late challenges.', 'En tu turno elige exactamente una acción que puedas pagar; no puedes pasar. Anuncia la acción, el objetivo y el personaje necesario. Resuelve primero el desafío al personaje, luego un bloqueo válido y su posible desafío. Aplica la acción si sigue en pie y pasa el turno en sentido horario. No se permiten desafíos retroactivos.'),
        L('Income: take 1 coin; no block or challenge. Foreign Aid: take 2; anyone may claim Duke to block. Coup: pay 7; your target loses 1 influence; no block or challenge. Starting with 10+ coins forces a coup.', 'Ingreso: toma 1 moneda; no admite bloqueo ni desafío. Ayuda extranjera: toma 2; cualquiera puede declarar Duque para bloquear. Golpe: paga 7 y el objetivo pierde 1 influencia; no admite bloqueo ni desafío. Empezar con 10 monedas o más obliga a dar un golpe.'),
        L('Tax claims Duke and takes 3 coins. Assassinate claims Assassin, costs 3 and removes 1 influence; only the target may block with Contessa. Steal claims Captain and takes up to 2 coins from a target; only the target may block with Captain or the selected exchange role. Exchange claims Ambassador or Inquisitor. These role claims can be challenged; Tax and Exchange cannot be blocked.', 'Impuestos declara Duque y toma 3 monedas. Asesinar declara Asesino, cuesta 3 y quita 1 influencia; solo el objetivo puede bloquear con Condesa. Robar declara Capitán y toma hasta 2 monedas de otro jugador; solo el objetivo puede bloquear con Capitán o el personaje de intercambio elegido. Intercambiar declara Embajador o Inquisidor. Estas declaraciones admiten desafío; Impuestos e Intercambiar no admiten bloqueo.'),
        L('For Ambassador exchange, draw 2 cards, choose which cards to keep among them and your living influence, then return 2 to the court. Keep the same number of living influences. You may keep your original cards. See the Inquisitor section for its different exchange.', 'Para intercambiar con el Embajador, roba 2 cartas y elige cuáles conservar entre ellas y tus influencias activas; devuelve 2 a la corte. Conserva el mismo número de influencias activas. Puedes quedarte con tus cartas originales. El intercambio del Inquisidor se explica en su sección.')
      ]),
      section('challenges', L('Challenges, costs & double losses', 'Desafíos, costes y pérdidas dobles'), [
        L('Any other active player may challenge a role claimed for an action or a block—even if they are not the target. You may bluff either claim. The challenged player either proves the exact claimed role using a hidden card or concedes. The challenge loser chooses an influence to reveal.', 'Cualquier otro jugador activo puede desafiar un personaje declarado en una acción o bloqueo, aunque no sea el objetivo. Puedes mentir en ambos casos. La persona desafiada demuestra el personaje exacto con una carta oculta o se rinde. Quien pierde el desafío elige una influencia para revelar.'),
        L('If the claim is proved, the challenger loses influence. Shuffle the proved card into the court and draw a replacement; proving it does not cost influence. The action or block then continues. If an action claim is disproved, cancel that action and refund its cost. If a block is disproved, the original action continues.', 'Si se demuestra la declaración, quien desafió pierde influencia. Mezcla la carta demostrada en la corte y roba otra; demostrarla no cuesta influencia. La acción o bloqueo continúa. Si se desmiente el personaje de una acción, cancélala y devuelve su coste. Si se desmiente un bloqueo, continúa la acción original.'),
        L('Assassination costs 3 even when Contessa successfully blocks it. But if the Assassin claim itself is successfully challenged, refund the 3 coins. A target can lose 2 influences in one turn: one for losing a challenge, then another for an unblocked assassination. Losing a challenge to Assassin does not prevent a surviving target from subsequently claiming Contessa.', 'Asesinar cuesta 3 incluso si la Condesa lo bloquea con éxito. Pero si el desafío al Asesino demuestra que mentía, devuelve esas 3 monedas. El objetivo puede perder 2 influencias en un turno: una por perder un desafío y otra por el asesinato sin bloquear. Si sobrevive al desafío perdido contra el Asesino, todavía puede declarar Condesa.'),
        L('Example: Alex claims Duke for Tax. Sol challenges. Alex shows Duke: Sol reveals one influence, Alex shuffles Duke into the court, draws a replacement and takes 3 coins. If Alex cannot or will not prove Duke, Alex loses an influence and takes no coins.', 'Ejemplo: Alex declara Duque para cobrar Impuestos. Sol desafía. Alex muestra Duque: Sol revela una influencia, Alex mezcla el Duque en la corte, roba otra carta y toma 3 monedas. Si Alex no puede o no quiere demostrar Duque, pierde una influencia y no recibe monedas.')
      ]),
      section('inquisitor', L('Inquisitor variant', 'Variante con Inquisidor'), [
        L('Replace every Ambassador with an Inquisitor; do not include both roles. This replacement works with ordinary Coup, without needing allegiance rules. The Inquisitor can claim one of two actions on a turn, and can also block a steal aimed at them.', 'Sustituye todos los Embajadores por Inquisidores; no incluyas ambos personajes. Esta sustitución funciona en Coup normal, sin reglas de lealtad. El Inquisidor permite declarar una de dos acciones por turno y también bloquear un robo dirigido contra ti.'),
        L('Exchange: draw only 1 card from the court. Choose among it and your living influence, then return 1 card. Your influence count stays the same. Examine: choose an opponent; they choose one hidden card to show only to you. You decide whether they keep it or must replace it. For a replacement, they first draw a random new card and then return the inspected card to the court.', 'Intercambiar: roba solo 1 carta de la corte. Elige entre ella y tus influencias activas y devuelve 1 carta. Tu cantidad de influencias no cambia. Examinar: elige un rival; esa persona elige una carta oculta y te la muestra solo a ti. Decides si la conserva o debe cambiarla. Si la cambia, primero roba una carta aleatoria y después devuelve la carta examinada a la corte.'),
        L('Exchange, Examine and the Inquisitor steal-block all claim Inquisitor and may be challenged. Examine cannot be blocked. Example: you inspect a Contessa and force its replacement. Your opponent draws before returning it, so they cannot immediately draw that same physical card.', 'Intercambiar, Examinar y bloquear un robo declaran Inquisidor y admiten desafío. Examinar no admite bloqueo. Ejemplo: ves una Condesa y obligas a cambiarla. El rival roba antes de devolverla, así que no puede robar esa misma carta física de inmediato.')
      ]),
      section('table', L('Table rules & player variants', 'Reglas de mesa y variantes de jugadores'), [
        L('Negotiation is allowed but promises are not binding. Do not voluntarily reveal your hidden cards, give coins away, or lend coins. Gold-colored money tokens serve as currency; color alone does not add an expansion rule. Use the values printed on your edition’s tokens.', 'Se permite negociar, pero las promesas no son obligatorias. No reveles voluntariamente tus cartas ocultas, regales monedas ni las prestes. Las fichas doradas sirven como dinero; el color por sí solo no añade reglas de expansión. Usa los valores indicados en las fichas de tu edición.'),
        L('Optional 2-player draft: divide the 15 cards into 3 sets containing one of each role. Each player takes a set, secretly keeps 1 card and removes the other 4 from play. Shuffle the third set, deal 1 more card to each player and leave its remaining 3 as the court. The starting player still begins with 1 coin.', 'Selección opcional para 2 jugadores: divide las 15 cartas en 3 grupos con un personaje de cada tipo. Cada persona toma un grupo, elige 1 carta en secreto y retira las otras 4 de la partida. Baraja el tercer grupo, reparte 1 carta adicional a cada persona y deja las 3 restantes como corte. Quien empieza sigue recibiendo 1 moneda.'),
        L('With extra expansion cards, 7–8 players need 4 copies of each chosen role (20 cards); 9–10 need 5 (25 cards). Keep five role types. Larger games mean longer waits after elimination.', 'Con cartas adicionales de la expansión, 7–8 jugadores necesitan 4 copias de cada personaje elegido (20 cartas); 9–10 necesitan 5 (25 cartas). Mantén cinco tipos de personaje. Las partidas grandes implican más espera después de la eliminación.')
      ])
    ],
    sources: [ ['Coup · rulebook', 'https://officialgamerules.org/wp-content/uploads/2025/02/Coup-Rulebook.pdf'], ['Coup: Reformation · Inquisitor', 'https://www.ultraboardgames.com/coup/reformation.php'] ]
  },
  avalon: {
    name: L('Avalon', 'Avalon'), subtitle: L('Trust is a dangerous game.', 'Confiar es un juego peligroso.'), category: L('Hidden roles & discussion', 'Roles ocultos y debate'), players: '5–10', time: '30', icon: 'sword', color: 'lavender',
    description: L('Build a quest team. Find the traitors. Protect Merlin.', 'Forma un equipo. Descubre a los traidores. Protege a Merlín.'),
    goal: L('Good needs 3 successful quests and a hidden Merlin. Evil wins with 3 failed quests, 5 consecutive rejected teams, or a correct final assassination of Merlin.', 'El Bien necesita 3 misiones exitosas y que Merlín siga oculto. El Mal gana con 3 misiones fallidas, 5 equipos rechazados consecutivamente o un asesinato final que identifique a Merlín.'),
    basics: [
      L('Choose the player count below. Deal one secret role to each player using the shown Good/Evil totals. Include Merlin and Assassin; optional characters replace ordinary members of their own side.', 'Elige la cantidad de jugadores. Reparte un personaje secreto por persona respetando los totales de Bien y Mal indicados. Incluye a Merlín y al Asesino; los personajes opcionales sustituyen integrantes normales de su propio bando.'),
      L('Read the opening script so Evil recognizes its allies and Merlin gets information. Then the leader proposes a team of the required size. Everyone discusses and votes publicly at the same time.', 'Lee el guion inicial para que el Mal reconozca a sus aliados y Merlín obtenga información. El líder propone un equipo del tamaño indicado. Todos debaten y revelan sus votos a la vez.'),
      L('A strict majority approves the team; a tie rejects it. On rejection, pass leadership clockwise and try again. Five rejected proposals in a row give Evil an immediate win.', 'La mayoría absoluta aprueba el equipo; un empate lo rechaza. Tras un rechazo, el liderazgo pasa en sentido horario y se intenta de nuevo. Cinco propuestas rechazadas seguidas dan la victoria inmediata al Mal.'),
      L('Only the approved team secretly plays quest cards. Good must play Success; Evil may choose Success or Fail. Shuffle before revealing. Usually 1 Fail defeats a quest; quest 4 needs 2 Fails with 7+ players.', 'Solo el equipo aprobado juega cartas de misión en secreto. El Bien debe jugar Éxito; el Mal puede elegir Éxito o Fracaso. Baraja antes de revelar. Normalmente 1 Fracaso hace fallar la misión; la misión 4 necesita 2 con 7 jugadores o más.'),
      L('Record the result, reset the rejection count and pass leadership clockwise. After 3 successes, keep identities hidden: Evil discusses and Assassin names Merlin. A correct guess gives Evil the win; a wrong guess gives Good the win.', 'Anota el resultado, reinicia los rechazos y pasa el liderazgo en sentido horario. Tras 3 éxitos, mantén los personajes ocultos: el Mal debate y el Asesino señala a Merlín. Si acierta gana el Mal; si falla gana el Bien.')
    ],
    reminder: L('Voting on a team is public and everyone participates. Quest cards are secret and only team members play them.', 'La votación del equipo es pública y participan todos. Las cartas de misión son secretas y solo las juegan los integrantes del equipo.'),
    sections: [
      section('setup', L('Setup & choosing roles', 'Preparación y selección de personajes'), [
        L('Use the board for your player count. Give everyone Approve and Reject tokens, deal one shuffled secret character each, choose the first leader randomly, and set the quest and rejection markers to their starting positions. Keep the quest cards and result markers nearby. Never show your character or use its printed artwork to prove your identity during play.', 'Usa el tablero correspondiente a la cantidad de jugadores. Entrega fichas de Aprobar y Rechazar a cada persona, reparte un personaje secreto al azar, elige al primer líder al azar y coloca los marcadores de misión y rechazos al inicio. Deja cerca las cartas de misión y los marcadores de resultado. No muestres tu personaje ni uses su ilustración para demostrar tu identidad durante la partida.'),
        L('Basic setup: Merlin plus ordinary Loyal Servants on Good; Assassin plus ordinary Minions on Evil. Optional setup: replace ordinary cards with Percival, Morgana, Mordred or Oberon, preserving the Good/Evil totals. Keep Merlin and Assassin for the rules in this guide. The setup helper limits optional roles to the available places.', 'Preparación básica: Merlín y Leales a Arturo en el Bien; Asesino y Esbirros en el Mal. Preparación opcional: sustituye cartas normales por Percival, Morgana, Mordred u Oberón, sin alterar los totales de cada bando. Conserva a Merlín y al Asesino para las reglas de esta guía. El asistente limita los personajes opcionales a los lugares disponibles.'),
        L('Before the first proposal, read the opening script with pauses. All Evil except Oberon see one another. Merlin sees Evil except Mordred, including Oberon. If included, Percival sees Merlin and Morgana together without learning which is which. All of this information stays secret.', 'Antes de la primera propuesta, lee el guion inicial con pausas. Todo el Mal excepto Oberón se reconoce. Merlín ve al Mal excepto Mordred, incluido Oberón. Si participa, Percival ve a Merlín y a Morgana juntos, sin distinguir quién es quién. Toda esa información es secreta.')
      ]),
      section('teams', L('Propose a team & vote', 'Proponer un equipo y votar'), [
        L('The leader proposes exactly the required number of distinct players for the current quest, optionally including themselves. Everyone can discuss, claim a role, accuse or bluff. After discussion, all players—including the leader and players outside the team—choose Approve or Reject secretly and reveal together.', 'El líder propone exactamente la cantidad de personas distintas que exige la misión; puede incluirse. Todos pueden debatir, declarar personajes, acusar o mentir. Después, todos los jugadores —incluidos el líder y quienes no van a la misión— eligen Aprobar o Rechazar en secreto y revelan a la vez.'),
        L('More than half the players must approve. A tie is a rejection. When rejected, keep the same quest, advance the rejection counter and pass leadership clockwise for a new proposal. Five consecutive rejections end the game in an Evil victory; the fifth team is still voted on. An approved team breaks the rejection streak.', 'Debe aprobar más de la mitad de los jugadores. Un empate es rechazo. Al rechazar, conserva la misma misión, avanza el contador de rechazos y pasa el liderazgo en sentido horario para otra propuesta. Cinco rechazos consecutivos dan la victoria al Mal; el quinto equipo también se vota. Aprobar un equipo rompe la racha de rechazos.')
      ]),
      section('quests', L('Resolve a quest & move on', 'Resolver una misión y avanzar'), [
        L('Give each team member a Success and a Fail card. They secretly submit one. Good must submit Success; Evil may submit either. Mix the submitted cards thoroughly and reveal only the combined result. Separately collect and shuffle unused cards so nobody can trace an individual choice.', 'Da a cada integrante una carta de Éxito y otra de Fracaso. Cada persona entrega una en secreto. El Bien debe entregar Éxito; el Mal puede entregar cualquiera. Mezcla bien las cartas entregadas y revela solo el resultado conjunto. Recoge y baraja aparte las cartas sin usar para que no se pueda rastrear una elección individual.'),
        L('Zero Fails means success. One or more means failure, except quest 4 with 7–10 players, which needs at least 2 Fails. That exception does not apply to quest 5. Mark the result and move to the next quest whether the previous one succeeded or failed; pass leadership clockwise.', 'Cero Fracasos significa éxito. Uno o más significa fracaso, salvo la misión 4 con 7–10 jugadores, que requiere al menos 2 Fracasos. La excepción no se aplica a la misión 5. Marca el resultado y avanza a la siguiente misión tanto si hubo éxito como fracaso; pasa el liderazgo en sentido horario.'),
        L('Example: with 7 players, quest 4 sends 4 people. Three Success cards and one Fail still succeed. Two Success cards and two Fails fail. A successful quest does not prove that everyone on its team is Good.', 'Ejemplo: con 7 jugadores, la misión 4 lleva a 4 personas. Tres Éxitos y un Fracaso dan éxito. Dos Éxitos y dos Fracasos hacen fallar la misión. Una misión exitosa no demuestra que todos sus integrantes sean del Bien.')
      ]),
      section('ending', L('Winning & the assassination', 'Victoria y asesinato'), [
        L('Stop immediately when 3 quests have failed: Evil wins. Also stop if 5 teams are rejected consecutively on the same quest. If 3 quests succeed instead, do not reveal roles yet. Evil discusses and the Assassin chooses one Good player as Merlin. If correct, Evil wins; otherwise Good wins. There is only one assassination guess.', 'Termina en cuanto fallen 3 misiones: gana el Mal. También termina si se rechazan 5 equipos consecutivos para la misma misión. Si se logran 3 éxitos, todavía no revelen los personajes. El Mal debate y el Asesino elige a un jugador del Bien como Merlín. Si acierta gana el Mal; si falla gana el Bien. Solo hay un intento de asesinato.')
      ]),
      section('optional', L('Optional characters', 'Personajes opcionales'), [
        L('Percival is Good and learns who Merlin is; if Morgana is present, Percival sees two possibilities. Morgana is Evil and appears alongside Merlin to Percival. Mordred is Evil and stays hidden from Merlin, but recognizes the other Evil players normally. Oberon is Evil but neither sees nor is seen by the other Evil players during their opening recognition; Merlin still sees him.', 'Percival pertenece al Bien y reconoce a Merlín; si está Morgana, ve dos posibilidades. Morgana pertenece al Mal y aparece junto a Merlín ante Percival. Mordred pertenece al Mal y permanece oculto para Merlín, pero reconoce normalmente al resto del Mal. Oberón pertenece al Mal, pero no ve ni es visto por sus aliados durante el reconocimiento inicial; Merlín sí lo ve.'),
        L('Add optional roles gradually. Percival usually helps Good, Mordred and Morgana help Evil, and Oberon makes Evil’s coordination harder. They change information, not quest-card permissions. Only the Assassin makes the final assassination choice.', 'Añade personajes opcionales poco a poco. Percival suele ayudar al Bien; Mordred y Morgana ayudan al Mal; Oberón dificulta la coordinación del Mal. Cambian la información, no los permisos para jugar cartas de misión. Solo el Asesino realiza la elección final.')
      ]),
      section('lady', L('Lady of the Lake', 'Dama del Lago'), [
        L('Optional, recommended for 7+ players. Give the Lady token to the player on the first leader’s right. After quests 2, 3 and 4 resolve, if play continues, its holder chooses another eligible player and privately checks their loyalty using the Good/Evil loyalty cards. This reveals a side, never a character.', 'Opcional, recomendada con 7 jugadores o más. Da la ficha de la Dama a quien esté a la derecha del primer líder. Tras resolver las misiones 2, 3 y 4, si la partida continúa, su portador elige otra persona válida y consulta en privado su lealtad con las cartas de Bien y Mal. Revela un bando, nunca el personaje.'),
        L('The inspected player must supply their true loyalty; giving the wrong card loses the game. The holder may tell the table anything about the result but cannot show the card. Pass the Lady token to the inspected player. Anyone who has already used the Lady cannot be inspected later. Its holder is public; this power does not replace a role.', 'La persona inspeccionada debe entregar su lealtad real; entregar la carta incorrecta hace perder la partida. El portador puede contar lo que quiera sobre el resultado, pero no mostrar la carta. Pasa la ficha a la persona inspeccionada. Quien ya haya usado la Dama no puede ser inspeccionado después. Su portador es público; este poder no sustituye un personaje.')
      ]),
      section('targeting', L('Optional quest order', 'Orden opcional de misiones'), [
        L('Targeting variant: the leader proposes both an unattempted quest and its team. Use that quest’s team size and mark its result in its own space. Each quest can be attempted only once. Quest 5 is unavailable until two quests have succeeded. With 7+ players, quest 4 still needs 2 Fails, wherever it appears in the order. Start with the normal fixed order while learning.', 'Variante de selección: el líder propone una misión aún no intentada y su equipo. Usa el tamaño de esa misión y marca el resultado en su casilla. Cada misión se intenta una sola vez. La misión 5 no está disponible hasta lograr dos éxitos. Con 7 jugadores o más, la misión 4 sigue requiriendo 2 Fracasos, sin importar cuándo se intente. Para aprender, usa el orden fijo normal.')
      ])
    ],
    sources: [['The Resistance: Avalon · rulebook', 'https://avalon.fun/pdfs/rules.pdf'], ['Avalon · publisher', 'https://indieboardsandcards.com/our-games/the-resistance-avalon/']]
  },
  poker: {
    name: L('Poker', 'Póker'), subtitle: L('Know your hand. Play your moment.', 'Conoce tu mano. Elige tu momento.'), category: L('No-Limit Texas Hold’em', 'Texas Hold’em sin límite'), players: '2–10', time: '30–90+', icon: 'spade', color: 'mint',
    description: L('Two private cards, five shared cards, endless possibilities.', 'Dos cartas propias, cinco compartidas y muchas posibilidades.'),
    goal: L('Win chips by making everyone else fold, or by showing the strongest five-card hand. Use any five of your two private cards and the five community cards—even none of your private cards.', 'Gana fichas haciendo que todos se retiren o mostrando la mejor mano de cinco cartas. Usa cinco entre tus dos cartas propias y las cinco comunitarias; puedes no usar ninguna propia.'),
    basics: [
      L('Use a 52-card deck without jokers. Agree on chip values, starting stacks, blinds and when the session ends. The dealer button rotates clockwise; the next two players post small and big blinds. Deal 2 private cards each.', 'Usa una baraja de 52 cartas sin comodines. Acuerden valores de fichas, montones iniciales, ciegas y cuándo termina la sesión. El botón del repartidor gira en sentido horario; las dos personas siguientes ponen ciega pequeña y grande. Reparte 2 cartas privadas a cada una.'),
      L('Before the flop, action starts left of the big blind. Fold, call the current bet, or raise. If no additional chips are needed, you can check. The big blind still gets a turn if everyone merely calls.', 'Antes del flop empieza quien está a la izquierda de la ciega grande. Puedes retirarte, igualar o subir. Si no necesitas añadir fichas, puedes pasar. La ciega grande conserva su turno aunque todos solo igualen.'),
      L('Deal 3 community cards (flop), then 1 (turn), then 1 (river), with a betting round after each. Burn a card before each deal. After the flop, the first active player left of the button acts first.', 'Reparte 3 cartas comunitarias (flop), luego 1 (turn) y luego 1 (river), con una ronda de apuestas después de cada etapa. Quema una carta antes de cada reparto. Desde el flop empieza la primera persona activa a la izquierda del botón.'),
      L('If only one player remains, they take the pot without showing. Otherwise compare five-card hands after the final betting round. Equal best hands split the pot. Move the button and start the next hand.', 'Si queda una sola persona, gana el pozo sin mostrar. Si quedan varias, comparen sus mejores manos de cinco cartas tras la última apuesta. Las manos iguales dividen el pozo. Mueve el botón y empieza otra mano.')
    ],
    reminder: L('A hand always has five cards. A sixth card never breaks a tie, and suits have equal strength.', 'Una mano siempre tiene cinco cartas. Una sexta carta nunca desempata y todos los palos valen lo mismo.'),
    sections: [
      section('setup', L('Table setup & dealing', 'Preparación y reparto'), [
        L('This guide uses No-Limit Texas Hold’em. Pick chip denominations, starting stacks and blinds before playing. Choose a fixed-blind casual session or a tournament with an agreed blind schedule and buy-in/rebuy rules. These are table choices. For example, use 1/2 blinds and 200 chips each. No money is needed.', 'Esta guía usa Texas Hold’em sin límite. Elijan valores de fichas, montones iniciales y ciegas antes de jugar. Pueden usar una sesión con ciegas fijas o un torneo con un calendario de ciegas y reglas de entrada o recompra acordados. Son decisiones de la mesa. Por ejemplo, ciegas 1/2 y 200 fichas por persona. No hace falta dinero.'),
        L('Shuffle a standard 52-card deck, without jokers. Mark a dealer with the button. The next active seat clockwise posts the small blind and the next posts the big blind. Deal one card at a time clockwise, starting left of the button, until each player has 2 hidden cards. Keep all cards and chips on the table.', 'Baraja 52 cartas sin comodines. Marca al repartidor con el botón. El siguiente asiento activo en sentido horario pone la ciega pequeña y el siguiente la grande. Reparte una carta por vez en sentido horario desde la izquierda del botón, hasta que cada persona tenga 2 cartas ocultas. Mantén cartas y fichas sobre la mesa.'),
        L('With exactly 2 players, the button posts the small blind and acts first before the flop; the big blind acts first after the flop. The big blind receives the first dealt card. Move the button clockwise between hands.', 'Con exactamente 2 jugadores, el botón pone la ciega pequeña y actúa primero antes del flop; la ciega grande actúa primero después. La ciega grande recibe la primera carta del reparto. Mueve el botón en sentido horario entre manos.')
      ]),
      section('betting', L('Betting actions & minimum raises', 'Acciones y subidas mínimas'), [
        L('Fold: surrender your hand and any chips already committed. Check: stay in without adding chips, allowed only when you owe nothing. Bet: put in the first wager of a round. Call: match the current wager, or go all-in for less if necessary. Raise: increase that wager. All-in: commit your entire remaining stack; you cannot wager chips you do not have on the table.', 'Retirarse (fold): abandonas la mano y las fichas ya apostadas. Pasar (check): sigues sin añadir fichas, solo si no debes nada. Apostar (bet): haces la primera apuesta de la ronda. Igualar (call): completas la apuesta actual, o vas all-in por menos si no te alcanza. Subir (raise): aumentas esa apuesta. All-in: apuestas todo tu montón restante; no puedes apostar fichas que no estén en la mesa.'),
        L('The minimum opening bet is the big blind. A full raise must increase the current wager by at least the previous full bet or raise increment. With blinds 1/2, raising to 6 adds 4, so the next full raise must be to at least 10. You may always move all-in for less than a full bet or raise, but a short all-in does not by itself reopen raising for players who already acted.', 'La apuesta inicial mínima es la ciega grande. Una subida completa debe aumentar la apuesta al menos por el incremento de la última apuesta o subida completa. Con ciegas 1/2, subir a 6 aumenta 4, así que la siguiente subida completa debe llegar al menos a 10. Puedes ir all-in por menos, pero un all-in corto no reabre por sí solo la posibilidad de subir a quienes ya actuaron.'),
        L('Several short all-ins can cumulatively reopen raising if a player now faces at least a full raise since their last action. Betting ends when all non-folded, non-all-in players have acted and matched the current wager. Going all-in does not force the rest of the table to stop betting against one another.', 'Varios all-ins cortos pueden reabrir las subidas si, en conjunto, una persona enfrenta al menos una subida completa desde su última acción. La ronda termina cuando quienes siguen y no están all-in han actuado e igualado la apuesta actual. Un all-in no impide que los demás sigan apostando entre sí.')
      ]),
      section('streets', L('The four betting rounds', 'Las cuatro rondas de apuestas'), [
        L('Pre-flop: two private cards each; begin left of the big blind. Flop: burn one face-down card, deal three community cards face up, then bet. Turn: burn one, deal a fourth community card, then bet. River: burn one, deal the fifth community card, then bet. From the flop onward, action starts with the first remaining player clockwise from the button.', 'Preflop: dos cartas privadas por persona; empieza quien está a la izquierda de la ciega grande. Flop: quema una carta boca abajo, muestra tres comunitarias y apuesta. Turn: quema una, muestra la cuarta y apuesta. River: quema una, muestra la quinta y apuesta. Desde el flop, empieza la primera persona que siga en la mano en sentido horario desde el botón.'),
        L('A burn card stays out of play and is not shown. If everyone but one player folds, award the pot immediately; do not deal more cards. If all remaining players are all-in, finish the community cards without further betting and compare eligible hands.', 'Una carta quemada queda fuera del juego y no se muestra. Si todos menos una persona se retiran, entrega el pozo inmediatamente y no repartas más cartas. Si quienes quedan están all-in, completa las comunitarias sin más apuestas y compara las manos que correspondan.')
      ]),
      section('showdown', L('Showdown, ties & side pots', 'Mostrar cartas, empates y pozos secundarios'), [
        L('At showdown the last player to bet or raise on the river shows first; if nobody did, start with the first remaining player left of the button. Show both private cards to claim a contested pot. Build the best 5-card hand from all 7 available cards. You may use zero, one or two private cards.', 'Al mostrar, empieza quien hizo la última apuesta o subida en el river; si nadie apostó, empieza la primera persona activa a la izquierda del botón. Muestra ambas cartas privadas para reclamar un pozo disputado. Forma la mejor mano de 5 con las 7 cartas disponibles. Puedes usar cero, una o dos privadas.'),
        L('Compare the hand category, then its relevant ranks and kickers. For two pairs, compare the higher pair, then the lower pair, then the kicker. For full houses compare the three-of-a-kind before the pair. For straights compare the highest card; A–2–3–4–5 is five-high. Ace may be high or low, but a straight cannot wrap around. Equal five-card hands tie regardless of suit. Split the pot; assign an indivisible odd chip to the first tied player clockwise from the button.', 'Compara la categoría y luego sus valores y cartas de desempate (kickers). Con doble pareja, compara la pareja mayor, luego la menor y después el kicker. En full compara primero el trío. En escaleras compara la carta más alta; A–2–3–4–5 tiene altura cinco. El as puede ser alto o bajo, pero no une ambos extremos. Cinco cartas equivalentes empatan sin importar el palo. Divide el pozo; una ficha indivisible va al primer jugador empatado en sentido horario desde el botón.'),
        L('All-in players can win only the amounts they matched from each opponent. Example: A contributes 20, B 50, C 50. The main pot is 60, contested by A, B and C. The side pot is 60, contested only by B and C. Resolve each pot separately; a folded hand cannot win, but its chips stay in the pots. Return any unmatched excess bet to its owner.', 'Quien va all-in solo puede ganar la cantidad que igualó de cada rival. Ejemplo: A aporta 20, B 50 y C 50. El pozo principal es 60 y lo disputan A, B y C. El secundario es 60 y solo lo disputan B y C. Resuelve cada pozo por separado; una mano retirada no puede ganar, pero sus fichas permanecen en los pozos. Devuelve al dueño cualquier exceso de apuesta que nadie haya igualado.'),
        L('Winning a hand is different from winning a session. A tournament ends when one player has all the chips. In a casual fixed-blind session, stop at the agreed time and count chips.', 'Ganar una mano no es lo mismo que ganar la sesión. Un torneo termina cuando alguien reúne todas las fichas. En una sesión informal con ciegas fijas, terminen a la hora acordada y cuenten las fichas.')
      ])
    ],
    sources: [['Texas Hold’em · PokerStars', 'https://www.pokerstars.com/poker/games/texas-holdem/'], ['Poker rules · PokerStars', 'https://www.pokerstars.com/poker/games/rules/']]
  },
  moth: {
    name: L('Cheating Moth', 'La Polilla Tramposa'), subtitle: L('A very good time to be sneaky.', 'El momento perfecto para hacer trampa.'), category: L('Cards & sleight of hand', 'Cartas y picardía'), players: '3–5', time: '15–25', icon: 'moth', color: 'yellow',
    description: L('Make your cards disappear. Just don’t let the guard see.', 'Haz desaparecer tus cartas sin que el guardián te vea.'),
    goal: L('Empty your hand by playing cards and secretly making cards disappear. Play as many rounds as there are players; the lowest total penalty score wins.', 'Vacía tu mano jugando cartas y haciéndolas desaparecer en secreto. Jueguen tantas rondas como participantes; gana quien acumule menos puntos de penalización.'),
    basics: [
      L('The oldest player takes the Guard Bug. Shuffle the other cards and deal 8 each. Make a face-down draw pile and reveal one starting discard; ignore its action effect. The guard starts.', 'La persona de mayor edad recibe la Chinche Guardiana. Baraja el resto y reparte 8 cartas a cada una. Forma un mazo boca abajo y revela un descarte inicial; ignora su efecto especial. Empieza el guardián.'),
      L('Play a card exactly 1 higher or lower than the top discard. The numbers wrap: on 1, play 2 or 5; on 5, play 4 or 1. If you cannot play, draw 1 and end your turn.', 'Juega una carta exactamente 1 mayor o menor que el descarte. Los números se conectan: sobre 1 puedes jugar 2 o 5; sobre 5, un 4 o 1. Si no puedes jugar, roba 1 y termina tu turno.'),
      L('Anyone except the guard may secretly get rid of cards, one at a time—even outside their turn. Keep your hand above the table, never hide your last card, and pause cheating during an accusation.', 'Cualquiera excepto el guardián puede hacer desaparecer cartas en secreto, de una en una, incluso fuera de su turno. Mantén la mano de cartas sobre la mesa, nunca escondas la última y pausa las trampas durante una acusación.'),
      L('Only the guard may catch a cheat. A caught player takes back the card, receives one from the guard and becomes the new guard. A false accusation makes the guard draw 1 and keep the job.', 'Solo el guardián puede descubrir una trampa. Quien es descubierto recupera la carta, recibe una del guardián y se convierte en el nuevo guardián. Si la acusación es falsa, el guardián roba 1 y conserva su función.')
    ],
    reminder: L('Moths cannot be played or given away—except the guard may play them by the normal number rule. Never save a moth as your last card!', 'Las polillas no se pueden jugar ni regalar, salvo que el guardián las juegue respetando la regla numérica. ¡No dejes una polilla como última carta!'),
    sections: [
      section('setup', L('Setup & normal turns', 'Preparación y turnos normales'), [
        L('Set aside the Guard Bug and give it face up to the oldest player. Shuffle the remaining cards, deal 8 each, and use the rest as a draw pile. Reveal its top card to start the discard pile. Only its number matters; do not trigger a starting action card. The guard begins and turns go clockwise.', 'Separa la Chinche Guardiana y entrégala boca arriba a la persona de mayor edad. Baraja el resto, reparte 8 por persona y forma un mazo con las restantes. Revela la primera carta para iniciar los descartes. Solo importa su número; no actives su efecto especial. Empieza el guardián y sigan en sentido horario.'),
        L('On your turn discard one legal card: one number above or below the top discard, wrapping between 1 and 5. Action cards follow this same rule and then trigger their effect. If you have no legal card, draw one and stop; you do not immediately play the drawn card. When the draw pile runs out, recycle and shuffle the discards to refill it.', 'En tu turno descarta una carta válida: un número mayor o menor que el descarte, conectando 1 con 5. Las cartas especiales siguen la misma regla y luego aplican su efecto. Si no tienes una carta válida, roba una y termina; no la juegas inmediatamente. Cuando se agote el mazo, recicla y baraja los descartes para reponerlo.')
      ]),
      section('cheating', L('Cheating, moths & the guard', 'Trampas, polillas y guardián'), [
        L('The guard plays normal turns but cannot cheat. Other players may secretly remove number cards, action cards or moths one at a time. Keep the hand holding your cards above the table. Never make your final card disappear. Nobody may cheat while an accusation is being resolved.', 'El guardián juega sus turnos normales, pero no puede hacer trampa. Los demás pueden quitarse cartas numéricas, especiales o polillas en secreto, de una en una. Mantén sobre la mesa la mano que sostiene tus cartas. Nunca hagas desaparecer tu última carta. Nadie puede hacer trampa mientras se resuelve una acusación.'),
        L('A moth cannot normally be discarded or handed to another player. You must sneak it away. The guard is the exception: they can play a moth on their turn if its number fits. This does not allow the guard to give moths away.', 'Una polilla normalmente no se puede descartar ni entregar a otra persona. Debes hacerla desaparecer. El guardián es la excepción: puede jugarla en su turno si su número encaja. Eso no le permite regalar polillas.'),
        L('Only the guard may accuse, and must catch the act; other players cannot report cheats. If correct, the caught player retrieves the disappearing card, takes one non-moth card from the guard’s hand and receives the Guard Bug. If wrong, the guard draws a penalty card and stays guard.', 'Solo el guardián puede acusar y debe descubrir la trampa en el momento; los demás no pueden delatar. Si acierta, la persona descubierta recupera la carta, recibe una carta que no sea polilla de la mano del guardián y recibe la Chinche Guardiana. Si se equivoca, el guardián roba una carta de penalización y conserva su función.')
      ]),
      section('insects', L('Every insect effect', 'Efecto de cada insecto'), [
        L('Spider: after playing it, you may give one card from your hand to any opponent, but never a moth. Mosquito: everyone except the person who played it races to slap the card. The last player receives one non-moth card from each other player, including the person who played the mosquito.', 'Araña: después de jugarla, puedes regalar una carta de tu mano a cualquier rival, pero nunca una polilla. Mosquito: todos excepto quien lo jugó intentan tocarlo primero. La última persona recibe una carta que no sea polilla de cada otro jugador, incluido quien jugó el mosquito.'),
        L('Cockroach: everyone, including the person who played it, may race to put a plain number card of that same value on top. Only the fastest leaves their card there; the others take theirs back. If nobody can do it, continue normally. Ant: everyone except the person who played it draws 1 card.', 'Cucaracha: todos, incluido quien la jugó, pueden intentar poner encima una carta numérica normal del mismo valor. Solo la persona más rápida la deja; las demás recuperan las suyas. Si nadie puede, continúen normalmente. Hormiga: todos excepto quien la jugó roban 1 carta.')
      ]),
      section('scoring', L('End of a round & scoring', 'Fin de ronda y puntuación'), [
        L('The round ends as soon as a player has no cards. Count penalty points for cards left in each hand: number cards 1 each, action cards 5 each, moths 10 each. The player who emptied their hand gets 0. Example: 2 number cards + 1 spider + 1 moth = 17 penalty points.', 'La ronda termina en cuanto alguien se queda sin cartas. Cuenta penalizaciones por lo que quede en cada mano: 1 por carta numérica, 5 por especial y 10 por polilla. Quien vació su mano recibe 0. Ejemplo: 2 cartas numéricas + 1 araña + 1 polilla = 17 puntos.'),
        L('Collect all cards, including hidden ones, and deal a fresh round. The player left of the previous round’s starting player becomes the new starting guard, regardless of who held the Guard Bug at the end. Play one round per player, then compare cumulative penalties. Lowest total wins.', 'Recoge todas las cartas, incluidas las escondidas, y reparte otra ronda. Quien está a la izquierda de la persona que inició la ronda anterior será el nuevo guardián inicial, sin importar quién tenía la Chinche al final. Jueguen una ronda por participante y comparen las penalizaciones acumuladas. Gana el total más bajo.')
      ])
    ],
    sources: [['Cheating Moth · Drei Magier / Schmidt Spiele', 'https://www.schmidtspiele.de/files/Produkte/4/40862%20-%20Mogel%20Motte/40862_Mogelmotte_DE_GB_FR_IT.pdf']]
  }
};
const AVALON_SETUPS = {5:{good:3,evil:2,quests:[2,3,2,3,3]},6:{good:4,evil:2,quests:[2,3,4,3,4]},7:{good:4,evil:3,quests:[2,3,3,4,4]},8:{good:5,evil:3,quests:[3,4,4,5,5]},9:{good:6,evil:3,quests:[3,4,4,5,5]},10:{good:6,evil:4,quests:[3,4,4,5,5]}};
const AVALON_ROLES = [
 {id:'merlin', side:'good', name:L('Merlin','Merlín'),text:L('Sees Evil, except Mordred. Must avoid the final assassination.','Ve al Mal, excepto a Mordred. Debe evitar el asesinato final.')},
 {id:'assassin', side:'evil', name:L('Assassin','Asesino'),text:L('Makes the final guess at Merlin after 3 successful quests.','Intenta identificar a Merlín tras 3 misiones exitosas.')},
 {id:'percival', side:'good', name:L('Percival','Percival'),text:L('Sees Merlin and Morgana, but cannot tell them apart. Without Morgana, sees Merlin alone.','Ve a Merlín y a Morgana sin distinguirlos. Sin Morgana, solo ve a Merlín.')},
 {id:'morgana', side:'evil', name:L('Morgana','Morgana'),text:L('Appears to Percival alongside Merlin.','Aparece junto a Merlín ante Percival.')},
 {id:'mordred', side:'evil', name:L('Mordred','Mordred'),text:L('Hidden from Merlin. Recognizes Evil normally.','Oculto para Merlín. Reconoce al Mal normalmente.')},
 {id:'oberon', side:'evil', name:L('Oberon','Oberón'),text:L('Does not recognize Evil and is not recognized by Evil. Merlin sees him.','No reconoce al Mal ni es reconocido por el Mal. Merlín sí lo ve.')}
];
const POKER_HANDS = [
 [L('Royal flush','Escalera real'),'A♥ K♥ Q♥ J♥ 10♥',L('Ace-high straight flush. The strongest hand.','Escalera de color hasta el as. La mano más fuerte.')],
 [L('Straight flush','Escalera de color'),'9♠ 8♠ 7♠ 6♠ 5♠',L('Five consecutive ranks, all the same suit.','Cinco valores consecutivos del mismo palo.')],
 [L('Four of a kind','Póker'),'Q♠ Q♥ Q♦ Q♣ 2♥',L('Four cards of the same rank, plus a kicker.','Cuatro cartas del mismo valor y un kicker.')],
 [L('Full house','Full'),'J♠ J♥ J♦ 4♣ 4♥',L('Three of a kind and a pair. Compare the trio first.','Un trío y una pareja. Compara primero el trío.')],
 [L('Flush','Color'),'A♦ J♦ 8♦ 6♦ 2♦',L('Five of the same suit. Compare ranks from highest down.','Cinco del mismo palo. Compara de mayor a menor.')],
 [L('Straight','Escalera'),'8♠ 7♥ 6♦ 5♣ 4♥',L('Five consecutive ranks. A–2–3–4–5 is the lowest straight.','Cinco valores consecutivos. A–2–3–4–5 es la escalera menor.')],
 [L('Three of a kind','Trío'),'7♠ 7♥ 7♦ K♣ 2♥',L('Three of one rank, plus two kickers.','Tres del mismo valor y dos kickers.')],
 [L('Two pair','Doble pareja'),'K♠ K♥ 5♦ 5♣ 9♥',L('Two different pairs and one kicker.','Dos parejas diferentes y un kicker.')],
 [L('One pair','Pareja'),'10♠ 10♥ A♦ 8♣ 3♥',L('One pair, plus three kickers.','Una pareja y tres kickers.')],
 [L('High card','Carta alta'),'A♠ J♥ 8♦ 6♣ 3♥',L('None of the above. Compare all five ranks from highest down.','Ninguna de las anteriores. Compara los cinco valores de mayor a menor.')]
];
GAMES.coup.sections.splice(4, 0, section('reformation', L('Reformation: allegiances & the reserve', 'Reformation: lealtades y reserva'), [
  L('Reformation adds factions, but each player still wins alone by eliminating everyone else. Put the Treasury Reserve card in the center, initially empty and separate from the normal bank. Give everyone an Allegiance card. The first player chooses Loyalist or Reformist; going clockwise, alternate the initial allegiances. All ordinary Coup rules still apply unless changed below.', 'Reformation añade facciones, pero cada persona sigue ganando por su cuenta al eliminar a todas las demás. Coloca la Reserva del Tesoro en el centro, inicialmente vacía y separada de la banca normal. Entrega una carta de Lealtad a cada persona. Quien empieza elige Leal o Reformista; en sentido horario, alterna las lealtades iniciales. Se aplican las reglas normales de Coup salvo los cambios siguientes.'),
  L('While both allegiances remain among active players, you cannot coup, assassinate, steal from, examine, or block Foreign Aid from someone on your own side. You may still challenge them. When all surviving players share one allegiance, these restrictions disappear until two sides exist again. Allegiances do not reveal character cards.', 'Mientras haya jugadores activos de ambas lealtades, no puedes dar un golpe, asesinar, robar, examinar ni bloquear Ayuda extranjera a alguien de tu mismo bando. Sí puedes desafiarlo. Si todos los supervivientes comparten lealtad, desaparecen esas restricciones hasta que vuelvan a existir dos bandos. Las lealtades no revelan personajes.'),
  L('Conversion is your whole turn: pay 1 coin to flip your own Allegiance card, or pay 2 to flip another active player’s. Put these coins on the Treasury Reserve, not in the normal bank. Conversion needs no character, cannot be blocked and cannot be challenged. You cannot convert instead of making a mandatory coup at 10+ coins.', 'Convertir ocupa todo tu turno: paga 1 moneda para voltear tu propia Lealtad o 2 para voltear la de otro jugador activo. Esas monedas van a la Reserva del Tesoro, no a la banca normal. Convertir no requiere personaje ni admite bloqueo o desafío. Si tienes 10 monedas o más, no puedes convertir en lugar del golpe obligatorio.'),
  L('Embezzlement is your whole turn: claim you have no hidden Duke and take all coins from the Treasury Reserve. It cannot be blocked, but any other active player may challenge the “no Duke” claim. A face-up, lost Duke is not living influence and does not prevent embezzlement.', 'Malversar ocupa todo tu turno: declara que no tienes ningún Duque oculto y toma todas las monedas de la Reserva del Tesoro. No admite bloqueo, pero cualquier otro jugador activo puede desafiar la declaración «no tengo Duque». Un Duque boca arriba, ya perdido, no es influencia activa y no impide malversar.'),
  L('If challenged and you have a hidden Duke, you must concede; you may also concede without one. Return any coins taken to the reserve and lose 1 influence. To prove you have no Duke, reveal all your living influence cards. The challenger loses 1 influence; shuffle all your revealed living cards into the court, draw the same number of replacements, and keep the reserve coins. This temporary reveal does not cost you influence.', 'Si te desafían y tienes un Duque oculto, debes rendirte; también puedes rendirte sin tenerlo. Devuelve a la reserva las monedas tomadas y pierde 1 influencia. Para demostrar que no tienes Duque, muestra todas tus influencias activas. Quien desafió pierde 1 influencia; mezcla todas tus cartas activas mostradas en la corte, roba la misma cantidad y conserva las monedas. Esta revelación temporal no te quita influencia.'),
  L('Example: Alex and Sol are Loyalists, while Dani is Reformist. Alex cannot steal from Sol, but can spend 2 coins to convert Sol; that ends Alex’s turn. Sol can now be targeted by Loyalists. If Dani is later eliminated and everyone remaining is Loyalist, normal targeting becomes available again. Inquisitor is an independent option: replace Ambassador if you want it, and apply the same-faction restriction to Examine.', 'Ejemplo: Alex y Sol son Leales; Dani es Reformista. Alex no puede robar a Sol, pero puede gastar 2 monedas para convertirlo; ahí termina su turno. Ahora los Leales pueden atacar a Sol. Si más adelante Dani queda eliminado y todos los supervivientes son Leales, se puede volver a atacar normalmente. El Inquisidor es una opción independiente: sustituye al Embajador si lo deseas y aplica a Examinar la restricción de facción.')
]));
