/* Original, bilingual explanations. Rule references live with each game. */
const L = (en, es) => ({ en, es });
const section = (id, title, paragraphs) => ({ id, title, paragraphs });
const GAMES = {
  coup: {
    name: L('Coup', 'Coup'), subtitle: L('Hide your roles. Decide who to trust.', 'Oculta tus personajes. Decide en quién confiar.'),
    category: L('Deception & deduction', 'Engaño y deducción'), players: '2–6', time: '15', icon: 'crown', color: 'peach',
    description: L('Use character powers, spot lies and eliminate your opponents.', 'Usa los poderes de los personajes, descubre mentiras y elimina a tus rivales.'),
    goal: L('Be the last player with a face-down character card. Each face-down card is one influence: think of it as one life. You may say you have any character, even if you do not. This is called bluffing.', 'Gana quien sea la última persona con una carta de personaje boca abajo. Cada carta boca abajo es una influencia: funciona como una vida. Puedes decir que tienes cualquier personaje, aunque no sea verdad.'),
    basics: [
      L('Use 3 cards of each of the 5 characters. Shuffle and give each player 2 face-down cards and 2 coins. The remaining cards form the draw deck; the remaining coins form the bank. With 2 players, the first player starts with 1 coin.', 'Usa 3 cartas de cada uno de los 5 personajes. Mezcla y reparte 2 cartas boca abajo y 2 monedas por persona. Las cartas restantes forman el mazo y las monedas restantes forman el banco. Con 2 jugadores, quien empieza recibe 1 moneda.'),
      L('Choose one action on your turn. Say which character you are using, if the action needs one. Allow time for a challenge, then for a block. Resolve them before applying the action. Play then moves to the left.', 'Elige una acción en tu turno. Si requiere un personaje, di cuál usas. Da tiempo para que los demás puedan desafiarte y luego bloquear la acción. Resuelve eso antes de aplicar la acción. Después juega la persona de tu izquierda.'),
      L('To challenge is to ask someone to prove they have the character they named. The loser turns one of their own hidden cards face up and loses that influence. If you prove your character, shuffle that card into the deck and take a new one. You keep the same number of hidden cards.', 'Desafiar es pedirle a alguien que demuestre que tiene el personaje que dijo. Quien pierde deja una carta propia boca arriba y pierde esa influencia. Si demuestras tu personaje, mezcla esa carta en el mazo y toma otra. Conservas la misma cantidad de cartas boca abajo.'),
      L('Coup: pay 7 coins and choose a player to lose 1 influence. If you start your turn with 10 or more coins, you must take this action. Losing both influences removes you from the game.', 'Golpe: paga 7 monedas y elige a un jugador para que pierda 1 influencia. Si empiezas el turno con 10 monedas o más, debes elegir esta acción. Si pierdes tus dos influencias, quedas fuera de la partida.')
    ],
    reminder: L('A block stops an action by naming a character that can stop it. A challenge asks someone to prove they have the character they named. You may lie about your character in either an action or a block.', 'Un bloqueo frena una acción: dices que tienes un personaje que puede impedirla. Un desafío exige demostrar que tienes el personaje que dijiste. Puedes mentir sobre tu personaje tanto al actuar como al bloquear.'),
    sections: [
      section('setup', L('Setup & influence', 'Preparación e influencia'), [
        L('Use Duke, Assassin, Captain, Contessa and either Ambassador or Inquisitor. For the standard 2–6 player game use 3 of each chosen role, 15 cards total. Give each player 2 cards face down and 2 coins. The previous winner starts; agree on a first player for your first game. In a 2-player game the first player receives only 1 coin.', 'Usa Duque, Asesino, Capitán, Condesa y Embajador o Inquisidor. Para 2–6 jugadores usa 3 copias de cada personaje elegido: 15 cartas. Reparte 2 cartas boca abajo y 2 monedas a cada persona. Empieza quien ganó la partida anterior; en la primera, acuerden quién empieza. Con 2 jugadores, quien empieza recibe solo 1 moneda.'),
        L('Keep your coins visible and your active character cards face down. When you lose 1 influence, choose one face-down card and leave it face up. That card loses its power and cannot be exchanged. When both your cards are face up, you are out: return your coins to the bank. The last player with a face-down card wins.', 'Deja tus monedas a la vista y tus personajes activos boca abajo. Al perder 1 influencia, elige una carta boca abajo y déjala boca arriba. Esa carta pierde su poder y ya no se puede intercambiar. Cuando ambas cartas estén boca arriba, quedas fuera: devuelve tus monedas al banco. Gana quien conserve una carta boca abajo al final.')
      ]),
      section('turn', L('Turn order, actions & blocks', 'Turnos, acciones y bloqueos'), [
        L('Choose exactly one action you can pay for; you cannot skip your turn. Announce the action, the player it affects and any character it needs. First resolve any challenge to your character. Next resolve any block, including a challenge to the blocking character. Apply the action if it has not been stopped. Play moves to the left. You cannot challenge after play has moved on.', 'Elige una sola acción que puedas pagar; no puedes saltarte el turno. Anuncia la acción, a quién afecta y qué personaje usas, si hace falta. Primero resuelve cualquier desafío a tu personaje. Después resuelve el bloqueo, incluido un posible desafío al personaje que bloquea. Aplica la acción si nadie logró impedirla. Sigue la persona de tu izquierda. No se puede desafiar una vez que el juego ya avanzó.'),
        L('Income: take 1 coin; no block or challenge. Foreign Aid: take 2; anyone may say they have Duke to block. Coup: pay 7; your target loses 1 influence; no block or challenge. Starting with 10+ coins forces a coup.', 'Ingreso: toma 1 moneda; no admite bloqueo ni desafío. Ayuda extranjera: toma 2; cualquiera puede decir que tiene Duque para bloquear. Golpe: paga 7 y el objetivo pierde 1 influencia; no admite bloqueo ni desafío. Empezar con 10 monedas o más obliga a dar un golpe.'),
        L('Tax: say you have Duke and take 3 coins. Assassinate: say you have Assassin, pay 3 coins and make another player lose 1 influence; only that player may block by saying they have Contessa. Steal: say you have Captain and take up to 2 coins from another player; only that player may block with Captain or the chosen exchange character. Exchange uses Ambassador or Inquisitor. Anyone else may challenge these character claims. Tax and Exchange cannot be blocked.', 'Impuestos: di que tienes Duque y toma 3 monedas. Asesinar: di que tienes Asesino, paga 3 monedas y haz que otro jugador pierda 1 influencia; solo esa persona puede bloquear diciendo que tiene Condesa. Robar: di que tienes Capitán y toma hasta 2 monedas de otro jugador; solo esa persona puede bloquear con Capitán o el personaje de intercambio elegido. Intercambiar usa Embajador o Inquisidor. Los demás pueden desafiar cualquiera de estas declaraciones. Impuestos e Intercambiar no se pueden bloquear.'),
        L('Ambassador exchange: take 2 cards from the deck and look at them with your face-down cards. Choose which to keep, then return 2 to the deck. Keep the same number of face-down cards as before. You may keep your original cards. Inquisitor has a different exchange, explained below.', 'Intercambio del Embajador: toma 2 cartas del mazo y míralas junto con tus cartas boca abajo. Elige cuáles conservar y devuelve 2 al mazo. Debes quedarte con la misma cantidad de cartas boca abajo que tenías antes. Puedes conservar tus cartas originales. El Inquisidor intercambia de otra manera, como se explica más adelante.')
      ]),
      section('challenges', L('Challenges, costs & double losses', 'Desafíos, costos y pérdidas dobles'), [
        L('Any other player still in the game may challenge a character named for an action or a block, even if it does not affect them. You may lie about having that character. If challenged, either show the exact character using a face-down card or accept that you lose the challenge. The loser chooses one face-down card to turn face up permanently.', 'Cualquier otra persona que siga en la partida puede desafiar el personaje usado en una acción o un bloqueo, aunque no la afecte. Puedes mentir sobre ese personaje. Si te desafían, muestra una carta boca abajo con el personaje exacto o acepta perder el desafío. Quien pierde elige una carta boca abajo y la deja boca arriba de forma permanente.'),
        L('If you show the character you named, the challenger loses 1 influence. Shuffle your shown card into the deck and take a replacement; you do not lose influence. Your action or block continues. If you lose a challenge to your action, cancel the action and take back its coin cost. If you lose a challenge to your block, the original action continues.', 'Si muestras el personaje que dijiste, quien te desafió pierde 1 influencia. Mezcla la carta mostrada en el mazo y toma otra; tú no pierdes influencia. Tu acción o bloqueo continúa. Si pierdes un desafío a tu acción, se cancela y recuperas las monedas que pagaste. Si pierdes un desafío a tu bloqueo, la acción original continúa.'),
        L('You still pay 3 coins if Contessa blocks your assassination. You get the 3 coins back only if you lose the challenge to your Assassin claim. The player you attack can lose 2 influences in one turn: one for losing a challenge, then one for the assassination if it is not blocked. A player who loses a challenge to Assassin but still has a hidden card may then claim Contessa to block.', 'Igual pagas las 3 monedas si la Condesa bloquea tu asesinato. Solo recuperas esas monedas si pierdes el desafío a tu declaración de Asesino. La persona atacada puede perder 2 influencias en un turno: una por perder un desafío y otra por el asesinato si no lo bloquea. Si pierde el desafío al Asesino pero todavía tiene una carta boca abajo, puede decir que tiene Condesa para bloquear.'),
        L('Example: Alex claims Duke for Tax. Sol challenges. Alex shows Duke: Sol reveals one influence, Alex shuffles Duke into the deck, draws a replacement and takes 3 coins. If Alex cannot or will not prove Duke, Alex loses an influence and takes no coins.', 'Ejemplo: Alex declara Duque para cobrar Impuestos. Sol desafía. Alex muestra Duque: Sol revela una influencia, Alex mezcla el Duque en el mazo, toma otra carta y toma 3 monedas. Si Alex no puede o no quiere demostrar Duque, pierde una influencia y no recibe monedas.')
      ]),
      section('inquisitor', L('Inquisitor variant', 'Variante con Inquisidor'), [
        L('Replace all Ambassador cards with Inquisitor cards; use only one of these characters. You can use Inquisitor without Reformation. On your turn, say you have Inquisitor to use either Exchange or Examine. You can also use it to block someone stealing from you.', 'Reemplaza todas las cartas de Embajador por Inquisidor; usa solo uno de esos personajes. Puedes usar Inquisidor sin Reformation. En tu turno, di que tienes Inquisidor para usar Intercambiar o Examinar. También sirve para bloquear un robo contra ti.'),
        L('Exchange: take 1 card from the deck. Look at it with your face-down cards, choose which to keep and return 1 card. Keep the same number of hidden cards. Examine: choose an opponent. They choose one of their hidden cards and show it only to you. Decide if they keep it or replace it. To replace it, they take a random card from the deck first, then return the card you examined.', 'Intercambiar: toma 1 carta del mazo. Mírala junto con tus cartas boca abajo, elige cuáles conservar y devuelve 1. Conserva la misma cantidad de cartas ocultas. Examinar: elige a un rival. Esa persona elige una de sus cartas ocultas y te la muestra solo a ti. Decide si la conserva o la cambia. Para cambiarla, primero toma una carta al azar del mazo y después devuelve la que examinaste.'),
        L('To Exchange, Examine or block a Steal with Inquisitor, say you have that character. Other players may challenge you. Examine cannot be blocked. Example: you see a Contessa and decide it must be replaced. The other player takes a new card before returning Contessa, so they cannot take that same card again.', 'Para Intercambiar, Examinar o bloquear un robo con Inquisidor, di que tienes ese personaje. Los demás pueden desafiarte. Examinar no se puede bloquear. Ejemplo: ves una Condesa y decides que debe cambiarse. El rival toma una carta nueva antes de devolver la Condesa, así que no puede tomar de nuevo esa misma carta.')
      ]),
      section('table', L('Table rules & player variants', 'Reglas de mesa y variantes de jugadores'), [
        L('You may negotiate, but you do not have to keep promises. Do not voluntarily reveal your hidden cards, give coins away, or lend coins. Gold-colored money tokens serve as currency; color alone does not add an expansion rule. Use the values printed on your edition’s tokens.', 'Se puede negociar, pero nadie está obligado a cumplir sus promesas. No reveles voluntariamente tus cartas ocultas, regales monedas ni las prestes. Las fichas doradas sirven como dinero; el color por sí solo no añade reglas de expansión. Usa los valores indicados en las fichas de tu edición.'),
        L('Optional card selection for 2 players: divide the 15 cards into 3 sets containing one of each role. Each player takes a set, secretly keeps 1 card and removes the other 4 from play. Shuffle the third set, deal 1 more card to each player and leave its remaining 3 as the deck. The starting player still begins with 1 coin.', 'Selección opcional para 2 jugadores: divide las 15 cartas en 3 grupos con un personaje de cada tipo. Cada persona toma un grupo, elige 1 carta en secreto y retira las otras 4 de la partida. Mezcla el tercer grupo, reparte 1 carta adicional a cada persona y deja las 3 restantes como mazo. Quien empieza sigue recibiendo 1 moneda.'),
        L('With extra expansion cards, 7–8 players need 4 copies of each chosen role (20 cards); 9–10 need 5 (25 cards). Keep five role types. Larger games mean longer waits after elimination.', 'Con cartas adicionales de la expansión, 7–8 jugadores necesitan 4 copias de cada personaje elegido (20 cartas); 9–10 necesitan 5 (25 cartas). Mantén cinco tipos de personaje. Las partidas grandes implican más espera después de la eliminación.')
      ])
    ],
    sources: [ [L('Coup · rules', 'Coup · reglamento'), 'https://officialgamerules.org/wp-content/uploads/2025/02/Coup-Rulebook.pdf'], [L('Coup: Reformation · Inquisitor', 'Coup: Reformation · Inquisidor'), 'https://www.ultraboardgames.com/coup/reformation.php'] ]
  },
  avalon: {
    name: L('Avalon', 'Avalon'), subtitle: L('Trust is a dangerous game.', 'Confiar es un juego peligroso.'), category: L('Hidden roles & discussion', 'Roles ocultos y debate'), players: '5–10', time: '30', icon: 'sword', color: 'lavender',
    description: L('Build a quest team. Find the traitors. Protect Merlin.', 'Forma un equipo. Descubre a los traidores. Protege a Merlín.'),
    goal: L('There are two sides: Good and Evil. Good wins after 3 successful quests, but only if the Assassin does not identify Merlin. Evil wins after 3 failed quests, 5 rejected teams in a row, or a correct final guess at Merlin.', 'Hay dos bandos: el Bien y el Mal. El Bien gana al completar 3 misiones con éxito, siempre que el Asesino no identifique a Merlín al final. El Mal gana si fallan 3 misiones, si se rechazan 5 equipos seguidos o si el Asesino identifica a Merlín.'),
    basics: [
      L('Choose the player count below. Deal one secret role to each player using the shown Good/Evil totals. Include Merlin and Assassin; optional characters replace ordinary members of their own side.', 'Elige la cantidad de jugadores. Reparte un personaje secreto por persona respetando los totales de Bien y Mal indicados. Incluye a Merlín y al Asesino; los personajes opcionales sustituyen integrantes normales de su propio bando.'),
      L('Read the opening script so Evil recognizes its allies and Merlin gets information. Then the leader proposes a team of the required size. Everyone discusses and votes publicly at the same time.', 'Lee el guion inicial para que el Mal reconozca a sus aliados y Merlín obtenga información. El líder propone un equipo del tamaño indicado. Todos debaten y revelan sus votos a la vez.'),
      L('A majority (more than half) approves the team; a tie rejects it. On rejection, pass leadership clockwise and try again. Five rejected proposals in a row give Evil an immediate win.', 'Para aprobar el equipo, debe votar a favor más de la mitad de los jugadores. Un empate lo rechaza. Tras un rechazo, el liderazgo pasa en sentido horario y se intenta de nuevo. Cinco propuestas rechazadas seguidas dan la victoria inmediata al Mal.'),
      L('Only the approved team secretly plays quest cards. Good must play Success; Evil may choose Success or Fail. Shuffle before revealing. Usually 1 Fail defeats a quest; quest 4 needs 2 Fails with 7+ players.', 'Solo el equipo aprobado juega cartas de misión en secreto. El Bien debe jugar Éxito; el Mal puede elegir Éxito o Fracaso. Mezcla antes de revelar. Normalmente 1 Fracaso hace fallar la misión; la misión 4 necesita 2 con 7 jugadores o más.'),
      L('Record the result, reset the rejection count and pass leadership clockwise. After 3 successes, keep identities hidden: Evil discusses and Assassin names Merlin. A correct guess gives Evil the win; a wrong guess gives Good the win.', 'Anota el resultado, reinicia los rechazos y pasa el liderazgo en sentido horario. Tras 3 éxitos, mantén los personajes ocultos: el Mal debate y el Asesino señala a Merlín. Si acierta gana el Mal; si falla gana el Bien.')
    ],
    reminder: L('Voting on a team is public and everyone participates. Quest cards are secret and only team members play them.', 'La votación del equipo es pública y participan todos. Las cartas de misión son secretas y solo las juegan los integrantes del equipo.'),
    sections: [
      section('setup', L('Setup & choosing roles', 'Preparación y selección de personajes'), [
        L('Use the board for your player count. Give everyone Approve and Reject tokens, deal one shuffled secret character each, choose the first leader randomly, and set the quest and rejection markers to their starting positions. Keep the quest cards and result markers nearby. Never show your character or use its printed artwork to prove your identity during play.', 'Usa el tablero correspondiente a la cantidad de jugadores. Entrega fichas de Aprobar y Rechazar a cada persona, reparte un personaje secreto al azar, elige al primer líder al azar y coloca los marcadores de misión y rechazos al inicio. Deja cerca las cartas de misión y los marcadores de resultado. No muestres tu personaje ni uses su ilustración para demostrar tu identidad durante la partida.'),
        L('Basic setup: Merlin plus ordinary Loyal Servants on Good; Assassin plus ordinary Minions on Evil. Optional setup: replace ordinary cards with Percival, Morgana, Mordred or Oberon, preserving the Good/Evil totals. Keep Merlin and Assassin for the rules in this guide. The setup helper limits optional roles to the available places.', 'Preparación básica: Merlín y Leales a Arturo en el Bien; Asesino y Esbirros en el Mal. Preparación opcional: sustituye cartas normales por Percival, Morgana, Mordred u Oberón, sin alterar los totales de cada bando. Conserva a Merlín y al Asesino para las reglas de esta guía. El asistente limita los personajes opcionales a los lugares disponibles.'),
        L('Before the first proposal, read the opening script with pauses. All Evil except Oberon see one another. Merlin sees Evil except Mordred, including Oberon. If included, Percival sees Merlin and Morgana together without learning which is which. All of this information stays secret.', 'Antes de la primera propuesta, lee el guion inicial con pausas. Todo el Mal excepto Oberón se reconoce. Merlín ve al Mal excepto Mordred, incluido Oberón. Si participa, Percival ve a Merlín y a Morgana juntos, sin distinguir quién es quién. Toda esa información es secreta.')
      ]),
      section('teams', L('Propose a team & vote', 'Proponer un equipo y votar'), [
        L('The leader chooses a team with exactly the number of players required for this quest. The leader may join the team. Everyone may discuss, say which role they have, accuse others or lie. Then every player, including those outside the team, secretly chooses Approve or Reject. Reveal all votes at the same time.', 'El líder elige un equipo con la cantidad exacta de jugadores que pide la misión. Puede incluirse en el equipo. Todos pueden conversar, decir qué personaje tienen, acusar o mentir. Después, todos los jugadores, incluso quienes no integran el equipo, eligen Aprobar o Rechazar en secreto. Muestren todos los votos a la vez.'),
        L('More than half the players must approve. A tie is a rejection. When rejected, keep the same quest, advance the rejection counter and pass leadership clockwise for a new proposal. Five consecutive rejections end the game in an Evil victory; the fifth team is still voted on. An approved team breaks the rejection streak.', 'Debe aprobar más de la mitad de los jugadores. Un empate es rechazo. Al rechazar, conserva la misma misión, avanza el contador de rechazos y pasa el liderazgo en sentido horario para otra propuesta. Cinco rechazos consecutivos dan la victoria al Mal; el quinto equipo también se vota. Aprobar un equipo rompe la racha de rechazos.')
      ]),
      section('quests', L('Resolve a quest & move on', 'Resolver una misión y avanzar'), [
        L('Give each team member a Success card and a Fail card. Each person secretly plays one. Good players must play Success; Evil players may choose either card. Mix the played cards before revealing them so nobody knows who played each one. Collect and mix the unused cards separately to keep those choices secret too.', 'Entrega a cada integrante del equipo una carta de Éxito y una de Fracaso. Cada persona juega una en secreto. Los jugadores del Bien deben jugar Éxito; los del Mal pueden elegir cualquiera. Mezcla las cartas jugadas antes de mostrarlas para que nadie sepa quién puso cada una. Recoge y mezcla por separado las cartas que no se usaron, para mantener esas elecciones en secreto.'),
        L('Zero Fails means success. One or more means failure, except quest 4 with 7–10 players, which needs at least 2 Fails. That exception does not apply to quest 5. Mark the result and move to the next quest whether the previous one succeeded or failed; pass leadership clockwise.', 'Cero Fracasos significa éxito. Uno o más significa fracaso, salvo la misión 4 con 7–10 jugadores, que requiere al menos 2 Fracasos. La excepción no se aplica a la misión 5. Marca el resultado y avanza a la siguiente misión tanto si hubo éxito como fracaso; pasa el liderazgo en sentido horario.'),
        L('Example: with 7 players, quest 4 sends 4 people. Three Success cards and one Fail still succeed. Two Success cards and two Fails fail. A successful quest does not prove that everyone on its team is Good.', 'Ejemplo: con 7 jugadores, la misión 4 lleva a 4 personas. Tres Éxitos y un Fracaso dan éxito. Dos Éxitos y dos Fracasos hacen fallar la misión. Una misión exitosa no demuestra que todos sus integrantes sean del Bien.')
      ]),
      section('ending', L('Winning & the assassination', 'Victoria y asesinato'), [
        L('Stop immediately when 3 quests have failed: Evil wins. Also stop if 5 teams are rejected consecutively on the same quest. If 3 quests succeed instead, do not reveal roles yet. Evil discusses and the Assassin chooses one Good player as Merlin. If correct, Evil wins; otherwise Good wins. There is only one assassination guess.', 'Termina en cuanto fallen 3 misiones: gana el Mal. También termina si se rechazan 5 equipos consecutivos para la misma misión. Si se logran 3 éxitos, todavía no revelen los personajes. El Mal debate y el Asesino elige a un jugador del Bien como Merlín. Si acierta gana el Mal; si falla gana el Bien. Solo hay un intento de asesinato.')
      ]),
      section('optional', L('Optional characters', 'Personajes opcionales'), [
        L('Percival is Good and learns who Merlin is; if Morgana is present, Percival sees two possibilities. Morgana is Evil and appears alongside Merlin to Percival. Mordred is Evil and stays hidden from Merlin, but recognizes the other Evil players normally. Oberon is Evil but neither sees nor is seen by the other Evil players during their opening recognition; Merlin still sees him.', 'Percival pertenece al Bien y reconoce a Merlín; si está Morgana, ve dos posibilidades. Morgana pertenece al Mal y aparece junto a Merlín ante Percival. Mordred pertenece al Mal y permanece oculto para Merlín, pero reconoce normalmente al resto del Mal. Oberón pertenece al Mal, pero no ve ni es visto por sus aliados durante el reconocimiento inicial; Merlín sí lo ve.'),
        L('Add optional characters a few at a time. Percival usually helps Good. Mordred and Morgana help Evil. Oberon makes it harder for Evil players to work together. These characters change what players know. Good must still play Success, and Evil may still choose either quest card. Only Assassin chooses whom to identify as Merlin at the end.', 'Agrega personajes opcionales de a poco. Percival suele ayudar al Bien. Mordred y Morgana ayudan al Mal. Oberón dificulta que los jugadores del Mal se coordinen. Estos personajes cambian la información que recibe cada uno. El Bien igual debe jugar Éxito y el Mal puede elegir cualquiera de las dos cartas de misión. Solo el Asesino elige a quién señalar como Merlín al final.')
      ]),
      section('lady', L('Lady of the Lake', 'Dama del Lago'), [
        L('Optional; recommended with 7 or more players. Give the Lady of the Lake token to the player on the first leader’s right. After quests 2, 3 and 4, if the game continues, the token holder chooses another player who has not used it before. That player privately shows their Good or Evil loyalty card. You learn their side, not their character.', 'Es opcional y se recomienda con 7 jugadores o más. Entrega la ficha de la Dama del Lago a quien esté a la derecha del primer líder. Después de las misiones 2, 3 y 4, si la partida sigue, quien tiene la ficha elige a otra persona que todavía no la haya usado. Esa persona muestra en secreto su carta de lealtad del Bien o del Mal. Así se conoce su bando, no su personaje.'),
        L('The chosen player must show their true side; showing the wrong loyalty card loses the game. The token holder may lie about what they saw, but cannot show the card to others. Give the Lady token to the player whose side was checked. Anyone who has used the Lady cannot be checked later. Everyone can see who holds the token. Players keep their original characters.', 'La persona elegida debe mostrar su bando real; mostrar la carta de lealtad incorrecta hace perder la partida. Quien tiene la ficha puede mentir sobre lo que vio, pero no puede mostrar esa carta a los demás. Entrega la ficha de la Dama a la persona que mostró su bando. No se puede elegir después a alguien que ya haya usado la Dama. La ficha queda a la vista y cada persona conserva su personaje original.')
      ]),
      section('targeting', L('Optional quest order', 'Orden opcional de misiones'), [
        L('Targeting variant: the leader proposes both an unattempted quest and its team. Use that quest’s team size and mark its result in its own space. Each quest can be attempted only once. Quest 5 is unavailable until two quests have succeeded. With 7+ players, quest 4 still needs 2 Fails, wherever it appears in the order. Start with the normal fixed order while learning.', 'Variante de selección: el líder propone una misión aún no intentada y su equipo. Usa el tamaño de esa misión y marca el resultado en su casilla. Cada misión se intenta una sola vez. La misión 5 no está disponible hasta lograr dos éxitos. Con 7 jugadores o más, la misión 4 sigue requiriendo 2 Fracasos, sin importar cuándo se intente. Para aprender, usa el orden fijo normal.')
      ])
    ],
    sources: [[L('The Resistance: Avalon · rules', 'The Resistance: Avalon · reglamento'), 'https://avalon.fun/pdfs/rules.pdf'], [L('Avalon · publisher', 'Avalon · editorial'), 'https://indieboardsandcards.com/our-games/the-resistance-avalon/']]
  },
  poker: {
    name: L('Poker', 'Póker'), subtitle: L('Learn the hands. Choose how to bet.', 'Conoce las jugadas. Decide cómo apostar.'), category: L('No-Limit Texas Hold’em', 'Texas Hold’em sin límite'), players: '2–10', time: '30–90+', icon: 'spade', color: 'mint',
    description: L('Two private cards, five shared cards, endless possibilities.', 'Dos cartas propias, cinco compartidas y muchas posibilidades.'),
    goal: L('Win chips by making everyone else fold, or by showing the strongest five-card hand. Use any five of your two private cards and the five community cards—even none of your private cards.', 'Gana fichas haciendo que todos se retiren o mostrando la mejor mano de cinco cartas. Usa cinco entre tus dos cartas propias y las cinco comunitarias; puedes no usar ninguna propia.'),
    basics: [
      L('Use a 52-card deck without jokers. Agree on chip values, how many chips each player starts with and when to stop. Blinds are required bets made before seeing your cards. The dealer marker, called the button, moves to the left each hand. The next two players pay the small and big blinds. Deal 2 face-down cards to each player.', 'Usa un mazo de 52 cartas sin comodines. Acuerden el valor de las fichas, cuántas recibe cada persona y cuándo termina la partida. Las ciegas son apuestas obligatorias que se hacen antes de ver las cartas. La ficha del repartidor, llamada botón, pasa a la izquierda en cada mano. Los dos jugadores siguientes ponen la ciega chica y la grande. Reparte 2 cartas boca abajo a cada persona.'),
      L('Before the flop, the player to the left of the big blind starts. Fold means leave this hand. Call means match the current bet. Raise means increase it. If you do not need to add chips, you may check: stay in without betting more. The big blind still gets a turn if everyone else only calls.', 'Antes del flop, empieza quien está a la izquierda de la ciega grande. Puedes retirarte de esta mano, igualar la apuesta actual o subirla. Si no necesitas agregar fichas, puedes pasar: sigues jugando sin apostar más. Quien puso la ciega grande también tiene su turno aunque todos solo hayan igualado.'),
      L('Put 3 shared cards face up on the table: the flop. Then add 1 card, the turn, and finally 1 more, the river. There is a betting round after each stage. Before each deal, set aside 1 card face down without using it; this is called burning a card. From the flop onward, the first player still in the hand to the left of the button acts first.', 'Coloca 3 cartas compartidas boca arriba en la mesa: el flop. Después agrega 1 carta, el turn, y por último otra, el river. Hay una ronda de apuestas después de cada etapa. Antes de cada reparto, aparta 1 carta boca abajo sin usarla: eso se llama quemar una carta. Desde el flop, empieza el primer jugador a la izquierda del botón que siga en la mano.'),
      L('The pot is all the chips bet during the hand. If everyone but one player folds, that player wins the pot without showing cards. Otherwise, after the last betting round, compare the best five-card hands. Equal hands share the pot. Move the button and deal the next hand.', 'El pozo reúne todas las fichas apostadas en esa mano. Si todos se retiran menos una persona, esa persona gana el pozo sin mostrar sus cartas. Si quedan varias, comparen sus mejores jugadas de cinco cartas después de la última ronda de apuestas. Si empatan, reparten el pozo. Mueve el botón y reparte la siguiente mano.')
    ],
    reminder: L('A hand always has five cards. A sixth card never breaks a tie, and suits have equal strength.', 'Una mano siempre tiene cinco cartas. Una sexta carta nunca desempata y todos los palos valen lo mismo.'),
    sections: [
      section('setup', L('Table setup & dealing', 'Preparación y reparto'), [
        L('This guide is for No-Limit Texas Hold’em: you may bet all the chips you have on the table. Before playing, agree on chip values, starting chips and blinds (required starting bets). For a casual game, you can keep the blinds fixed and set an end time. For a tournament, agree on when blinds increase and whether players may pay to enter or get more chips. Example: blinds of 1 and 2, with 200 chips each. You can play without money.', 'Esta guía explica Texas Hold’em sin límite: puedes apostar todas las fichas que tienes en la mesa. Antes de jugar, acuerden el valor de las fichas, cuántas recibe cada persona y las ciegas (apuestas iniciales obligatorias). En una partida informal, pueden mantener las ciegas fijas y acordar una hora de finalización. En un torneo, acuerden cuándo aumentan las ciegas y si se puede pagar para entrar o recibir más fichas. Ejemplo: ciegas de 1 y 2, con 200 fichas por persona. Se puede jugar sin dinero.'),
        L('Shuffle 52 cards without jokers. Place a marker, called the button, in front of the dealer. Moving to the left, the next active player pays the small blind and the following player pays the big blind. Deal one card at a time to the left, starting with the player after the button, until everyone has 2 face-down cards. Keep cards and chips on the table.', 'Mezcla 52 cartas sin comodines. Coloca una ficha, llamada botón, frente al repartidor. Hacia la izquierda, el siguiente jugador activo pone la ciega chica y el que sigue pone la ciega grande. Reparte una carta por vez hacia la izquierda, empezando después del botón, hasta que todos tengan 2 cartas boca abajo. Mantén las cartas y las fichas sobre la mesa.'),
        L('With exactly 2 players, the button posts the small blind and acts first before the flop; the big blind acts first after the flop. The big blind receives the first dealt card. Move the button clockwise between hands.', 'Con exactamente 2 jugadores, el botón pone la ciega chica y actúa primero antes del flop; la ciega grande actúa primero después. La ciega grande recibe la primera carta del reparto. Mueve el botón en sentido horario entre manos.')
      ]),
      section('betting', L('Betting actions & minimum raises', 'Acciones y subidas mínimas'), [
        L('Fold: leave this hand and lose the chips you already bet. Check: stay in without adding chips, only when you have no bet to match. Bet: make the first bet of this round. Call: add enough chips to match the current bet, or all your remaining chips if you have less. Raise: increase the current bet. All-in: bet all your remaining chips. You cannot bet chips that are not on the table.', 'Retirarse (fold): dejas esta mano y pierdes las fichas que ya apostaste. Pasar (check): sigues sin agregar fichas, solo si no hay una apuesta pendiente por igualar. Apostar (bet): haces la primera apuesta de esta ronda. Igualar (call): agregas lo necesario para alcanzar la apuesta actual, o todas tus fichas si no te alcanza. Subir (raise): aumentas la apuesta actual. Ir con todo (all-in): apuestas todas las fichas que te quedan. No puedes apostar fichas que no tengas en la mesa.'),
        L('The first bet must be at least the big blind. A raise must add at least as much as the last full bet or raise added. Example with blinds 1/2: raising the bet from 2 to 6 adds 4, so the next raise must reach at least 10. If you do not have enough chips, you may still go all-in for less. An all-in below the minimum raise does not by itself let players who already acted raise again.', 'La primera apuesta debe ser al menos igual a la ciega grande. Una subida debe agregar como mínimo lo mismo que agregó la última apuesta o subida completa. Ejemplo con ciegas 1/2: subir de 2 a 6 agrega 4, así que la siguiente subida debe llegar por lo menos a 10. Si no te alcanzan las fichas, igual puedes ir con todo por menos. Un all-in menor que la subida mínima no permite, por sí solo, que quienes ya actuaron vuelvan a subir.'),
        L('Several small all-ins can add up to a full raise. A player may raise again if the total increase since their last action reaches the minimum full raise. A betting round ends when every player still in the hand has acted and matched the bet, except players who are already all-in. When one player goes all-in, the others may keep betting against each other.', 'Varios all-ins pequeños pueden sumar una subida completa. Una persona puede volver a subir si el aumento total desde su última acción alcanza la subida mínima. La ronda de apuestas termina cuando todos los que siguen en la mano actuaron e igualaron la apuesta, salvo quienes ya apostaron todas sus fichas. Si alguien va con todo, los demás pueden seguir apostando entre sí.')
      ]),
      section('streets', L('The four betting rounds', 'Las cuatro rondas de apuestas'), [
        L('Pre-flop: two private cards each; begin left of the big blind. Flop: burn one face-down card, deal three community cards face up, then bet. Turn: burn one, deal a fourth community card, then bet. River: burn one, deal the fifth community card, then bet. From the flop onward, action starts with the first remaining player clockwise from the button.', 'Preflop: dos cartas privadas por persona; empieza quien está a la izquierda de la ciega grande. Flop: quema una carta boca abajo, muestra tres comunitarias y apuesta. Turn: quema una, muestra la cuarta y apuesta. River: quema una, muestra la quinta y apuesta. Desde el flop, empieza la primera persona que siga en la mano en sentido horario desde el botón.'),
        L('A burn card stays out of play and is not shown. If everyone but one player folds, award the pot immediately; do not deal more cards. If all remaining players are all-in, finish the community cards without further betting and compare eligible hands.', 'Una carta quemada queda fuera del juego y no se muestra. Si todos menos una persona se retiran, entrega el pozo inmediatamente y no repartas más cartas. Si quienes quedan están all-in, completa las comunitarias sin más apuestas y compara las manos que correspondan.')
      ]),
      section('showdown', L('Showdown, ties & side pots', 'Mostrar cartas, empates y pozos secundarios'), [
        L('At showdown the last player to bet or raise on the river shows first; if nobody did, start with the first remaining player left of the button. Show both private cards to claim a contested pot. Build the best 5-card hand from all 7 available cards. You may use zero, one or two private cards.', 'Al mostrar, empieza quien hizo la última apuesta o subida en el river; si nadie apostó, empieza la primera persona activa a la izquierda del botón. Muestra ambas cartas privadas para reclamar un pozo disputado. Forma la mejor mano de 5 con las 7 cartas disponibles. Puedes usar cero, una o dos privadas.'),
        L('Compare the type of hand first, then the card values that decide a tie. Extra cards used to break ties are called kickers. With two pairs, compare the higher pair, then the lower pair, then the fifth card. With a full house, compare the three matching cards before the pair. With a straight, compare the highest card: A–2–3–4–5 counts as five-high. Ace can be low or high, but K–A–2 is not a sequence. Equal five-card hands share the pot; suits do not break ties. Give any leftover chip that cannot be split to the first tied player to the left of the button.', 'Compara primero el tipo de jugada y después los valores de las cartas. Las cartas que completan la jugada y sirven para desempatar se llaman kickers. Con doble par, compara el par mayor, luego el menor y después la quinta carta. En un full, compara primero el trío y después el par. En una escalera, compara la carta más alta: en A–2–3–4–5 es el 5. El as puede ir al principio o al final, pero K–A–2 no es una secuencia. Si las cinco cartas tienen el mismo valor, se reparte el pozo; el palo no desempata. Si sobra una ficha que no se puede dividir, va al primer jugador empatado a la izquierda del botón.'),
        L('A player who goes all-in can win only the amount they matched from each opponent. Example: A bets 20, B bets 50 and C bets 50. Put 20 from each player in the main pot: 60, which any of the three can win. Put the remaining 30 from B and 30 from C in a side pot: 60, which only B or C can win. Decide each pot separately. A player who folded cannot win, but their bet stays in the pot. Return any part of a bet that no other player matched.', 'Quien apuesta todas sus fichas solo puede ganar la cantidad que igualó de cada rival. Ejemplo: A apuesta 20, B 50 y C 50. Coloca 20 de cada persona en el pozo principal: son 60 que puede ganar cualquiera de los tres. Los 30 restantes de B y los 30 de C forman un pozo secundario de 60 que solo pueden ganar B o C. Resuelve cada pozo por separado. Quien se retiró no puede ganar, pero sus fichas quedan en el pozo. Devuelve cualquier parte de una apuesta que nadie haya igualado.'),
        L('Winning a hand is different from winning a session. A tournament ends when one player has all the chips. In a casual fixed-blind session, stop at the agreed time and count chips.', 'Ganar una mano no es lo mismo que ganar la sesión. Un torneo termina cuando alguien reúne todas las fichas. En una sesión informal con ciegas fijas, terminen a la hora acordada y cuenten las fichas.')
      ])
    ],
    sources: [[L('Texas Hold’em · PokerStars', 'Texas Hold’em · PokerStars'), 'https://www.pokerstars.com/poker/games/texas-holdem/'], [L('Poker rules · PokerStars', 'Reglas de póker · PokerStars'), 'https://www.pokerstars.com/poker/games/rules/']]
  },
  moth: {
    name: L('Cheating Moth', 'La Polilla Tramposa'), subtitle: L('Get rid of your cards without being caught.', 'Deshazte de tus cartas sin que te descubran.'), category: L('Cards & hidden tricks', 'Cartas y trampas'), players: '3–5', time: '15–25', icon: 'moth', color: 'yellow',
    description: L('Make your cards disappear. Just don’t let the guard see.', 'Haz desaparecer tus cartas sin que el guardián te vea.'),
    goal: L('Empty your hand by playing cards and secretly making cards disappear. Play as many rounds as there are players; the lowest total penalty score wins.', 'Vacía tu mano jugando cartas y haciéndolas desaparecer en secreto. Jueguen tantas rondas como participantes; gana quien acumule menos puntos de penalización.'),
    basics: [
      L('The oldest player gets the Guard Bug card and becomes the guard. Shuffle the other cards and give each player 8. Put the rest face down as a draw pile. Turn over the top card to start a discard pile; ignore any special effect on that first card. The guard starts.', 'La persona de mayor edad recibe la carta de la Chinche Guardiana y será el guardián. Mezcla las demás cartas y reparte 8 a cada persona. El resto queda boca abajo en un mazo. Da vuelta la carta de arriba para iniciar la pila de descarte; ignora su efecto especial. Empieza el guardián.'),
      L('Play one card on top of the discard pile. Its number must be exactly 1 higher or lower. On a 1, you can play 2 or 5; on a 5, you can play 4 or 1. If you cannot play, take 1 card from the draw pile and end your turn.', 'Juega una carta sobre la pila de descarte. Su número debe ser exactamente 1 más o 1 menos. Sobre un 1 puedes jugar 2 o 5; sobre un 5 puedes jugar 4 o 1. Si no puedes jugar, toma 1 carta del mazo y termina tu turno.'),
      L('Everyone except the guard may secretly hide or drop cards, one at a time, even outside their turn. Keep the hand holding your cards above the table. Never hide or drop your last card. Stop cheating while an accusation is being resolved.', 'Todos menos el guardián pueden esconder o dejar caer cartas en secreto, de a una, incluso fuera de su turno. Mantén sobre la mesa la mano que sostiene tus cartas. Nunca escondas ni dejes caer tu última carta. Nadie puede hacer trampa mientras se resuelve una acusación.'),
      L('Only the guard can accuse someone of cheating. If the guard catches you, take back your card, receive a card other than a moth from the guard, and become the new guard. If the accusation is wrong, the guard takes 1 card from the deck and remains the guard.', 'Solo el guardián puede acusar a alguien de hacer trampa. Si te descubre, recupera tu carta, recibe del guardián una carta que no sea polilla y pasa a ser el nuevo guardián. Si la acusación es incorrecta, el guardián toma 1 carta del mazo y sigue siendo el guardián.')
    ],
    reminder: L('Moths cannot be played or given away—except the guard may play them by the normal number rule. Never save a moth as your last card!', 'Las polillas no se pueden jugar ni regalar, salvo que el guardián las juegue respetando la regla numérica. ¡No dejes una polilla como última carta!'),
    sections: [
      section('setup', L('Setup & normal turns', 'Preparación y turnos normales'), [
        L('Set aside the Guard Bug and give it face up to the oldest player. Shuffle the remaining cards, deal 8 each, and use the rest as a draw pile. Reveal its top card to start the discard pile. Only its number matters; do not trigger a starting action card. The guard begins and turns go clockwise.', 'Separa la Chinche Guardiana y entrégala boca arriba a la persona de mayor edad. Mezcla el resto, reparte 8 por persona y forma un mazo con las restantes. Revela la primera carta para iniciar los descartes. Solo importa su número; no actives su efecto especial. Empieza el guardián y sigan en sentido horario.'),
        L('On your turn, play one card with a number exactly 1 higher or lower than the top discard. On 1, play 2 or 5; on 5, play 4 or 1. Action cards follow this same rule and then trigger their effect. If you have no legal card, draw one and stop; you do not immediately play the drawn card. When the draw pile runs out, recycle and shuffle the discards to refill it.', 'En tu turno, juega una carta con un número exactamente 1 más o 1 menos que la carta de arriba del descarte. Sobre un 1 puedes jugar 2 o 5; sobre un 5, 4 o 1. Las cartas especiales siguen la misma regla y luego aplican su efecto. Si no tienes una carta válida, toma una y termina; no la juegas inmediatamente. Cuando se agote el mazo, recicla y mezcla los descartes para reponerlo.')
      ]),
      section('cheating', L('Cheating, moths & the guard', 'Trampas, polillas y guardián'), [
        L('The guard plays normal turns but cannot cheat. Other players may secretly remove number cards, action cards or moths one at a time. Keep the hand holding your cards above the table. Never make your final card disappear. Nobody may cheat while an accusation is being resolved.', 'El guardián juega sus turnos normales, pero no puede hacer trampa. Los demás pueden quitarse cartas numéricas, especiales o polillas en secreto, de una en una. Mantén sobre la mesa la mano que sostiene tus cartas. Nunca hagas desaparecer tu última carta. Nadie puede hacer trampa mientras se resuelve una acusación.'),
        L('A moth cannot normally be discarded or handed to another player. You must sneak it away. The guard is the exception: they can play a moth on their turn if its number fits. This does not allow the guard to give moths away.', 'Una polilla normalmente no se puede descartar ni entregar a otra persona. Debes hacerla desaparecer. El guardián es la excepción: puede jugarla en su turno si su número encaja. Eso no le permite regalar polillas.'),
        L('Only the guard may accuse, and must catch the act; other players cannot report cheats. If correct, the caught player retrieves the disappearing card, takes one non-moth card from the guard’s hand and receives the Guard Bug. If wrong, the guard draws a penalty card and stays guard.', 'Solo el guardián puede acusar y debe descubrir la trampa en el momento; los demás no pueden delatar. Si acierta, la persona descubierta recupera la carta, recibe una carta que no sea polilla de la mano del guardián y recibe la Chinche Guardiana. Si se equivoca, el guardián toma una carta de penalización y conserva su función.')
      ]),
      section('insects', L('Every insect effect', 'Efecto de cada insecto'), [
        L('Spider: after playing it, you may give one card from your hand to any opponent, except a moth. Mosquito: everyone except the player who played it must touch the card as quickly as possible. The last person to touch it receives one card other than a moth from every other player, including the person who played the mosquito.', 'Araña: después de jugarla, puedes darle una carta de tu mano a cualquier rival, excepto una polilla. Mosquito: todos menos quien lo jugó deben tocar la carta lo más rápido posible. Quien la toque en último lugar recibe una carta que no sea polilla de cada uno de los demás, incluido quien jugó el mosquito.'),
        L('Cockroach: anyone, including the player who played it, may quickly put a number card with no special effect on top. It must have the same number as the cockroach. Only the first card stays; everyone else takes theirs back. If nobody plays a card, continue normally. Ant: everyone except the player who played it takes 1 card from the deck.', 'Cucaracha: cualquiera, incluso quien la jugó, puede poner rápidamente encima una carta de número sin efecto especial. Debe tener el mismo número que la cucaracha. Solo queda la primera carta; los demás recuperan las suyas. Si nadie juega una carta, la partida sigue normalmente. Hormiga: todos menos quien la jugó toman 1 carta del mazo.')
      ]),
      section('scoring', L('End of a round & scoring', 'Fin de ronda y puntuación'), [
        L('The round ends as soon as a player has no cards. Count penalty points for cards left in each hand: number cards 1 each, action cards 5 each, moths 10 each. The player who emptied their hand gets 0. Example: 2 number cards + 1 spider + 1 moth = 17 penalty points.', 'La ronda termina en cuanto alguien se queda sin cartas. Cuenta penalizaciones por lo que quede en cada mano: 1 por carta numérica, 5 por especial y 10 por polilla. Quien vació su mano recibe 0. Ejemplo: 2 cartas numéricas + 1 araña + 1 polilla = 17 puntos.'),
        L('Collect all cards, including hidden ones, and deal a fresh round. The player left of the previous round’s starting player becomes the new starting guard, regardless of who held the Guard Bug at the end. Play one round per player, then compare cumulative penalties. Lowest total wins.', 'Recoge todas las cartas, incluidas las escondidas, y reparte otra ronda. Quien está a la izquierda de la persona que inició la ronda anterior será el nuevo guardián inicial, sin importar quién tenía la Chinche al final. Jueguen una ronda por participante y comparen las penalizaciones acumuladas. Gana quien tenga menos puntos.')
      ])
    ],
    sources: [[L('Cheating Moth · Drei Magier / Schmidt Spiele', 'La Polilla Tramposa · Drei Magier / Schmidt Spiele'), 'https://www.schmidtspiele.de/files/Produkte/4/40862%20-%20Mogel%20Motte/40862_Mogelmotte_DE_GB_FR_IT.pdf']]
  }
};
const AVALON_SETUPS = {5:{good:3,evil:2,quests:[2,3,2,3,3]},6:{good:4,evil:2,quests:[2,3,4,3,4]},7:{good:4,evil:3,quests:[2,3,3,4,4]},8:{good:5,evil:3,quests:[3,4,4,5,5]},9:{good:6,evil:3,quests:[3,4,4,5,5]},10:{good:6,evil:4,quests:[3,4,4,5,5]}};
const AVALON_ROLES = [
 {id:'merlin', side:'good', name:L('Merlin','Merlín'),text:L('Sees Evil, except Mordred. Must avoid the final assassination.','Ve al Mal, excepto a Mordred. Debe evitar el asesinato final.')},
 {id:'assassin', side:'evil', name:L('Assassin','Asesino'),text:L('Makes the final guess at Merlin after 3 successful quests.','Intenta identificar a Merlín tras 3 misiones exitosas.')},
 {id:'percival', side:'good', name:L('Percival','Percival'),text:L('Sees Merlin and Morgana, but cannot tell them apart. Without Morgana, sees Merlin alone.','Ve a Merlín y a Morgana sin distinguirlos. Sin Morgana, solo ve a Merlín.')},
 {id:'morgana', side:'evil', name:L('Morgana','Morgana'),text:L('Appears to Percival alongside Merlin.','Aparece junto a Merlín ante Percival.')},
 {id:'mordred', side:'evil', name:L('Mordred','Mordred'),text:L('Hidden from Merlin. Recognizes Evil normally.','Oculto para Merlín. Reconoce al Mal normalmente.')},
 {id:'oberon', side:'evil', name:L('Oberon','Oberón'),text:L('Does not recognize Evil and is not recognized by Evil. Merlin sees him.','No reconoce al Mal ni es reconocido por el Mal. Merlín sí lo ve.')}
];
const POKER_HANDS = [
 [L('Royal flush','Escalera real'),'A♥ K♥ Q♥ J♥ 10♥',L('10, J, Q, K and A, all of the same suit. The strongest hand.','10, J, Q, K y A del mismo palo. Es la jugada más fuerte.')],
 [L('Straight flush','Escalera de color'),'9♠ 8♠ 7♠ 6♠ 5♠',L('Five cards in number order, all of the same suit.','Cinco cartas con valores seguidos y del mismo palo.')],
 [L('Four of a kind','Póker'),'Q♠ Q♥ Q♦ Q♣ 2♥',L('Four cards of the same value. The fifth card breaks a tie.','Cuatro cartas del mismo valor. La quinta sirve para desempatar.')],
 [L('Full house','Full'),'J♠ J♥ J♦ 4♣ 4♥',L('Three cards of one value and two of another. Compare the group of three first.','Tres cartas de un valor y dos de otro. Compara primero el trío.')],
 [L('Flush','Color'),'A♦ J♦ 8♦ 6♦ 2♦',L('Five cards of the same suit. Compare their values from highest to lowest.','Cinco cartas del mismo palo. Compara sus valores de mayor a menor.')],
 [L('Straight','Escalera'),'8♠ 7♥ 6♦ 5♣ 4♥',L('Five cards in number order. A–2–3–4–5 is the lowest straight.','Cinco cartas con valores seguidos. A–2–3–4–5 es la escalera más baja.')],
 [L('Three of a kind','Trío'),'7♠ 7♥ 7♦ K♣ 2♥',L('Three cards of the same value. The two remaining cards break ties.','Tres cartas del mismo valor. Las otras dos sirven para desempatar.')],
 [L('Two pair','Doble par'),'K♠ K♥ 5♦ 5♣ 9♥',L('Two cards of one value and two of another. The fifth card breaks a tie.','Dos cartas de un valor y dos de otro. La quinta sirve para desempatar.')],
 [L('One pair','Par'),'10♠ 10♥ A♦ 8♣ 3♥',L('Two cards of the same value. The other three cards break ties.','Dos cartas del mismo valor. Las otras tres sirven para desempatar.')],
 [L('High card','Carta alta'),'A♠ J♥ 8♦ 6♣ 3♥',L('None of the above. Compare all five ranks from highest down.','Ninguna de las anteriores. Compara los cinco valores de mayor a menor.')]
];
GAMES.coup.sections.splice(4, 0, section('reformation', L('Reformation: sides & the coin reserve', 'Reformation: bandos y reserva de monedas'), [
  L('Reformation adds two sides, called allegiances. You still win alone by eliminating every other player. Put the empty Treasury Reserve card in the center, separate from the bank. This card holds coins paid for changing sides. Give each player an Allegiance card. The first player chooses Loyalist or Reformist. Continue to the left, alternating sides. Use the normal Coup rules with the changes below.', 'Reformation agrega dos bandos, llamados lealtades. Sigues ganando por tu cuenta al eliminar a los demás. Coloca la carta Reserva del Tesoro vacía en el centro, separada del banco. Allí van las monedas que se pagan por cambiar de bando. Reparte una carta de Lealtad a cada persona. Quien empieza elige Leal o Reformista. Sigue hacia la izquierda, alternando bandos. Se usan las reglas normales de Coup con los cambios siguientes.'),
  L('While players from both sides remain, you cannot use Coup, Assassinate, Steal or Examine against someone on your side. You also cannot block their Foreign Aid. You may challenge them. If all remaining players are on the same side, these limits stop applying until there are two sides again. Your Allegiance card does not reveal your hidden characters.', 'Mientras queden jugadores de ambos bandos, no puedes usar Golpe, Asesinar, Robar ni Examinar contra alguien de tu bando. Tampoco puedes bloquear su Ayuda extranjera. Sí puedes desafiarlo. Si todos los que siguen jugando son del mismo bando, esas restricciones dejan de aplicarse hasta que vuelva a haber dos bandos. Tu carta de Lealtad no revela tus personajes ocultos.'),
  L('Convert means change sides. Use your turn to pay 1 coin to change your own side, or 2 coins to change another active player’s side. Turn over that Allegiance card and put the coins in the Treasury Reserve, not the bank. No character is needed. This action cannot be blocked or challenged. With 10 or more coins at the start of your turn, you must use Coup instead.', 'Convertir significa cambiar de bando. Usa tu turno para pagar 1 moneda y cambiar tu propio bando, o 2 monedas para cambiar el de otra persona que siga jugando. Da vuelta la carta de Lealtad y coloca las monedas en la Reserva del Tesoro, no en el banco. No necesitas un personaje. No se puede bloquear ni desafiar esta acción. Si empiezas con 10 monedas o más, debes dar un Golpe en su lugar.'),
  L('Embezzle means take all the coins from the Treasury Reserve. Use your turn to say you have no face-down Duke and take those coins. The action cannot be blocked, but any other active player can challenge your statement. A Duke already face up from lost influence does not stop you from taking this action.', 'Malversar significa llevarte todas las monedas de la Reserva del Tesoro. Usa tu turno para decir que no tienes ningún Duque boca abajo y toma esas monedas. No se puede bloquear, pero cualquier otra persona que siga jugando puede desafiar lo que dijiste. Un Duque que ya está boca arriba porque perdiste esa influencia no impide usar esta acción.'),
  L('If challenged while you have a face-down Duke, you must accept losing the challenge. You may also accept losing if you have no Duke. Return the coins to the reserve and lose 1 influence. To prove you have no Duke, show all your face-down cards. The challenger loses 1 influence. Shuffle the cards you just showed into the deck and take the same number of new cards. Keep the reserve coins. Showing cards this way does not remove your influence.', 'Si te desafían y tienes un Duque boca abajo, debes aceptar que pierdes el desafío. También puedes aceptar perder aunque no tengas Duque. Devuelve las monedas a la reserva y pierde 1 influencia. Para demostrar que no tienes Duque, muestra todas tus cartas boca abajo. Quien te desafió pierde 1 influencia. Mezcla las cartas que acabas de mostrar en el mazo y toma la misma cantidad de cartas nuevas. Conserva las monedas de la reserva. Mostrar las cartas de esta manera no te quita influencia.'),
  L('Example: Alex and Sol are Loyalists; Dani is Reformist. Alex cannot steal from Sol, but can pay 2 coins to change Sol to Reformist. That ends the turn. Loyalists can now attack Sol. If all remaining players later share one side, they can attack each other again. Inquisitor is a separate option that replaces Ambassador. Its Examine action follows the same rule against attacking your own side.', 'Ejemplo: Alex y Sol son Leales; Dani es Reformista. Alex no puede robarle a Sol, pero puede pagar 2 monedas para cambiar a Sol al bando Reformista. Allí termina el turno. Ahora los Leales pueden atacar a Sol. Si más adelante todos los que siguen jugando quedan en el mismo bando, pueden volver a atacarse entre sí. El Inquisidor es una opción independiente que reemplaza al Embajador. Su acción Examinar también respeta la regla que impide atacar al propio bando.')
]));
