/* Dixit base game: publisher's 2021 refresh rules, 3–8 players. */
GAMES.dixit={
 name:L('Dixit','Dixit'),subtitle:L('A clue. A picture. A little imagination.','Una pista. Una imagen. Un poco de imaginación.'),category:L('Storytelling & imagination','Historias e imaginación'),players:'3–8',time:'30',icon:'sparkle',color:'lavender',
 description:L('Give a clue, hide your picture among the others, and follow your imagination.','Da una pista, mezcla tu imagen con las demás y sigue tu imaginación.'),
 goal:L('Finish a round with the most points when someone reaches 30. As storyteller, aim for some correct guesses—not everyone and not nobody.','Termina una ronda con más puntos cuando alguien llegue a 30. Como narrador, intenta que algunos acierten: ni todos ni nadie.'),
 basics:[
 L('Shuffle the 84 picture cards. Give everyone 6 cards, a rabbit at 0, and matching voting pieces. Keep hands secret. With 3 players, deal 7 cards instead.','Baraja las 84 cartas ilustradas. Cada persona recibe 6 cartas, un conejo en 0 y sus piezas de voto. Las manos son secretas. Con 3 jugadores, reparte 7 cartas.'),
 L('The storyteller chooses one hidden card and says a clue: a word, phrase, sound, song or mime. Everyone else secretly submits one card that fits. With 3 players, each other player submits two.','El narrador elige una carta oculta y da una pista: palabra, frase, sonido, canción o mímica. Los demás entregan en secreto una carta que encaje. Con 3 jugadores, cada uno de los otros entrega dos.'),
 L('The storyteller shuffles all submitted cards with their own and displays them in numbered slots. Everyone except the storyteller secretly votes for the storyteller’s card. Never vote for your own. Reveal votes together.','El narrador mezcla todas las cartas entregadas con la suya y las muestra en lugares numerados. Todos excepto el narrador votan en secreto por la carta del narrador. No votes por la tuya. Revelen los votos a la vez.'),
 L('If some but not all guess correctly: storyteller +3, correct voters +3. If everyone or nobody guesses correctly: storyteller 0, everyone else +2. In either case, non-storytellers also earn +1 for every vote on their own card.','Si algunos aciertan, pero no todos: narrador +3 y cada acierto +3. Si todos o nadie aciertan: narrador 0 y todos los demás +2. En ambos casos, los demás también suman +1 por cada voto recibido en su carta.'),
 L('Score everyone, discard the played cards and refill hands. Pass storytelling to the left. If someone has reached 30 or more, highest score wins; ties share the win. Otherwise, play another round.','Puntúen a todos, descarten las cartas jugadas y repongan las manos. El papel de narrador pasa a la izquierda. Si alguien llegó a 30 o más, gana la puntuación mayor; los empates comparten victoria. Si no, jueguen otra ronda.')
 ],
 reminder:L('The storyteller never votes. You cannot vote for your own card. Bonus votes count even when nobody finds the storyteller.','El narrador no vota. No puedes votar por tu propia carta. Los votos extra cuentan incluso cuando nadie acierta la del narrador.'),
 sections:[
 section('setup',L('Setup & edition','Preparación y edición'),[
 L('This guide uses the standard Dixit 2021 refresh: 3–8 players, 84 illustrated cards, a score board, 8 rabbits and 8 voting dials. It does not cover Odyssey or Disney. Older boxes may support only 3–6 players; use the capacity printed on your box.','Esta guía usa Dixit estándar, edición renovada de 2021: 3–8 jugadores, 84 cartas ilustradas, un tablero, 8 conejos y 8 diales de voto. No cubre Odyssey ni Disney. Las cajas antiguas pueden admitir solo 3–6 jugadores; respeta la cantidad de tu caja.'),
 L('Choose colors, place rabbits at 0 and shuffle the cards. Deal 6 face down to each player; the rest form a draw pile. Keep space for a discard pile and numbered face-up cards. The first person ready with a clue becomes the first storyteller.','Elijan colores, coloquen los conejos en 0 y barajen. Reparte 6 cartas boca abajo por persona; el resto forma el mazo. Deja sitio para los descartes y las cartas numeradas boca arriba. Empieza como narrador quien primero tenga una pista.')]),
 section('clue',L('Give a clue & submit cards','Dar una pista y entregar cartas'),[
 L('The storyteller selects one card without showing it and gives a clue inspired by its image. Words, quotations, sounds, songs and gestures are allowed. The clue should suggest the picture without making it obvious to everybody.','El narrador elige una carta sin mostrarla y da una pista inspirada en la imagen. Se permiten palabras, citas, sonidos, canciones y gestos. La pista debe sugerir la imagen sin resultar obvia para todos.'),
 L('Each other player chooses the card in their hand that best fits that clue and gives it face down to the storyteller. Mix those cards together with the storyteller’s card. Lay them face up at numbered positions so nobody can tell who submitted each card.','Cada otra persona elige la carta de su mano que mejor encaje con la pista y la entrega boca abajo. Mezcla esas cartas con la del narrador. Colócalas boca arriba en posiciones numeradas sin revelar quién entregó cada una.')]),
 section('vote',L('Secret voting','Votación secreta'),[
 L('Every player except the storyteller selects one numbered card using their dial or voting token. Your goal is to find the storyteller’s card, not simply your favorite picture. You may not vote for any card you submitted. Once everyone is ready, reveal votes simultaneously. The storyteller then identifies their card.','Todos excepto el narrador eligen una carta numerada con su dial o ficha de voto. Debes encontrar la carta del narrador, no tu imagen favorita. No puedes votar por ninguna carta que hayas entregado. Cuando estén listos, revelen los votos a la vez. El narrador indica cuál era su carta.')]),
 section('scoring',L('Score the round','Puntuar la ronda'),[
 L('Some, but not all, guess correctly: give the storyteller 3 points and each correct voter 3 points. Incorrect voters get no guessing points.','Algunos aciertan, pero no todos: el narrador recibe 3 puntos y cada persona que acierta recibe 3. Quienes fallan no suman puntos por adivinar.'),
 L('All guess correctly, or nobody does: the storyteller gets 0 points and every other player gets 2 points.','Todos aciertan o nadie acierta: el narrador recibe 0 puntos y cada otro jugador recibe 2.'),
 L('Then, in both cases, every non-storyteller adds 1 point per vote received on their own card. The storyteller receives no vote bonus. The 2021 base-game rulebook used here sets no three-point cap on this bonus. Move every rabbit before checking the winner.','Después, en ambos casos, cada jugador que no sea narrador añade 1 punto por voto recibido en su carta. El narrador no recibe este extra. El reglamento base de 2021 usado aquí no fija un máximo de tres puntos para este extra. Mueve todos los conejos antes de comprobar quién gana.'),
 L('Example with 5 players: two of the four voters find the storyteller. Storyteller +3; those two voters +3 each; the other two +0 for guessing. Any non-storyteller whose card attracted votes adds +1 per vote, even if they guessed incorrectly.','Ejemplo con 5 jugadores: dos de los cuatro votantes aciertan. Narrador +3; los dos aciertos +3 cada uno; los otros dos +0 por adivinar. Quien no sea narrador añade +1 por cada voto en su carta, aunque haya fallado al adivinar.')]),
 section('ending',L('Next round & winning','Siguiente ronda y victoria'),[
 L('Discard the played cards face up and draw back to 6 cards. If the draw pile cannot refill everyone’s hand, shuffle the remaining draw cards with the discards to make a new pile. The next storyteller is the player to the left.','Descarta las cartas jugadas boca arriba y roba hasta tener 6. Si el mazo no alcanza para reponer todas las manos, mezcla las cartas restantes con los descartes para formar otro mazo. La persona de la izquierda será el siguiente narrador.'),
 L('After scoring a round, if anyone has 30 or more points, the game ends. The player with the highest total wins, even if somebody else crossed 30 first. Tied leaders share victory. In this edition an empty deck is reshuffled; it does not end the game. Some older editions use different ending rules—follow the rulebook supplied with those boxes.','Tras puntuar una ronda, si alguien tiene 30 puntos o más, termina la partida. Gana el total mayor, aunque otra persona haya cruzado 30 primero. Los líderes empatados comparten victoria. En esta edición se vuelve a barajar el mazo agotado; no termina la partida. Algunas ediciones antiguas usan otro final: sigue el reglamento incluido en esas cajas.')]),
 section('three',L('Exactly 3 players','Exactamente 3 jugadores'),[
 L('Keep 7 cards in each hand. The storyteller submits one card; each of the other two players submits two, giving five cards to choose from. Each non-storyteller still casts just one vote and cannot vote for either of their own cards.','Mantén 7 cartas por mano. El narrador entrega una carta y cada uno de los otros dos jugadores entrega dos: hay cinco para elegir. Cada uno de los otros sigue emitiendo un único voto y no puede votar por ninguna de sus dos cartas.'),
 L('Scoring stays the same: if exactly one voter finds the storyteller, both that voter and the storyteller score 3. If both or neither find it, storyteller 0 and the other two +2 each. Add +1 for a vote received on either of your own cards. Refill to 7: storyteller draws one, others two.','La puntuación no cambia: si solo un votante acierta, ese votante y el narrador suman 3. Si ambos o ninguno aciertan, narrador 0 y los demás +2 cada uno. Añade +1 por un voto recibido en cualquiera de tus cartas. Repón hasta 7: el narrador roba una y los otros dos.')])
 ],
 sources:[['Dixit · Libellud / Asmodee · 2021 rules','https://cdn.svc.asmodee.net/production-asmodeeca/uploads/2023/07/DIXIT_REFRESH_RULES_US-UK-AU_BD.pdf']]
};
function dixitHelper(){return dixitSheet()+`<details class="practice-fold" id="dixit-example"><summary>${tr('See a scoring example','Ver un ejemplo de puntuación')}</summary><p>${e(GAMES.dixit.sections.find(s=>s.id==='scoring').paragraphs[3])}</p></details>`;}
