/* Dixit base game: publisher's 2021 refresh rules, 3–8 players. */
GAMES.dixit={
 name:L('Dixit','Dixit'),subtitle:L('A clue. A picture. A little imagination.','Una pista. Una imagen. Un poco de imaginación.'),category:L('Storytelling & imagination','Historias e imaginación'),players:'3–8',time:'30',icon:'sparkle',color:'lavender',
 description:L('Give a clue, hide your picture among the others, and follow your imagination.','Da una pista, mezcla tu imagen con las demás y sigue tu imaginación.'),
 goal:L('Try to finish with the most points. The game ends after a round in which someone reaches 30 or more. When you give the clue, try to help some players find your card, but not everyone.','Intenta terminar con la mayor cantidad de puntos. La partida termina después de una ronda en la que alguien llega a 30 o más. Cuando te toque dar la pista, intenta que algunos encuentren tu carta, pero no todos.'),
 basics:[
 L('Shuffle the 84 picture cards. Give each player 6 cards and a rabbit marker on space 0 of the score board. Give them voting pieces in the same color. Keep your cards hidden. With 3 players, deal 7 cards each instead.','Mezcla las 84 cartas con imágenes. Reparte 6 a cada persona y coloca su ficha de conejo en el 0 del tablero de puntos. Entrega las piezas para votar del mismo color. No muestres tus cartas. Si juegan 3 personas, reparte 7 cartas a cada una.'),
 L('The storyteller is the player giving the clue this round. Choose one card without showing it. Give a clue: a word, phrase, sound, song or gesture. Everyone else secretly gives you one card that matches the clue. With 3 players, each of the other two gives you 2 cards.','El narrador es quien da la pista en esa ronda. Elige una carta sin mostrarla. Da una pista: una palabra, frase, sonido, canción o gesto. Los demás te entregan en secreto una carta que se relacione con la pista. Si juegan 3 personas, cada una de las otras dos entrega 2 cartas.'),
 L('The storyteller mixes the cards received with their own card and places them face up in numbered spaces. Everyone else secretly votes for the card they think belongs to the storyteller. You cannot vote for your own cards. Show all votes at the same time.','El narrador mezcla las cartas recibidas con la suya y las coloca boca arriba en espacios numerados. Los demás votan en secreto por la carta que creen que es del narrador. No puedes votar por tus propias cartas. Muestren todos los votos a la vez.'),
 L('If some players guess correctly, but not everyone: the storyteller and each correct voter get 3 points. If everyone or nobody guesses correctly: the storyteller gets 0 and each other player gets 2. In both cases, everyone except the storyteller also gets 1 point for each vote their own cards receive.','Si algunos aciertan, pero no todos: el narrador y cada persona que acertó suman 3 puntos. Si todos aciertan o nadie acierta: el narrador suma 0 y cada uno de los demás suma 2. En ambos casos, todos menos el narrador también suman 1 punto por cada voto recibido en sus propias cartas.'),
 L('Move the rabbit markers to add all points. Put the played cards in the discard pile and take new cards to refill your hand. The player to the left becomes the next storyteller. If anyone has 30 or more points, the highest total wins. Players tied for the highest total share the win. Otherwise, play another round.','Mueve las fichas de conejo para sumar todos los puntos. Aparta las cartas jugadas y toma cartas del mazo hasta volver a tener la cantidad inicial. La persona de la izquierda será el siguiente narrador. Si alguien tiene 30 puntos o más, gana quien tenga el total más alto. Si varias personas empatan en el primer lugar, comparten la victoria. Si no, jueguen otra ronda.')
 ],
 reminder:L('The storyteller does not vote. You cannot vote for your own cards. You still get points for votes on your cards when nobody finds the storyteller’s card.','El narrador no vota. No puedes votar por tus propias cartas. Los votos que reciben tus cartas igual suman puntos aunque nadie encuentre la del narrador.'),
 sections:[
 section('setup',L('Setup & edition','Preparación y edición'),[
 L('This guide uses the standard Dixit 2021 refresh: 3–8 players, 84 illustrated cards, a score board, 8 rabbits and 8 voting dials. It does not cover Odyssey or Disney. Older boxes may support only 3–6 players; use the capacity printed on your box.','Esta guía usa Dixit estándar, edición renovada de 2021: 3–8 jugadores, 84 cartas ilustradas, un tablero, 8 conejos y 8 ruedas para votar. No cubre Odyssey ni Disney. Las cajas antiguas pueden admitir solo 3–6 jugadores; respeta la cantidad de tu caja.'),
 L('Choose colors, place rabbits at 0 and shuffle the cards. Deal 6 face down to each player; the rest form a draw pile. Keep space for a discard pile and numbered face-up cards. The first person ready with a clue becomes the first storyteller.','Elijan colores, coloquen los conejos en 0 y mezclen. Reparte 6 cartas boca abajo por persona; el resto forma el mazo. Deja sitio para los descartes y las cartas numeradas boca arriba. Empieza como narrador quien primero tenga una pista.')]),
 section('clue',L('Give a clue & submit cards','Dar una pista y entregar cartas'),[
 L('The storyteller selects one card without showing it and gives a clue inspired by its image. Words, quotations, sounds, songs and gestures are allowed. The clue should suggest the picture without making it obvious to everybody.','El narrador elige una carta sin mostrarla y da una pista inspirada en la imagen. Se permiten palabras, citas, sonidos, canciones y gestos. La pista debe sugerir la imagen sin resultar obvia para todos.'),
 L('Each other player chooses the card in their hand that best fits that clue and gives it face down to the storyteller. Mix those cards together with the storyteller’s card. Lay them face up at numbered positions so nobody can tell who submitted each card.','Cada una de las demás personas elige la carta de su mano que mejor encaje con la pista y la entrega boca abajo. Mezcla esas cartas con la del narrador. Colócalas boca arriba en posiciones numeradas sin revelar quién entregó cada una.')]),
 section('vote',L('Secret voting','Votación secreta'),[
 L('Every player except the storyteller selects one numbered card using their dial or voting token. Your goal is to find the storyteller’s card, not simply your favorite picture. You may not vote for any card you submitted. Once everyone is ready, reveal votes simultaneously. The storyteller then identifies their card.','Todos excepto el narrador eligen una carta numerada con su rueda o ficha para votar. Debes encontrar la carta del narrador, no tu imagen favorita. No puedes votar por ninguna carta que hayas entregado. Cuando estén listos, revelen los votos a la vez. El narrador indica cuál era su carta.')]),
 section('scoring',L('Score the round','Puntuar la ronda'),[
 L('Some, but not all, guess correctly: give the storyteller 3 points and each correct voter 3 points. Incorrect voters get no guessing points.','Algunos aciertan, pero no todos: el narrador recibe 3 puntos y cada persona que acierta recibe 3. Quienes fallan no suman puntos por adivinar.'),
 L('All guess correctly, or nobody does: the storyteller gets 0 points and every other player gets 2 points.','Todos aciertan o nadie acierta: el narrador recibe 0 puntos y cada uno de los demás jugadores recibe 2.'),
 L('In both cases, each player except the storyteller also gets 1 point for each vote their own cards receive. There is no limit of 3 points for these extra votes in the 2021 rules used here. The storyteller does not get extra points for votes. Add all players’ points before checking who wins.','En ambos casos, cada persona que no sea el narrador también suma 1 punto por cada voto recibido en sus propias cartas. Las reglas de 2021 que usa esta guía no ponen un límite de 3 puntos a ese extra. El narrador no suma puntos extra por los votos. Suma los puntos de todos antes de ver quién ganó.'),
 L('Example with 5 players: two of the four voters find the storyteller. Storyteller +3; those two voters +3 each; the other two +0 for guessing. Any non-storyteller whose card attracted votes adds +1 per vote, even if they guessed incorrectly.','Ejemplo con 5 jugadores: dos de los cuatro votantes aciertan. Narrador +3; las dos personas que aciertan +3 cada una; los otros dos +0 por adivinar. Quien no sea narrador añade +1 por cada voto en su carta, aunque haya fallado al adivinar.')]),
 section('ending',L('Next round & winning','Siguiente ronda y victoria'),[
 L('Discard the played cards face up and draw back to 6 cards. If the draw pile cannot refill everyone’s hand, shuffle the remaining draw cards with the discards to make a new pile. The next storyteller is the player to the left.','Descarta las cartas jugadas boca arriba y toma cartas hasta tener 6. Si el mazo no alcanza para reponer todas las manos, mezcla las cartas restantes con los descartes para formar otro mazo. La persona de la izquierda será el siguiente narrador.'),
 L('After scoring a round, if anyone has 30 or more points, the game ends. The player with the highest total wins, even if somebody else crossed 30 first. Tied leaders share victory. In this edition an empty deck is reshuffled; it does not end the game. Some older editions use different ending rules—follow the rulebook supplied with those boxes.','Tras puntuar una ronda, si alguien tiene 30 puntos o más, termina la partida. Gana quien tenga más puntos, aunque otra persona haya cruzado 30 primero. Los líderes empatados comparten victoria. En esta edición se vuelve a mezclar el mazo agotado; no termina la partida. Algunas ediciones antiguas usan otro final: sigue el reglamento incluido en esas cajas.')]),
 section('three',L('Exactly 3 players','Exactamente 3 jugadores'),[
 L('Keep 7 cards in each hand. The storyteller submits one card; each of the other two players submits two, giving five cards to choose from. Each non-storyteller still casts just one vote and cannot vote for either of their own cards.','Mantén 7 cartas por mano. El narrador entrega una carta y cada uno de los otros dos jugadores entrega dos: hay cinco para elegir. Cada uno de los otros sigue emitiendo un único voto y no puede votar por ninguna de sus dos cartas.'),
 L('Scoring stays the same: if exactly one voter finds the storyteller, both that voter and the storyteller score 3. If both or neither find it, storyteller 0 and the other two +2 each. Add +1 for a vote received on either of your own cards. Refill to 7: storyteller draws one, others two.','La puntuación no cambia: si solo un votante acierta, ese votante y el narrador suman 3. Si ambos o ninguno aciertan, narrador 0 y los demás +2 cada uno. Añade +1 por un voto recibido en cualquiera de tus cartas. Vuelvan a tener 7 cartas: el narrador toma 1 del mazo y cada uno de los demás toma 2.')])
 ],
 sources:[[L('Dixit · Libellud / Asmodee · 2021 rules','Dixit · Libellud / Asmodee · reglas de 2021'),'https://cdn.svc.asmodee.net/production-asmodeeca/uploads/2023/07/DIXIT_REFRESH_RULES_US-UK-AU_BD.pdf']]
};
function dixitHelper(){return dixitSheet()+`<details class="practice-fold" id="dixit-example"><summary>${tr('See a scoring example','Ver un ejemplo de puntuación')}</summary><p>${e(GAMES.dixit.sections.find(s=>s.id==='scoring').paragraphs[3])}</p></details>`;}
