/* Visual learning tools. All examples are instructional, not game automation. */
const visualState={steps:{},street:0,quest:1,fails:0,coins:2,mothGuess:null,guard:false,mothCard:false};
function lessonSteps(){
 const steps=[...GAMES[state.game].basics];
 if(state.game==='coup'&&state.reformation)steps.push(L('Reformation: use your turn to change your side for 1 coin or another player’s side for 2. Pay into the reserve. Another option is to say you have no hidden Duke and take all reserve coins (Embezzle). If challenged, show all hidden cards to prove it, or accept losing 1 influence and return the coins. See the full rules for details.','Reformation: usa tu turno para cambiar tu bando por 1 moneda o el de otra persona por 2. Paga a la reserva. Otra opción es decir que no tienes Duque oculto y llevarte las monedas de la reserva (Malversar). Si te desafían, muestra todas tus cartas ocultas para demostrarlo o acepta perder 1 influencia y devuelve las monedas. Consulta los detalles en las reglas completas.'));
 return contextualBasics(state.game,steps,state);
}
function lesson(){
 const steps=lessonSteps();const n=Math.min(visualState.steps[state.game]||0,steps.length-1);visualState.steps[state.game]=n;
 const titles={dixit:[L('Deal the pictures','Reparte las imágenes'),L('Give a clue','Da una pista'),L('Find the storyteller’s card','Encuentra la carta del narrador'),L('Count the points','Cuenta los puntos'),L('Start the next round','Empieza la siguiente ronda')],coup:[L('Set the table','Prepara la mesa'),L('Make your move','Haz tu jugada'),L('Challenge a character','Desafía un personaje'),L('Stay in the game','Sigue en la partida'),L('Change sides','Cambia de bando')],avalon:[L('Deal secret roles','Reparte personajes'),L('Propose a team','Propón un equipo'),L('Vote together','Voten juntos'),L('Go on the quest','Completen la misión'),L('Protect Merlin','Protejan a Merlín')],poker:[L('Cards, chips & blinds','Cartas, fichas y ciegas'),L('Make your first bet','Haz tu primera apuesta'),L('Reveal the shared cards','Muestra las cartas compartidas'),L('Find the winning hand','Encuentra la mano ganadora')],moth:[L('Meet the guard','Conoce al guardián'),L('Play your card','Juega tu carta'),L('Be a little sneaky','Haz una pequeña trampa'),L('When the guard catches you','Cuando el guardián te descubre')]};
 titles[state.game] ||= GAMES[state.game].lessonTitles;
 return `<section id="basics" class="block"><div class="lesson-heading"><h2>${tr('Learn one move at a time.','Aprende una jugada a la vez.')}</h2><span class="lesson-counter">${n+1} / ${steps.length}</span></div><div class="lesson" aria-roledescription="${tr('Step-by-step guide','Guía paso a paso')}"><div class="lesson-dots" role="group" aria-label="${tr('Choose a step','Elige un paso')}">${steps.map((_,i)=>`<button id="lesson-step-${i}" data-step="${i}" aria-label="${tr('Step','Paso')} ${i+1}: ${e(titles[state.game][i])}" aria-current="${i===n?'step':'false'}"><span>${i<n?'✓':i+1}</span></button>`).join('')}</div><div class="lesson-copy" aria-live="polite" aria-atomic="true"><span class="eyebrow muted">${tr('STEP','PASO')} ${n+1}</span><h3>${e(titles[state.game][n])}</h3><p>${glossaryText(state.game,t(steps[n]))}</p></div>${lessonCardBlock(state.game,n,state)}${lessonComparisons(n)}${inlineLessonPractice(n)}<div class="lesson-buttons"><button id="lesson-prev" ${n===0?'disabled':''}>${icon('back')}${tr('Previous','Anterior')}</button>${n<steps.length-1?`<button id="lesson-next" class="accent-button">${tr('Next step','Siguiente')}${icon('arrow')}</button>`:`<a class="accent-button" href="#${state.game}/reference">${tr('Ready to play','Listo para jugar')}${icon('check')}</a>`}</div></div><details class="lesson-overview" id="lesson-overview"><summary>${tr('See all steps together','Ver todos los pasos juntos')}</summary><ol class="step-list">${steps.map(s=>`<li>${glossaryText(state.game,t(s))}</li>`).join('')}</ol></details></section>`;
}
function learningSetup(){
 const g=GAMES[state.game], setup=g.sections.find(s=>s.id==='setup'||s.id==='menu')||g.sections[0];
 return `<section id="learn-setup" class="learning-setup block" aria-labelledby="learn-setup-heading"><span class="eyebrow">${tr('BEFORE THE FIRST TURN','ANTES DEL PRIMER TURNO')}</span><h2 id="learn-setup-heading">${tr('Set up the game','Prepara la partida')}</h2>${state.game==='avalon'?avalonHelper('setup'):`${(selectedSetup(state.game,state).length?selectedSetup(state.game,state):setup.paragraphs).map(p=>`<p>${e(p)}</p>`).join('')}${portableSetupVisuals()}${state.game==='skull_king'&&state.skullExpansion?g.expansionSections.find(s=>s.id==='expansion-setup').paragraphs.map(p=>`<p>${e(p)}</p>`).join(''):''}`}</section>`;
}
function learningPage(){const g=GAMES[state.game];return `<div id="goal" class="goal-box"><div class="eyebrow">${tr('THE GOAL','EL OBJETIVO')}</div><p>${glossaryText(state.game,t(g.goal))}</p></div>${learningSetup()}${state.game==='skull_king'?skullTrickLesson():''}${state.game==='coup'?coupLesson():''}${state.game==='avalon'?avalonLesson():''}${lesson()}${scoringExample()}<div class="callout"><strong>${tr('Keep in mind.','Recuerda.')} </strong>${e(g.reminder)}</div><section id="helper">${fold('learning-tools',L('Card photos & practice','Fotos de cartas y práctica'),helper(false),practiceHint('learn'))}</section><a class="inline-link" href="#${state.game}/full">${tr('Read the full rules & exceptions','Leer las reglas completas y excepciones')}${icon('arrow')}</a>`;}
function playingCard(value,visible=true){return `<span class="playing-card ${visible?'face-up':'face-down'} ${/[♥♦]/.test(value)?'red':''}" aria-label="${visible?escapeHTML(value):tr('Unrevealed community card','Carta comunitaria sin revelar')}">${visible?`<span>${escapeHTML(value.slice(0,-1))}</span><b>${value.slice(-1)}</b>`:`<span aria-hidden="true">✧</span>`}</span>`;}
const STREETS=[
 [L('Pre-flop','Preflop'),L('Two cards, just for you.','Dos cartas, solo para ti.'),L('You hold A♥ Q♥. Before any community cards appear, betting begins left of the big blind. You may fold, call or raise. This example follows a hand that stays in play.','Tienes A♥ Q♥. Antes de mostrar comunitarias, empieza a apostar quien está a la izquierda de la ciega grande. Puedes retirarte, igualar o subir. En este ejemplo sigues en la mano.')],
 [L('Flop','Flop'),L('Three shared cards. One pair.','Tres compartidas. Un par.'),L('The dealer burns one card and reveals Q♣ 7♥ 2♠. You now have a pair of queens. A betting round starts with the first active player left of the button.','El repartidor quema una carta y revela Q♣ 7♥ 2♠. Ahora tienes par de reinas. Empieza a apostar la primera persona activa a la izquierda del botón.')],
 [L('Turn','Turn'),L('You need one more heart for a flush.','Falta un corazón para formar color.'),L('Burn a card and reveal 9♥. With A♥ Q♥ in your hand and 7♥ 9♥ on the table, you have four hearts. You still have one pair, not a flush yet. Another betting round follows.','Quema una carta y revela 9♥. Con A♥ Q♥ en tu mano y 7♥ 9♥ en la mesa, tienes cuatro corazones. Todavía tienes un par; aún no hay color. Sigue otra ronda de apuestas.')],
 [L('River','River'),L('Five hearts. A flush.','Cinco corazones. Un color.'),L('Burn a card and reveal 3♥. Your best five cards are A♥ Q♥ 9♥ 7♥ 3♥: an ace-high flush. There is one final betting round.','Quema una carta y revela 3♥. Tus mejores cinco cartas son A♥ Q♥ 9♥ 7♥ 3♥: color al as. Queda una última ronda de apuestas.')],
 [L('Showdown','Mostrar'),L('Use the best five of seven.','Usa las mejores cinco de siete.'),L('If several players remain, compare their best five-card hands. Your flush beats a straight or three of a kind, but loses to a full house. A flush is strong, not a guaranteed win. Equal five-card hands split the pot.','Si quedan varios jugadores, comparen sus mejores cinco cartas. Tu color supera una escalera o un trío, pero pierde ante un full. El color es fuerte, pero no garantiza ganar. Cinco cartas equivalentes dividen el pozo.')]
];
function pokerDemo(){const s=visualState.street;const shown=[0,3,4,5,5][s];return `<section class="playground" id="poker-demo"><div class="playground-heading"><span class="eyebrow">${tr('PLAY THROUGH A HAND','RECORRE UNA MANO')}</span><h2>${tr('See your cards at each stage.','Mira tus cartas en cada etapa.')}</h2><p>${tr('Tap through each betting round. The cards and explanation change together.','Avanza por las rondas de apuestas. Las cartas y la explicación cambian juntas.')}</p></div><div class="poker-table"><p class="table-label">${tr('YOUR CARDS','TUS CARTAS')}</p><div class="private-cards">${playingCard('A♥')}${playingCard('Q♥')}</div><p class="table-label">${tr('COMMUNITY CARDS','CARTAS COMUNITARIAS')}</p><div class="community-cards">${['Q♣','7♥','2♠','9♥','3♥'].map((c,i)=>playingCard(c,i<shown)).join('')}</div></div><div class="street-picker" role="group" aria-label="${tr('Betting round','Ronda de apuestas')}">${STREETS.map((r,i)=>`<button id="street-${i}" data-street="${i}" aria-label="${e(r[0])}" aria-pressed="${s===i}"><span class="street-full">${e(r[0])}</span><span class="street-short" aria-hidden="true">${i===4?tr('Show','Mostrar'):e(r[0])}</span></button>`).join('')}</div><div class="demo-explanation" aria-live="polite" aria-atomic="true"><h3>${e(STREETS[s][1])}</h3><p>${e(STREETS[s][2])}</p></div><div class="demo-actions"><button id="street-prev" ${s===0?'disabled':''}>${icon('back')}${tr('Back','Atrás')}</button><button id="street-next" class="accent-button">${s===4?tr('Start again','Volver a empezar'):tr('Reveal next','Revelar siguiente')}${icon('arrow')}</button></div></section>`;}
function questDemo(){
 const q=visualState.quest, n=AVALON_SETUPS[state.players].quests[q-1];const maxFails=Math.min(n,AVALON_SETUPS[state.players].evil);visualState.fails=Math.min(visualState.fails,maxFails);const threshold=q===4&&state.players>=7?2:1;const success=visualState.fails<threshold;
 return `<section class="playground" id="quest-demo"><div class="playground-heading"><span class="eyebrow">${tr('TRY A QUEST','PRUEBA UNA MISIÓN')}</span><h2>${tr('Does this quest succeed?','¿Esta misión tiene éxito?')}</h2><p>${tr(`Explore the result for your ${state.players}-player setup. This is a practice example.`,`Explora el resultado para tus ${state.players} jugadores. Es un ejemplo de práctica.`)}</p></div><div class="quest-picker" role="group" aria-label="${tr('Choose a quest','Elige una misión')}">${[1,2,3,4,5].map(i=>`<button id="quest-pick-${i}" data-quest="${i}" aria-pressed="${q===i}"><small>${tr('Quest','Misión')}</small>${i}</button>`).join('')}</div><div class="counter-row"><div><strong>${tr('Fail cards revealed','Cartas de Fracaso')}</strong><small>${tr(`${n} people on the team`,`${n} personas en el equipo`)}</small></div><div class="counter"><button id="fail-less" aria-label="${tr('Remove one Fail','Quitar un Fracaso')}" ${visualState.fails===0?'disabled':''}>−</button><output id="fail-count">${visualState.fails}</output><button id="fail-more" aria-label="${tr('Add one Fail','Añadir un Fracaso')}" ${visualState.fails===maxFails?'disabled':''}>+</button></div></div><div class="quest-result ${success?'success':'failure'}" aria-live="polite" aria-atomic="true"><strong>${success?tr('✓ Quest succeeds','✓ Misión exitosa'):tr('× Quest fails','× Misión fallida')}</strong><p>${threshold===2?tr('With 7+ players, quest 4 needs TWO Fail cards to fail. One Fail is not enough.','Con 7 jugadores o más, la misión 4 necesita DOS Fracasos para fallar. Uno no basta.'):tr('This quest fails if at least one Fail is revealed. Good must play Success; Evil may play either card.','Esta misión falla si se revela al menos un Fracaso. El Bien debe jugar Éxito; el Mal puede elegir cualquiera.')}</p></div></section>`;
}
function coinDemo(){const n=visualState.coins;const moves=n>=10?[tr('Coup (required)','Golpe (obligatorio)')]:[tr('Income','Ingreso'),tr('Foreign Aid','Ayuda extranjera'),tr('Tax','Impuestos'),tr('Steal','Robar'),tr('Exchange','Intercambiar'),...(state.exchange==='inquisitor'?[tr('Examine','Examinar')]:[]),...(n>=3?[tr('Assassinate','Asesinar')]:[]),...(n>=7?[tr('Coup','Golpe')]:[]),...(state.reformation?[tr('Embezzlement','Malversar'),...(n>=1?[tr('Change your side','Cambiar tu bando')]:[]),...(n>=2?[tr('Change another player’s side','Cambiar el bando de otra persona')]:[])]:[])];return `<section class="playground" id="coin-demo"><div class="playground-heading"><span class="eyebrow">${tr('PLAN YOUR TURN','PREPARA TU TURNO')}</span><h2>${tr('What can these coins do?','¿Qué puedes hacer con estas monedas?')}</h2><p>${tr('Set the coins you have at the start of your turn. Choose one action.','Indica tus monedas al comenzar el turno. Elige una sola acción.')}</p></div><div class="counter-row"><div class="coin-stack" aria-hidden="true">${Array.from({length:Math.min(n,5)},(_,i)=>`<span style="--coin:${i}">✦</span>`).join('')}${n===0?'∅':''}</div><div class="counter"><button id="coin-less" aria-label="${tr('Remove one coin','Quitar una moneda')}" ${n===0?'disabled':''}>−</button><output id="coin-count">${n===12?'12+':n}</output><button id="coin-more" aria-label="${tr('Add one coin','Añadir una moneda')}" ${n===12?'disabled':''}>+</button></div></div><label class="range-label" for="coin-range">${tr('Coins at the start of your turn','Monedas al comenzar tu turno')}</label><input id="coin-range" class="coin-range" type="range" min="0" max="12" value="${n}" aria-valuetext="${n===12?tr('12 or more coins','12 monedas o más'):tr(`${n} coins`,`${n} monedas`)}"><div class="available-moves" aria-live="polite" aria-atomic="true"><strong>${n>=10?tr('You must launch a coup.','Debes dar un golpe.'):tr('Actions you can pay for:','Acciones que puedes pagar:')}</strong><div>${moves.map(m=>`<span>${m}</span>`).join('')}</div><p>${tr('If the action needs a character, you must say you have it. You may be lying. Other players can still challenge or block when allowed.','Si la acción requiere un personaje, debes decir que lo tienes, aunque sea mentira. Los demás pueden desafiar o bloquear cuando las reglas lo permitan.')}${state.reformation?' '+tr('Apply allegiance restrictions when choosing a target.','Aplica las restricciones de bando al elegir objetivo.'):''}</p></div></section>`;}
function mothPractice(){const guess=visualState.mothGuess;const legal=guess!==null&&((guess===((state.mothTop+3)%5+1)||guess===(state.mothTop%5+1))&&(!visualState.mothCard||visualState.guard));return `<section class="playground" id="moth-practice"><div class="playground-heading"><span class="eyebrow">${tr('TRY A DISCARD','PRUEBA UN DESCARTE')}</span><h2>${tr('Can you play this card?','¿Puedes jugar esta carta?')}</h2><p>${tr('Choose the top card of the discard pile above. Then choose a card below to see if you can play it on a normal turn.','Elige arriba la carta que está sobre la pila de descarte. Después elige una carta abajo para ver si puedes jugarla en un turno normal.')}</p></div><div class="discard-practice"><div><span class="eyebrow muted">${tr('TOP OF DISCARD PILE','ÚLTIMA CARTA JUGADA')}</span><span class="number-card">${state.mothTop}</span></div><span class="practice-arrow" aria-hidden="true">→</span><div><span class="eyebrow muted">${tr('YOUR CARD','TU CARTA')}</span><span class="number-card ${visualState.mothCard?'is-moth':''}">${guess??'?'}${visualState.mothCard?icon('moth'):''}</span></div></div><div class="practice-flags"><label class="check-label"><input id="practice-guard" type="checkbox" ${visualState.guard?'checked':''}>${tr('I am the guard','Soy el guardián')}</label><label class="check-label"><input id="practice-moth" type="checkbox" ${visualState.mothCard?'checked':''}>${tr('My card is a moth','Mi carta es una polilla')}</label></div><div class="number-demo" role="group" aria-label="${tr('Number on your card','Número de tu carta')}">${[1,2,3,4,5].map(n=>`<button id="guess-${n}" data-guess="${n}" aria-pressed="${guess===n}">${n}</button>`).join('')}</div><div class="practice-feedback ${guess===null?'':legal?'success':'failure'}" aria-live="polite" aria-atomic="true">${guess===null?tr('Pick a number to test your move.','Elige un número para probar la jugada.'):legal?tr('✓ Legal play! The number fits'+(visualState.mothCard?' and the guard may play moths.':'.'),'✓ ¡Jugada válida! El número encaja'+(visualState.mothCard?' y el guardián puede jugar polillas.':'.')):visualState.mothCard&&!visualState.guard?tr('× Only the guard can play a moth. Other players must sneak it away, never as their last card.','× Solo el guardián puede jugar polillas. Los demás deben esconderlas, nunca como última carta.'):tr('× That number does not fit. Play a number exactly 1 higher or lower. On 1, you can play 2 or 5; on 5, play 4 or 1.','× Ese número no sirve. Debe ser exactamente 1 más o 1 menos. Sobre un 1 puedes jugar 2 o 5; sobre un 5, 4 o 1.')}</div></section>`;}
function patchTool(id,html,focus){const target=document.getElementById(id);if(!target)return;const y=scrollY;target.outerHTML=html;bindLearningTools();if(focus)document.getElementById(focus)?.focus({preventScroll:true});window.scrollTo({top:y,behavior:'instant'});}
function bindLearningTools(){
 bindInlineLessonPractice();
 bindLessonComparisons();
 if($('#practice-helper-retry'))$('#practice-helper-retry').onclick=()=>{if(state.game==='poker'){visualState.street=0;patchTool('poker-demo',pokerDemo(),'street-0');}else{visualState.mothGuess=null;visualState.mothCard=false;visualState.guard=false;patchTool('moth-practice',mothPractice(),'guess-1');}persistPracticeHelpers();};
 bindScoringExample();
 bindScenarioPractice();
 $$('[data-step]').forEach(b=>b.onclick=()=>{visualState.steps[state.game]=+b.dataset.step;render(true);});
 if($('#lesson-prev'))$('#lesson-prev').onclick=()=>{visualState.steps[state.game]--;render(true);};
 if($('#lesson-next'))$('#lesson-next').onclick=()=>{visualState.steps[state.game]++;render(true);$('#lesson-next')?.focus({preventScroll:true});};
 const setStreet=(n,id)=>{visualState.street=n;persistPracticeHelpers();patchTool('poker-demo',pokerDemo(),id);};
 $$('[data-street]').forEach(b=>b.onclick=()=>setStreet(+b.dataset.street,b.id));
 if($('#street-prev'))$('#street-prev').onclick=()=>setStreet(Math.max(0,visualState.street-1),'street-prev');
 if($('#street-next'))$('#street-next').onclick=()=>setStreet((visualState.street+1)%5,'street-next');
 $$('[data-quest]').forEach(b=>b.onclick=()=>{visualState.quest=+b.dataset.quest;patchTool('quest-demo',questDemo(),b.id);});
 for(const [id,delta] of [['fail-less',-1],['fail-more',1]])if($('#'+id))$('#'+id).onclick=()=>{visualState.fails+=delta;patchTool('quest-demo',questDemo(),id);};
 for(const [id,delta] of [['coin-less',-1],['coin-more',1]])if($('#'+id))$('#'+id).onclick=()=>{visualState.coins=Math.max(0,Math.min(12,visualState.coins+delta));patchTool('coin-demo',coinDemo(),id);};
 if($('#coin-range'))$('#coin-range').oninput=event=>{visualState.coins=+event.target.value;$('#coin-count').textContent=visualState.coins===12?'12+':visualState.coins;const template=document.createElement('template');template.innerHTML=coinDemo();for(const selector of ['.available-moves','.coin-stack'])$(selector,$('#coin-demo')).replaceWith($(selector,template.content));$('#coin-less').disabled=visualState.coins===0;$('#coin-more').disabled=visualState.coins===12;event.target.setAttribute('aria-valuetext',visualState.coins===12?tr('12 or more coins','12 monedas o más'):tr(`${visualState.coins} coins`,`${visualState.coins} monedas`));};
 $$('[data-guess]').forEach(b=>b.onclick=()=>{visualState.mothGuess=+b.dataset.guess;persistPracticeHelpers();patchTool('moth-practice',mothPractice(),b.id);});
 for(const [id,key] of [['practice-guard','guard'],['practice-moth','mothCard']])if($('#'+id))$('#'+id).onchange=event=>{visualState[key]=event.target.checked;persistPracticeHelpers();patchTool('moth-practice',mothPractice(),id);};
 if($('#section-jump'))$('#section-jump').onchange=event=>{if(event.target.value)location.hash=`${state.game}/full/${event.target.value}`;};
}

function mothDecisionHelper(){return `<div class="scenario"><h3>${tr('What can I play on this?','¿Qué puedo jugar encima?')}</h3><p class="muted">${tr('Choose the number on top of the discard pile.','Elige el número de la carta superior del descarte.')}</p><div class="number-demo">${[1,2,3,4,5].map(n=>`<button data-number="${n}" aria-pressed="${state.mothTop===n}">${n}</button>`).join('')}</div><p id="moth-result" class="scenario-result" aria-live="polite">${mothResult()}</p></div>${mothPractice()}`;}
function lessonPracticeHelper(){const html=state.game==='poker'?pokerDemo():state.game==='moth'?mothDecisionHelper():'';return html?html+`<button type="button" id="practice-helper-retry">${tr('Try again','Intentar de nuevo')}</button>`:'';}

function persistPracticeHelpers(){
 if(!['poker','moth'].includes(state.game))return;
 try{sessionStorage.setItem(`tablefolk-${typeof sharedRoute!=='undefined'&&sharedRoute?'shared-':''}practice-${state.game}-helper-v1`,JSON.stringify({street:visualState.street,mothGuess:visualState.mothGuess,mothCard:visualState.mothCard,guard:visualState.guard,mothTop:state.mothTop}));}catch{}
}
function recoverPracticeHelpers(){
 if(!['poker','moth'].includes(state.game))return;
 let saved={};try{saved=JSON.parse(sessionStorage.getItem(`tablefolk-${typeof sharedRoute!=='undefined'&&sharedRoute?'shared-':''}practice-${state.game}-helper-v1`)||'{}')||{};}catch{}
 if(state.game==='poker')visualState.street=[0,1,2,3,4].includes(saved.street)?saved.street:0;
 else{state.mothTop=[1,2,3,4,5].includes(saved.mothTop)?saved.mothTop:1;visualState.mothGuess=[1,2,3,4,5].includes(saved.mothGuess)?saved.mothGuess:null;visualState.mothCard=saved.mothCard===true;visualState.guard=saved.guard===true;}
}
