/* Publisher-rule-based guides for Skull King and the two Sushi Go editions. */
Object.assign(GAMES, {
  skull_king: {
    name:L('Skull King','Skull King'), subtitle:L('Bid boldly. Win exactly the tricks you called.','Apuesta con audacia. Gana exactamente las bazas anunciadas.'),
    category:L('Trick-taking & bidding','Bazas y apuestas'), players:'2–8', time:'30–45', icon:'crown', color:'peach',
    caption:L('Pirates, mermaids and a dangerous prediction','Piratas, sirenas y una predicción arriesgada'),
    description:L('Predict your tricks across ten rounds; add the expansion pack with one switch.','Predice tus bazas durante diez rondas; activa el paquete de expansión con un interruptor.'),
    goal:L('Finish ten rounds with the most points. Each round, bid the exact number of tricks you will win.','Termina diez rondas con la mayor puntuación. En cada ronda, anuncia exactamente cuántas bazas ganarás.'),
    basics:[
      L('Remove blank cards, Loot, Kraken and White Whale for a first game. Shuffle and deal 1 card per player in round 1, then 2 in round 2, increasing toward 10. If the deck cannot deal equally to everyone, repeat the largest possible hand size.','Para la primera partida, aparta las cartas en blanco, Botín, Kraken y Ballena Blanca. Mezcla y reparte 1 carta por persona en la ronda 1, luego 2 en la ronda 2, y aumenta hasta 10. Si el mazo no alcanza para repartir a todos por igual, repite el mayor tamaño de mano posible.'),
      L('Look at your hand and announce how many tricks you expect to win. Reveal all bids together. The player left of the dealer leads the first trick.','Mira tu mano y anuncia cuántas bazas esperas ganar. Revelen todas las apuestas a la vez. La persona a la izquierda de quien repartió inicia la primera baza.'),
      L('Play one card clockwise. Follow the led numbered suit if you can; special cards may be played at any time. The winning player takes the trick and leads the next one.','Jueguen una carta por turno en sentido horario. Sigue el palo numérico de salida si puedes; las cartas especiales se pueden jugar en cualquier momento. Quien gane recoge la baza e inicia la siguiente.'),
      L('After the hand, compare tricks won with your bid. A correct positive bid scores 20 per trick; a correct zero scores 10 per card dealt. Wrong bids lose points. Add capture bonuses only for an exact bid.','Al acabar la mano, compara las bazas ganadas con tu apuesta. Una apuesta positiva exacta da 20 por baza; acertar cero da 10 por carta repartida. Los errores restan puntos. Suma bonificaciones por capturas solo si acertaste exactamente.')
    ],
    lessonTitles:[L('Deal the voyage','Reparte la travesía'),L('Make your bid','Anuncia tu apuesta'),L('Fight for tricks','Compite por las bazas'),L('Count the score','Cuenta los puntos')],
    reminder:L('Special cards break the follow-suit rule. A Mermaid beats the Skull King, and a Pirate beats a Mermaid; if all three appear, the Mermaid wins.','Las cartas especiales no están obligadas a seguir palo. Una Sirena vence al Skull King y un Pirata vence a una Sirena; si aparecen los tres, gana la Sirena.'),
    galleryCopy:L('The black numbered suit is trump. Escape and character cards change which play wins; check the card hierarchy before a close trick.','El palo negro numerado es triunfo. Las cartas de Escape y de personaje alteran quién gana; consulta la jerarquía cuando una baza esté reñida.'),
    quick:[
      [L('Bid','Apuesta'),'0–10',L('Predict exactly how many tricks you will take this round. Reveal bids together.','Predice exactamente cuántas bazas ganarás esta ronda. Revelen las apuestas a la vez.')],
      [L('Follow suit','Seguir palo'),'1 card',L('A numbered lead sets a suit. Play that suit if you have it, or play any special card.','Una salida numérica fija el palo. Juega ese palo si lo tienes, o cualquier carta especial.')],
      [L('Who wins?','¿Quién gana?'),'⚑',L('Numbers: highest led suit, unless black trump is played. Characters change the result: Pirate beats Mermaid, King beats Pirate, and Mermaid wins when all three meet.','Numeradas: gana la mayor del palo de salida, salvo que haya triunfo negro. Los personajes cambian el resultado: Pirata supera a Sirena, Rey supera a Pirata y Sirena gana si coinciden los tres.')],
      [L('Exact bid','Apuesta exacta'),'+20',L('Positive bid: 20 per won trick. Zero bid: 10 per card dealt. Capture bonuses count only when exact.','Apuesta positiva: 20 por baza ganada. Apuesta cero: 10 por carta repartida. Las bonificaciones cuentan solo al acertar.')],
      [L('Wrong bid','Apuesta fallida'),'−10',L('Positive bid: lose 10 per trick of difference. Failed zero bid: lose 10 per card dealt.','Apuesta positiva: pierde 10 por cada baza de diferencia. Cero fallido: pierde 10 por carta repartida.')]
    ],
    sections:[
      section('setup',L('Deck, rounds & bids','Mazo, rondas y apuestas'),[
        L('For the basic game, set aside the four blank cards, two Loot cards, Kraken and White Whale. Give out player aids. Shuffle the remaining deck anew each round. Deal one card each in round 1, two in round 2, and so on through round 10. With a large group, once the deck is too small to deal the round number to everyone, repeat the largest equal hand size in the remaining rounds.','En el juego básico, aparta las cuatro cartas en blanco, las dos de Botín, Kraken y Ballena Blanca. Reparte las cartas de ayuda. Mezcla de nuevo todo el mazo en cada ronda. Da una carta a cada persona en la primera ronda, dos en la segunda y así hasta la décima. Si el mazo no alcanza para la ronda correspondiente, repite en las restantes el mayor número de cartas que todos puedan recibir por igual.'),
        L('After studying their hands, everyone chooses a bid from zero to the number of cards dealt. Reveal the bids simultaneously and record them. The dealer’s left neighbor leads the first trick; after the round, the deal moves left.','Tras mirar la mano, cada persona elige una apuesta entre cero y el número de cartas repartidas. Muéstrenlas simultáneamente y anótenlas. Quien está a la izquierda del repartidor inicia la primera baza; después de la ronda, el reparto pasa a la izquierda.')
      ]),
      section('tricks',L('Following suit & winning a trick','Seguir palo y ganar una baza'),[
        L('The leader plays a card face up. Everyone else plays one clockwise. If the lead establishes a numbered suit, play a card of that suit when you have one; any special card may be played instead. Without that suit, play any card. An off-suit numbered card cannot beat a led-suit card, but black numbered cards are trump.','Quien sale juega una carta boca arriba y los demás juegan una en sentido horario. Si la salida fija un palo numérico, juega ese palo cuando lo tengas; puedes jugar cualquier carta especial en su lugar. Si no tienes el palo, juega cualquiera. Una carta numerada de otro palo no vence a una del palo de salida, pero las numeradas negras son triunfo.'),
        L('The highest-ranking card wins the trick. The winner collects it and leads the next. If Escape, Tigress as Escape or Loot leads, the next suitable card determines the led suit. If a character leads, no numbered suit is set. If only Escape-like cards appear, the first played wins.','La carta de mayor jerarquía gana la baza. Quien gana la recoge y sale en la siguiente. Si sale Escape, Tigresa como Escape o Botín, la siguiente carta adecuada determina el palo. Si sale un personaje, no se fija palo numérico. Si solo hay cartas que se comportan como Escape, gana la primera jugada.')
      ]),
      section('hierarchy',L('Card hierarchy & character exceptions','Jerarquía de cartas y excepciones'),[
        L('Among numbered cards: the highest card of the led suit wins unless a black trump is played; then the highest black card wins. A Pirate beats all numbered cards. A Mermaid beats numbered cards but normally loses to a Pirate. The Skull King beats Pirates but loses to a Mermaid. If Pirate, Mermaid and Skull King all appear in one trick, Mermaid wins regardless of play order. Equal Pirates or Mermaids are won by the first played.','Entre cartas numeradas, gana la más alta del palo de salida, salvo que aparezca un triunfo negro; entonces gana el negro más alto. Un Pirata vence a todas las numeradas. Una Sirena vence a las numeradas, pero normalmente pierde ante un Pirata. Skull King vence a los Piratas, pero pierde ante una Sirena. Si coinciden Pirata, Sirena y Skull King, gana la Sirena sin importar el orden. Entre Piratas o Sirenas iguales gana el primero jugado.'),
        L('Tigress is declared as either Pirate or Escape when played and then follows that choice. Ordinary Escape loses to every ranked card. If you use the optional named-pirate powers printed in the base rules, a Pirate must win the trick to activate their power, immediately after that trick; Harry the Giant may also adjust his bid after the final trick.','Al jugar la Tigresa, declara si actúa como Pirata o como Escape y aplica esa elección. Escape normal pierde ante toda carta con jerarquía. Si usan los poderes opcionales de piratas con nombre del reglamento base, el Pirata debe ganar la baza para activarlos inmediatamente; Harry el Gigante también puede ajustar su apuesta después de la última baza.')
      ]),
      section('scoring',L('Classic scoring & capture bonuses','Puntuación clásica y bonificaciones'),[
        L('With Skull King’s classic scoring, an exact positive bid scores 20 points per trick won. A positive bid missed by any amount scores −10 per trick of difference, with no points for tricks taken. An exact zero bid scores 10 times the number of cards dealt; a failed zero bid scores −10 times that number. Highest cumulative total after round 10 wins.','Con la puntuación clásica de Skull King, una apuesta positiva exacta da 20 puntos por baza ganada. Una apuesta positiva fallida resta 10 por cada baza de diferencia, sin sumar las bazas ganadas. Acertar cero da 10 por la cantidad de cartas repartidas; fallar cero resta 10 por esa cantidad. Gana la mayor suma tras la ronda 10.'),
        L('Only when your bid is exact, add bonuses for cards in tricks you captured: each standard 14 of yellow, purple or green +10; black 14 +20; each Mermaid captured by a Pirate +20; each Pirate captured by Skull King +30; Skull King captured by a Mermaid +40. The 14 bonus applies whether you or an opponent played it. In the Pirate–Mermaid–Skull King exception, only the Mermaid’s capture bonus applies.','Solo si acertaste la apuesta, suma bonificaciones por cartas en tus bazas: cada 14 normal amarillo, violeta o verde +10; 14 negro +20; cada Sirena capturada por un Pirata +20; cada Pirata capturado por Skull King +30; Skull King capturado por una Sirena +40. El 14 suma aunque lo haya jugado un rival. En la excepción Pirata–Sirena–Skull King, solo corresponde la bonificación de la Sirena.')
      ]),
      section('rascal-scoring',L('Optional Rascal scoring','Puntuación opcional Rascal'),[
        L('Rascal scoring is an alternative to the classic system, chosen before the game. The potential round score is 10 points per card dealt, whatever your bid. An exact bid earns all of it; missing by one earns half; missing by two or more earns zero. Apply the same full/half/zero scale to base-game capture bonuses; Loot and Expansion Pack bonuses still require an exact bid.','La puntuación Rascal es una alternativa al sistema clásico que se elige antes de jugar. El puntaje potencial de la ronda es 10 por carta repartida, sin importar la apuesta. Acertar da el total; errar por una baza da la mitad; errar por dos o más da cero. Aplica la misma escala de total/mitad/cero a las bonificaciones por capturas del juego base; Botín y las bonificaciones del paquete de expansión siguen exigiendo una apuesta exacta.'),
        L('Optional Cannonball wager with Rascal scoring: after bidding, each player secretly chooses Grapeshot or Cannonball and reveals together. Grapeshot uses the normal Rascal scale. Cannonball gives 15 points per dealt card only for an exact bid, and zero otherwise; bonuses also require an exact bid.','Apuesta opcional Bala de cañón con puntuación Rascal: después de apostar, cada persona elige en secreto Metralla o Bala de cañón y todos revelan a la vez. Metralla usa la escala Rascal normal. Bala de cañón da 15 por carta repartida solo si la apuesta es exacta, o cero en caso contrario; las bonificaciones también exigen acierto exacto.')
      ]),
      section('base-options',L('Optional cards in the base box','Cartas opcionales de la caja base'),[
        L('The current base box also contains two Loot cards, Kraken and White Whale. They are advanced options, separate from the add-on Expansion Pack. Loot plays like Escape; its player and the trick winner each get +20 only if both bid exactly. If Loot itself wins an all-Escape trick, no alliance forms.','La caja base actual también trae dos cartas de Botín, Kraken y Ballena Blanca. Son opciones avanzadas distintas del paquete de expansión adicional. Botín actúa como Escape; quien lo juega y quien gana la baza reciben +20 cada uno solo si ambos acertaron la apuesta. Si el propio Botín gana una baza de solo Escapes, no se forma alianza.'),
        L('Kraken destroys the trick: nobody wins it. The player who would have won without Kraken leads next. White Whale removes character powers and compares numbered cards by number alone, regardless of suit; highest wins, with the first played breaking a tie. If only special cards were played, discard the trick and the Whale player leads. When both sea monsters occur, the one played later controls the effect.','Kraken destruye la baza: nadie la gana. Sale después quien habría ganado sin Kraken. Ballena Blanca anula los personajes y compara las cartas numeradas solo por número, sin importar el palo; gana la más alta y, en empate, la primera. Si solo se jugaron cartas especiales, se descarta la baza y sale quien jugó Ballena Blanca. Si aparecen ambos monstruos, manda el efecto del último que se jugó.')
      ]),
      section('pirate-powers',L('Optional named-pirate powers','Poderes opcionales de piratas con nombre'),[
        L('To use a named Pirate’s power, win a trick with that Pirate. Use the power immediately after that trick; Harry the Giant is the only one whose power may be used after the last trick of the round. Rosie D’ Laney chooses anyone, including herself, to lead the next trick. Bendt the Bandit draws two cards from the deck, then discards two.','Para usar el poder de un Pirata con nombre, gana una baza con él. Aplica el poder inmediatamente después de esa baza; Harry el Gigante es el único que puede usarse después de la última baza de la ronda. Rosie D’ Laney elige a cualquiera, incluida ella misma, para iniciar la siguiente baza. Bendt el Bandido roba dos cartas del mazo y luego descarta dos.'),
        L('Rascal of Roatan wagers 0, 10 or 20 points: gain that amount for an exact bid, lose it otherwise. Juanita Jade privately looks at all undealt cards from the current round. Harry the Giant may raise or lower his bid by one, or leave it unchanged.','Rascal de Roatán apuesta 0, 10 o 20 puntos: gana esa cantidad si acierta la apuesta y la pierde si falla. Juanita Jade mira en privado todas las cartas que no se repartieron en la ronda actual. Harry el Gigante puede aumentar o disminuir su apuesta en uno, o dejarla igual.')
      ]),
      section('two-player',L('Two-player game with Graybeard','Partida de dos con Barbagrís'),[
        L('Deal a third hand for Graybeard, who has no bid or score. The two players alternate who leads at the start of each round. Graybeard normally plays second by revealing the top of his hand, without following suit. If he wins a trick, he leads the next by revealing a card. Tigress in his hand acts as Escape.','Reparte una tercera mano para Barbagrís, que no apuesta ni puntúa. Las dos personas alternan quién inicia cada ronda. Barbagrís normalmente juega segundo revelando la primera carta de su mano, sin obligación de seguir palo. Si gana una baza, sale en la siguiente revelando una carta. Su Tigresa actúa como Escape.')
      ])
    ],
    expansionBasics:[L('Expansion Pack on: add the extra 7s, 8s, 0/14s, Wild 15 and Mary Thorne. Add any or all of the other expansion cards you want. For two players, omit 0/14s, Wild 15 and Walk the Plank.','Paquete de expansión activado: agrega los 7, 8 y 0/14 adicionales, el 15 comodín y Mary Thorne. Agrega las demás cartas de expansión que quieras. Con dos personas, excluye 0/14, 15 comodín y Caminar por la tabla.')],
    expansionLessonTitles:[L('Add the expansion cards','Agrega las cartas de expansión')],
    expansionQuick:[
      [L('New suited cards','Cartas de palo nuevas'),'7 · 8 · 0/14 · 15',L('Declare each 0/14 when played. Wild 15 follows or chooses yellow, purple or green, never black.','Declara cada 0/14 al jugarlo. El 15 comodín sigue o elige amarillo, violeta o verde; nunca negro.')],
      [L('New characters','Personajes nuevos'),'Mary · Con',L('Mary can force a random next card when she wins. First Mate Con beats Pirates and may use powers of Pirates he captures.','Mary puede obligar a jugar una carta al azar en la baza siguiente. Primer Oficial Con vence a los Piratas y puede usar poderes de los que capture.')],
      [L('New disruptions','Nuevas interrupciones'),'4 cards',L('Walk the Plank removes a Pirate; Stingray favors the lowest card; Last Volley adds a late card; Davy Jones removes sea monsters.','Caminar por la tabla elimina un Pirata; Mantarraya favorece la carta menor; Última salva agrega una carta tardía; Davy Jones elimina monstruos marinos.')],
      [L('Expansion bonuses','Bonificaciones de expansión'),'+5 / −5',L('With an exact bid, captured expansion 8s add 5 and 7s subtract 5. Capturing Con or sea monsters can add more.','Con una apuesta exacta, cada 8 de expansión capturado suma 5 y cada 7 resta 5. Capturar a Con o monstruos marinos puede sumar más.')]
    ],
    expansionSections:[
      section('expansion-setup',L('Expansion Pack setup & player counts','Preparación y cantidad de jugadores con expansión'),[
        L('Add one extra 7, 8 and 0/14 of each of the four suits, Wild 15 and Mary Thorne. Then include any or all of First Mate Con, Walk the Plank, Spotted Stingray, Last Volley and Davy Jones’ Locker. Expansion cards have a compass mark. With every expansion card included, nine players can complete all ten rounds; above nine, repeat the largest equal deal size as needed. With two players, leave out all 0/14s, Wild 15 and Walk the Plank.','Agrega un 7, un 8 y un 0/14 extra de cada uno de los cuatro palos, el 15 comodín y Mary Thorne. Después incluye los que quieras de Primer Oficial Con, Caminar por la tabla, Mantarraya moteada, Última salva y Cofre de Davy Jones. Las cartas de expansión llevan una brújula. Con todas incluidas, nueve personas pueden completar diez rondas; con más, repite el mayor reparto igual posible. Con dos personas, excluye todos los 0/14, el 15 comodín y Caminar por la tabla.')
      ]),
      section('expansion-suits',L('Expansion 7s, 8s, 0/14s & Wild 15','7, 8, 0/14 y 15 comodín de la expansión'),[
        L('The added 7s and 8s follow normal suited rules. If tied for highest, the first played wins. Capturing an expansion 8 adds +5, while an expansion 7 adds −5, only when the winner’s bid is exact. When playing a 0/14, immediately declare which value it has; it gives no normal 14 capture bonus. The 0/14 cards are excluded at two players.','Los 7 y 8 añadidos siguen las reglas normales de palo. Si empatan como cartas más altas, gana la primera. Capturar un 8 de expansión suma +5 y capturar un 7 de expansión resta −5, solo si quien ganó acertó su apuesta. Al jugar un 0/14, declara enseguida qué valor tiene; no da la bonificación normal por capturar un 14. Los 0/14 se excluyen con dos personas.'),
        L('Wild Monkey 15 is a numbered card that represents yellow, purple or green, never black trump. If one of those suits was led, it follows that suit as 15; otherwise its player chooses one of them. Against a black lead it loses to trump. Under White Whale, its 15 is the highest number. Do not use Wild 15 at two players.','El 15 comodín es una carta numerada que representa amarillo, violeta o verde, nunca el triunfo negro. Si ya salió uno de esos palos, sigue ese palo con valor 15; si no, quien lo juega elige uno. Ante una salida negra pierde contra el triunfo. Con Ballena Blanca, su 15 es el número más alto. No uses el 15 comodín con dos personas.')
      ]),
      section('expansion-pirates',L('Mary Thorne & First Mate Con','Mary Thorne y Primer Oficial Con'),[
        L('Mary Thorne follows normal Pirate ranking: she beats Mermaids and loses to Skull King. If she wins a trick and her optional pirate power is used, choose a random card without looking from any player’s hand, including your own. That player must play it in the next trick, even if it breaks follow-suit or another card effect.','Mary Thorne tiene la jerarquía normal de Pirata: vence a Sirenas y pierde ante Skull King. Si gana una baza y se usa su poder opcional, elige sin mirar una carta al azar de la mano de cualquier persona, incluso la propia. Esa persona debe jugarla en la siguiente baza, aunque contradiga la obligación de seguir palo u otro efecto.'),
        L('First Mate Con beats other Pirates but loses to both Mermaids and Skull King. If Con wins, his player may use all powers of Pirates he captured in that trick. Con earns no bonus for capturing Pirates. A Mermaid or Skull King that captures Con gains +30, provided its player made an exact bid.','Primer Oficial Con vence a los demás Piratas, pero pierde ante Sirenas y Skull King. Si Con gana, quien lo jugó puede usar todos los poderes de Piratas capturados en esa baza. Con no recibe bonificación por capturar Piratas. Una Sirena o Skull King que capture a Con gana +30 si acertó exactamente su apuesta.')
      ]),
      section('expansion-effects',L('Walk the Plank, Stingray, Last Volley & Davy Jones','Caminar por la tabla, Mantarraya, Última salva y Davy Jones'),[
        L('Walk the Plank cannot win. At the end of the trick its player must remove one standard Pirate if present, choosing which if there are several. A removed Pirate cannot give the Skull King a capture bonus. Do not use this card at two players. Spotted Stingray changes the trick so the lowest card wins, with the first played winning a lowest-card tie. If multiple sea monsters occur, the last one played controls the effect.','Caminar por la tabla no puede ganar. Al final de la baza, quien la jugó debe retirar un Pirata normal si hay alguno, eligiendo cuál si hay varios. Un Pirata retirado no da bonificación a Skull King. No uses esta carta con dos personas. Mantarraya moteada hace ganar a la carta de menor jerarquía; ante empate en la menor, gana la primera. Si aparecen varios monstruos marinos, se aplica el efecto del último jugado.'),
        L('Last Volley cannot win. After everyone else plays, its player plays one extra card; that player skips the final trick of the round unless Last Volley itself was used on the final trick. Davy Jones’ Locker cannot win: at the end of the trick it removes all sea monsters, regardless of order; the highest remaining card wins. Whoever played Davy Jones earns +20 per sea monster it removed if their bid is exact.','Última salva no puede ganar. Después de que jueguen los demás, su dueño juega una carta adicional; luego se salta la última baza de la ronda, salvo que haya usado Última salva precisamente en la última baza. Cofre de Davy Jones no puede ganar: al final retira todos los monstruos marinos, sin importar el orden, y gana la carta restante de mayor jerarquía. Quien jugó Davy Jones suma +20 por cada monstruo retirado si acertó su apuesta.')
      ]),
      section('expansion-exceptions',L('Expansion timing & unusual tricks','Orden de efectos y bazas inusuales'),[
        L('Walk the Plank, Stingray, Last Volley and Davy Jones do not count as ordinary Escape cards and cannot win by themselves. If the other cards are all Escapes, the first Escape wins. If a trick contains only non-winning special cards and no ranked card, discard it; the original leader leads again. When one of these non-winning cards leads, the choice of led suit passes to the next player.','Caminar por la tabla, Mantarraya, Última salva y Davy Jones no son cartas Escape normales y no ganan por sí solas. Si las demás cartas son solo Escapes, gana el primer Escape. Si una baza contiene únicamente cartas especiales que no pueden ganar y ninguna carta con jerarquía, descártala; sale otra vez quien la inició. Si una de esas cartas sin posibilidad de ganar sale primero, la elección del palo pasa a la siguiente persona.'),
        L('A Mermaid wins a trick containing a Pirate, First Mate Con and a Mermaid, regardless of their play order. Expansion bonuses and penalties, like base capture bonuses, apply only when the relevant player gets their bid exactly right.','Una Sirena gana la baza si coinciden Pirata, Primer Oficial Con y Sirena, sin importar el orden. Las bonificaciones y penalizaciones de expansión, como las capturas base, solo se aplican cuando la persona correspondiente acierta exactamente su apuesta.')
      ])
    ],
    sources:[[L('Skull King · official rules and FAQ','Skull King · reglas y preguntas oficiales'),'https://www.grandpabecksgames.com/pages/skull-king'],[L('Skull King · base rulebook','Skull King · reglamento base'),'https://circlejgames.com/wp-content/uploads/2023/10/sk_rulebook_optimized.pdf'],[L('Skull King Expansion · official rulebook','Expansión de Skull King · reglamento oficial'),'https://cdn.shopify.com/s/files/1/0565/3230/4053/files/Skull_King_Expansion_Rulebook_Web.pdf?v=1753214318']]
  },
  sushi_go: {
    name:L('Sushi Go!','Sushi Go!'), subtitle:L('Pick a card, pass the hand, build a feast.','Elige una carta, pasa la mano y arma un festín.'),
    category:L('Card drafting & sets','Elección de cartas y conjuntos'), players:'2–5', time:'15', icon:'sparkle', color:'yellow',
    edition:L('Original 108-card game','Juego original de 108 cartas'), caption:L('A tiny sushi bar in three rounds','Un pequeño sushi bar en tres rondas'),
    description:L('Draft matching dishes, save pudding and score after three rounds.','Elige platos que combinen, guarda budines y puntúa tras tres rondas.'),
    goal:L('Score the most points over three rounds by choosing one card at a time from passing hands.','Consigue más puntos que los demás en tres rondas eligiendo una carta por vez de manos que van pasando.'),
    basics:[
      L('Shuffle all 108 cards. Deal 10 each for 2 players, 9 for 3, 8 for 4 or 7 for 5. Keep your hand secret.','Mezcla las 108 cartas. Reparte 10 por persona si son 2, 9 si son 3, 8 si son 4 o 7 si son 5. Mantén tu mano en secreto.'),
      L('Everyone chooses one card face down, then reveals together. Pass the remaining hand left. Keep choosing until the hands run out; the final passed card is played face up.','Todos eligen una carta boca abajo y luego la revelan a la vez. Pasan la mano restante a la izquierda. Sigan hasta agotar las manos; la última carta recibida se juega boca arriba.'),
      L('Score maki, tempura, sashimi, dumplings and nigiri at round end. Wasabi triples your next nigiri. Chopsticks played earlier let you take two cards on a later turn, then return the chopsticks to the passing hand.','Al acabar la ronda, puntúa maki, tempura, sashimi, dumplings y nigiri. Wasabi triplica tu siguiente nigiri. Los palillos jugados antes te permiten tomar dos cartas en un turno posterior y luego regresan a la mano que pasas.'),
      L('Keep puddings in front of you between rounds; discard the other played cards and deal fresh hands from the remaining deck. Score pudding after round 3.','Conserva los budines entre rondas; descarta las demás cartas jugadas y reparte manos nuevas del mazo restante. Puntúa los budines después de la tercera ronda.')
    ],
    lessonTitles:[L('Deal the cards','Reparte las cartas'),L('Choose and pass','Elige y pasa'),L('Build combinations','Forma combinaciones'),L('Score and reset','Puntúa y reinicia')],
    reminder:L('Sushi Go! and Sushi Go Party! use different tie rules for maki and pudding. This guide follows the original Sushi Go! rulebook: tied players split those points.','Sushi Go! y Sushi Go Party! tienen reglas distintas para los empates de maki y budín. Esta guía sigue el reglamento original de Sushi Go!: quienes empatan dividen esos puntos.'),
    galleryCopy:L('The tin contains 108 cards. The back shows examples of nigiri, tempura and sashimi; the full guide lists every scoring set.','La lata contiene 108 cartas. La parte trasera muestra ejemplos de nigiri, tempura y sashimi; la guía completa enumera todas las puntuaciones.'),
    quick:[
      [L('Choose & pass','Elegir y pasar'),'1 → left',L('Reveal one chosen card simultaneously, then pass the remaining hand left.','Revelen a la vez una carta elegida y pasen la mano restante a la izquierda.')],
      [L('Maki rolls','Rollos maki'),'6 / 3',L('Count icons. Most gets 6, second gets 3; ties split points, rounding down. A tie for first removes second place.','Cuenta los iconos. El mayor recibe 6 y el segundo 3; los empates reparten puntos redondeando hacia abajo. Empatar primero elimina el segundo puesto.')],
      [L('Tempura · Sashimi','Tempura · Sashimi'),'2=5 · 3=10',L('Each pair of tempura scores 5; each trio of sashimi scores 10. Incomplete sets score zero.','Cada pareja de tempura da 5; cada trío de sashimi da 10. Los conjuntos incompletos no puntúan.')],
      [L('Dumplings','Dumplings'),'1 / 3 / 6 / 10 / 15',L('Score 1, 3, 6, 10 or 15 for 1, 2, 3, 4 or at least 5 dumplings.','Suma 1, 3, 6, 10 o 15 por 1, 2, 3, 4 o al menos 5 dumplings.')],
      [L('Nigiri · Wasabi','Nigiri · Wasabi'),'1 / 2 / 3 ×3',L('Egg, salmon and squid nigiri score 1, 2 and 3. Your next nigiri must use an empty wasabi, tripling it.','Nigiri de huevo, salmón y calamar valen 1, 2 y 3. Tu siguiente nigiri debe usar un wasabi libre y triplica su valor.')],
      [L('Pudding','Budín'),'+6 / −6',L('Keep across rounds. After round 3, most gets +6 and fewest −6; tied players split. No negative score at two players.','Guárdalos entre rondas. Tras la tercera, quien tenga más suma 6 y quien tenga menos pierde 6; los empates reparten. Con dos personas no hay penalización.')]
    ],
    sections:[
      section('setup',L('Setup, deals & three rounds','Preparación, reparto y tres rondas'),[
        L('Shuffle the 108-card deck. Deal 10 cards each at two players, 9 at three, 8 at four or 7 at five. Place the rest face down. Keep hands secret and choose a scorekeeper. Play three rounds.','Mezcla el mazo de 108 cartas. Reparte 10 por persona si son dos, 9 si son tres, 8 si son cuatro o 7 si son cinco. Deja el resto boca abajo. Mantengan las manos ocultas y elijan quién anotará puntos. Jueguen tres rondas.'),
        L('At the end of each round, record scores. Keep pudding cards face up in front of their owners. Discard other played cards face up beside the draw pile; deal fresh hands from the remaining draw pile for the next round.','Al final de cada ronda, anoten los puntos. Mantengan los budines boca arriba frente a sus dueños. Descartan las demás cartas jugadas junto al mazo y repartan manos nuevas de las cartas restantes para la ronda siguiente.')
      ]),
      section('draft',L('Choosing, revealing & passing','Elegir, revelar y pasar'),[
        L('Each player secretly chooses one card from their hand and places it face down. Reveal simultaneously. Then pass all remaining cards to the player on the left and pick up the hand arriving from the right. Continue until each hand has only one card; pass that last card and place it face up. Cards collected stay face up until scoring.','Cada persona elige en secreto una carta de su mano y la pone boca abajo. La revelan simultáneamente. Luego pasan las restantes a la izquierda y reciben la mano de la derecha. Continúen hasta que quede una carta por mano; pasen esa última y colóquenla boca arriba. Las cartas elegidas quedan visibles hasta puntuar.'),
        L('Wasabi placed in front of you waits for the next nigiri you play. That nigiri must go on an empty wasabi and is worth triple; each wasabi holds only one nigiri. An empty wasabi scores zero.','Un wasabi jugado frente a ti espera al próximo nigiri que juegues. Ese nigiri debe colocarse sobre un wasabi libre y vale el triple; cada wasabi sostiene solo uno. Un wasabi vacío vale cero.')
      ]),
      section('chopsticks',L('Using chopsticks','Usar los palillos'),[
        L('Chopsticks score zero. On a later turn after playing one, choose a card normally, say “Sushi Go!” before the simultaneous reveal, and choose a second card from that same hand. Reveal both, then put one chopsticks card back into the hand you pass. You can hold several chopsticks but use only one per turn.','Los palillos valen cero. En un turno posterior al que los jugaste, elige una carta normalmente, di «Sushi Go!» antes de revelar y elige una segunda de la misma mano. Revela ambas y luego devuelve una carta de palillos a la mano que pasas. Puedes tener varios palillos, pero usar solo uno por turno.')
      ]),
      section('round-scoring',L('Scoring every dish in a round','Puntuación de cada plato en una ronda'),[
        L('Maki: count the roll icons, not the cards. Most icons earns 6 and second most earns 3. If players tie for first, split the 6 equally, drop any remainder, and award no second place. A second-place tie splits the 3 equally. Tempura scores 5 per pair; sashimi scores 10 per trio; incomplete sets score zero.','Maki: cuenta los iconos de rollo, no las cartas. La mayor cantidad recibe 6 y la segunda 3. Si hay empate en primer lugar, repartan los 6 por igual, descarten el resto y no den segundo puesto. Un empate en segundo reparte los 3. Tempura da 5 por pareja; sashimi da 10 por trío; los conjuntos incompletos valen cero.'),
        L('Dumplings score 1/3/6/10/15 for 1/2/3/4/5 or more cards. Nigiri scores 1 for egg, 2 for salmon and 3 for squid. A nigiri on wasabi scores triple: 3, 6 or 9. Multiple complete sets of tempura or sashimi each score. Chopsticks and unused wasabi score zero.','Los dumplings valen 1/3/6/10/15 por 1/2/3/4/5 o más cartas. Nigiri vale 1 por huevo, 2 por salmón y 3 por calamar. Sobre wasabi valen el triple: 3, 6 o 9. Cada conjunto completo de tempura o sashimi puntúa. Los palillos y wasabi sin usar valen cero.')
      ]),
      section('dessert',L('Pudding, winner & optional variants','Budín, ganador y variantes opcionales'),[
        L('After round 3, whoever has the most pudding cards receives 6 points and whoever has the fewest, including zero, loses 6. Tied players split the positive or negative points equally, dropping the remainder. If everyone ties, nobody scores pudding. In a two-player game, skip the negative pudding points. Most total points wins; a tied total is broken by more pudding cards.','Tras la tercera ronda, quien tenga más budines recibe 6 puntos y quien tenga menos, incluso cero, pierde 6. Quienes empaten reparten por igual los puntos positivos o negativos, descartando el resto. Si todos empatan, nadie puntúa por budín. Con dos personas no hay puntos negativos por budín. Gana el mayor total; un empate se resuelve a favor de quien tenga más budines.'),
        L('Optional passing variant: pass left in rounds 1 and 3, right in round 2. For the optional two-player dummy variant, deal three hands of nine and put the dummy hand face down between the players. Alternate who controls it. The controller draws its top card into their own hand, then chooses one card for themself and one for the dummy; the opponent chooses one normally. Reveal, switch player hands and pass control of the dummy. Continue for three rounds with normal scoring.','Variante opcional de pase: pasen a la izquierda en las rondas 1 y 3, a la derecha en la 2. En la variante opcional de dos personas con mano ficticia, reparte tres manos de nueve y deja la ficticia boca abajo entre ambos. Alternen quién la controla. Quien la controla toma la carta superior en su mano y elige una para sí y otra para la mano ficticia; su rival elige una normalmente. Revelen, intercambien las manos de los jugadores y cedan el control de la ficticia. Jueguen tres rondas y puntúen normalmente.')
      ])
    ],
    sources:[[L('Sushi Go! · official Gamewright rules','Sushi Go! · reglamento oficial de Gamewright'),'https://gamewright.com/pdfs/Rules/SushiGoTM-RULES.pdf'],[L('Sushi Go! · publisher page','Sushi Go! · página de la editorial'),'https://gamewright.com/product/Sushi-Go']]
  },
  sushi_go_party: {
    name:L('Sushi Go Party!','Sushi Go Party!'), subtitle:L('Build the menu before you pass the sushi.','Arma el menú antes de pasar el sushi.'),
    category:L('Card drafting & custom menus','Elección de cartas y menús'), players:'2–8', time:'30', icon:'sparkle', color:'peach',
    edition:L('Deluxe game · 181 cards','Juego deluxe · 181 cartas'), caption:L('A whole banquet of pick-and-pass choices','Un banquete entero de opciones para elegir y pasar'),
    description:L('Choose a menu, draft dishes and score new combinations with up to eight players.','Elige un menú, combina platos nuevos y juega con hasta ocho personas.'),
    goal:L('Earn the most points over three rounds by drafting from a menu chosen before the game.','Obtén más puntos en tres rondas eligiendo cartas de un menú acordado antes de empezar.'),
    basics:[
      L('Choose a published menu or build one: Nigiri, one roll type, three appetizers, two specials and one dessert. Put the matching tiles on the board and set pawns near zero.','Elijan un menú publicado o armen uno: nigiri, un tipo de rollo, tres aperitivos, dos especiales y un postre. Coloquen las fichas correspondientes en el tablero y los peones cerca de cero.'),
      L('Keep dessert cards in a separate pile. Add dessert cards to the main deck each round: 5/3/2 for 2–5 players or 7/5/3 for 6–8. Deal 10 cards each at 2–3 players, 9 at 4–5, 8 at 6–7 or 7 at 8.','Mantén los postres en una pila aparte. Agrega cartas de postre al mazo principal en cada ronda: 5/3/2 si juegan 2–5 o 7/5/3 si juegan 6–8. Reparte 10 por persona si son 2–3, 9 si son 4–5, 8 si son 6–7 o 7 si son 8.'),
      L('Everyone secretly chooses one card and reveals together. Resolve immediate effects, then pass the remaining hand left. Chopsticks and Spoon can be used from a later turn after revealing.','Todos eligen una carta en secreto y la revelan a la vez. Resuelvan los efectos inmediatos y luego pasen la mano restante a la izquierda. Los Palillos y la Cuchara se pueden usar desde un turno posterior después de revelar.'),
      L('After each round, set aside desserts for end-game scoring, score all other cards and reshuffle them for the next round. Add the next batch of desserts. After three rounds, score all desserts and compare totals.','Después de cada ronda, aparta los postres para puntuarlos al final, puntúa las demás cartas y vuelve a mezclarlas para la ronda siguiente. Agrega el siguiente grupo de postres. Tras tres rondas, puntúa todos los postres y compara los totales.')
    ],
    lessonTitles:[L('Choose the menu','Elige el menú'),L('Prepare dessert and deal','Prepara el postre y reparte'),L('Choose, reveal and pass','Elige, revela y pasa'),L('Score the feast','Puntúa el festín')],
    reminder:L('Party rules differ from original Sushi Go!: maki and pudding ties award the full amount to every tied player. Check the menu tiles because only selected dishes are in play.','Las reglas Party difieren de Sushi Go! original: en empates de maki y budín, cada persona empatada recibe la cantidad completa. Consulta las fichas del menú porque solo participan los platos elegidos.'),
    galleryCopy:L('The deluxe tin includes a board, menu tiles and pawns. Its back illustrates several dishes and the menu board; each game uses only its selected menu.','La lata deluxe incluye tablero, fichas de menú y peones. La parte trasera muestra varios platos y el tablero; cada partida usa solo el menú elegido.'),
    quick:[
      [L('Build a menu','Armar un menú'),'1+1+3+2+1',L('Use Nigiri, one roll, three appetizers, two specials and one dessert. Put their tiles on the board.','Usa nigiri, un rollo, tres aperitivos, dos especiales y un postre. Pon sus fichas en el tablero.')],
      [L('Deal cards','Repartir'),'10 / 9 / 8 / 7',L('For 2–3 / 4–5 / 6–7 / 8 players. Add the prescribed dessert cards before each round.','Para 2–3 / 4–5 / 6–7 / 8 personas. Agrega las cartas de postre indicadas antes de cada ronda.')],
      [L('Choose & pass','Elegir y pasar'),'1 → left',L('Reveal one card each at once, resolve effects, then pass the hand left.','Revelen una carta cada uno a la vez, resuelvan efectos y pasen la mano a la izquierda.')],
      [L('Maki or Temaki','Maki o Temaki'),'6 / 3 · 4 / −4',L('Maki: most/second 6/3, or 6/4/2 with 6–8 players. Temaki: most +4, fewest −4 except at two players. Ties get full points.','Maki: primero/segundo 6/3, o 6/4/2 con 6–8. Temaki: mayor +4, menor −4 salvo con dos personas. Los empates reciben puntos completos.')],
      [L('Uramaki','Uramaki'),'8 / 5 / 2',L('First, second and third to reach 10 icons score immediately and discard those cards; remaining icons can claim the next place at round end.','Primero, segundo y tercero en llegar a 10 iconos puntúan de inmediato y descartan esas cartas; los iconos restantes pueden ocupar el puesto siguiente al final.')],
      [L('Dessert','Postre'),'round 3',L('Keep all played dessert cards between rounds. Score the chosen dessert only after the third round.','Conserva todos los postres jugados entre rondas. Puntúa el postre elegido solo después de la tercera.')]
    ],
    sections:[
      section('menu',L('Choose the menu & set up the board','Elegir menú y preparar el tablero'),[
        L('Sushi Go Party! uses selected sets rather than all 181 cards at once. Choose a suggested menu or make your own with Nigiri, exactly one of Maki/Temaki/Uramaki, three different appetizers, two different specials and one dessert. Place their menu tiles on the board and each player’s pawn near zero. Use the chosen sets of cards only.','Sushi Go Party! usa conjuntos elegidos, no las 181 cartas a la vez. Elijan un menú sugerido o creen uno con Nigiri, exactamente uno entre Maki/Temaki/Uramaki, tres aperitivos distintos, dos especiales distintos y un postre. Coloquen sus fichas en el tablero y cada peón cerca de cero. Usen solo las cartas de los conjuntos elegidos.'),
        L('Menu and Special Order are unavailable with 7–8 players. Spoon and Edamame are unavailable with two players. Flip the Maki menu tile to its 6–8-player side when appropriate. The published Sushi Go! menu recreates the classic dish selection, but Party scoring and tie rules still apply.','Menú y Pedido especial no están disponibles con 7–8 personas. Cuchara y Edamame no se usan con dos. Da vuelta la ficha de Maki al lado de 6–8 cuando corresponda. El menú publicado Sushi Go! reproduce la selección clásica de platos, pero siguen rigiendo las puntuaciones y empates de Party.')
      ]),
      section('deal',L('Dessert schedule, deals & passing','Calendario de postres, reparto y pases'),[
        L('Shuffle the chosen dessert cards separately. Before rounds 1, 2 and 3, shuffle 5, 3 and 2 dessert cards into the main deck with 2–5 players; use 7, 5 and 3 with 6–8. At 2–5 players, the five unused dessert cards stay out. Deal 10 each for 2–3 players, 9 for 4–5, 8 for 6–7 or 7 for 8. Place the remaining deck beside the board.','Mezcla aparte las cartas del postre elegido. Antes de las rondas 1, 2 y 3, agrega al mazo principal 5, 3 y 2 postres con 2–5 personas; usa 7, 5 y 3 con 6–8. Con 2–5, deja fuera las cinco cartas de postre sobrantes. Reparte 10 por persona si son 2–3, 9 si son 4–5, 8 si son 6–7 o 7 si son 8. Deja el mazo restante junto al tablero.'),
        L('Everyone chooses one card face down and reveals together. Resolve immediate effects, then pass remaining hands face down to the left. Repeat until hands are empty. Put played desserts aside for the end of the game, score everything else, then collect and reshuffle non-dessert cards for the next round.','Todos eligen una carta boca abajo y la revelan a la vez. Resuelvan los efectos inmediatos y pasen las manos restantes boca abajo a la izquierda. Repitan hasta agotar las manos. Aparten los postres jugados hasta el final de la partida, puntúen lo demás y recojan y mezclen de nuevo las cartas que no son postres para la siguiente ronda.')
      ]),
      section('rolls',L('Rolls: Maki, Temaki & Uramaki','Rollos: Maki, Temaki y Uramaki'),[
        L('Maki counts icons. With 2–5 players, most gets 6 and second most 3; with 6–8, first/second/third get 6/4/2. Every tied player receives the full points for that place. A player needs at least one Maki card to score. Temaki awards +4 to the most and −4 to the fewest, including zero; ties get full amounts. There is no Temaki penalty at two players.','Maki cuenta iconos. Con 2–5 personas, el primero recibe 6 y el segundo 3; con 6–8, los puestos primero/segundo/tercero reciben 6/4/2. Cada persona empatada recibe los puntos completos de ese puesto. Hay que tener al menos una carta Maki para puntuar. Temaki da +4 a quien tenga más y −4 a quien tenga menos, incluso cero; los empates reciben cantidades completas. No hay penalización Temaki con dos personas.'),
        L('Uramaki is a race: the first player to collect at least 10 icons scores 8 immediately and discards those Uramaki, then second scores 5 and third 2. When players reach 10 in the same turn, more icons breaks the tie; an exact tie gives each full points and skips the next place. At round end, the most unscored Uramaki icons can claim the next available place. One player may score more than one place in a round.','Uramaki es una carrera: la primera persona en reunir al menos 10 iconos suma 8 de inmediato y descarta esas cartas; la segunda suma 5 y la tercera 2. Si varias llegan a 10 en el mismo turno, más iconos desempatan; un empate exacto da puntos completos a cada una y salta el puesto siguiente. Al final de la ronda, la mayor cantidad de iconos Uramaki sin puntuar puede ocupar el próximo puesto disponible. Una persona puede puntuar más de un puesto en la misma ronda.')
      ]),
      section('appetizers',L('All appetizer scores','Puntuación de todos los aperitivos'),[
        L('Tempura: 5 per pair. Sashimi: 10 per trio. Dumplings: 1/3/6/10/15 for 1/2/3/4/5 or more. Eel: one is −3, two or more is +7. Tofu: one +2, two +6, three or more zero.','Tempura: 5 por pareja. Sashimi: 10 por trío. Dumplings: 1/3/6/10/15 por 1/2/3/4/5 o más. Anguila: una vale −3, dos o más +7. Tofu: uno +2, dos +6, tres o más cero.'),
        L('Onigiri has four shapes. Each set with 1/2/3/4 distinct shapes scores 1/4/9/16; extra copies can make further sets. Edamame scores, for each Edamame card, one point per opponent who has any Edamame, up to four points per card; it scores zero if only one player has any. Use Edamame only with 3–8 players.','Onigiri tiene cuatro formas. Cada conjunto de 1/2/3/4 formas distintas vale 1/4/9/16; las copias extra pueden formar otros conjuntos. Cada carta Edamame da un punto por cada rival con al menos un Edamame, hasta cuatro por carta; vale cero si solo una persona tiene Edamame. Úsalo solo con 3–8 personas.'),
        L('A Miso Soup played alone in its turn stays and scores 3 at round end. If two or more Miso Soups are played in the same turn, discard them all, including any played through bonus actions or Special Order. You may score more than one Miso Soup from separate turns.','Una Sopa miso jugada sola en su turno permanece y da 3 al final de la ronda. Si se juegan dos o más Sopas miso en el mismo turno, descártalas todas, incluidas las jugadas mediante acciones adicionales o Pedido especial. Puedes puntuar varias Sopas miso de turnos distintos.')
      ]),
      section('specials',L('Nigiri & every special card','Nigiri y todas las cartas especiales'),[
        L('Nigiri scores egg 1, salmon 2 and squid 3. The next Nigiri you play must occupy an empty Wasabi you have already played, tripling that Nigiri to 3/6/9. Each Wasabi holds one; an unused Wasabi scores zero.','Nigiri de huevo vale 1, de salmón 2 y de calamar 3. El próximo Nigiri que juegues debe ocupar un Wasabi libre que ya jugaste y triplica su valor a 3/6/9. Cada Wasabi admite uno; sin Nigiri vale cero.'),
        L('Chopsticks and Spoon are played first, then may be used on a later turn after the normal reveal and before hands are passed. Chopsticks let you play a second card from your current hand, then return Chopsticks to that hand. Spoon lets you name a card: the first player to your left holding one gives it to you, plays your Spoon into their hand, and you play the requested card; if nobody has it, discard Spoon. Spoon requires 3–8 players.','Palillos y Cuchara se juegan primero y pueden usarse en un turno posterior, tras revelar normalmente y antes de pasar manos. Palillos te dejan jugar una segunda carta de tu mano actual y luego vuelven a esa mano. Cuchara te permite pedir una carta: la primera persona a tu izquierda que la tenga te la entrega, recibe tu Cuchara en su mano y tú juegas la carta pedida; si nadie la tiene, descarta la Cuchara. Cuchara requiere 3–8 personas.'),
        L('Menu (2–6 players): when played, draw four cards from the unused deck, play one that is not another Menu, return the other three and reshuffle; discard Menu. Special Order (2–6): when played, copy one of your previously played cards by pointing the Order toward it. If none exists, discard the Order. Takeout Box: when played, flip any number of cards played on earlier turns face down; each becomes worth two points at round end, then discard the Box.','Menú (2–6 personas): al jugarlo, toma cuatro cartas del mazo no repartido, juega una que no sea otro Menú, devuelve las otras tres y mezcla; descarta Menú. Pedido especial (2–6): al jugarlo, copia una carta propia de turnos anteriores señalándola con el Pedido. Si no hay ninguna, descártalo. Caja para llevar: al jugarla, da vuelta cualquier número de cartas que jugaste en turnos anteriores; cada una vale dos puntos al final de la ronda. Después descarta la Caja.'),
        L('Soy Sauce gives 4 points per Soy Sauce card if you tie for or have the most different card background colors at round end. Tea scores one point per card in your largest same-color group, for each Tea card. When multiple bonus actions, Menus or Takeout Boxes resolve together, use their small printed numbers in ascending order.','Cada carta de Salsa de soja da 4 puntos si empatas o tienes la mayor variedad de colores de fondo al final de la ronda. Cada Té da un punto por carta del grupo más numeroso de un mismo color. Si se resuelven varias acciones adicionales, Menús o Cajas para llevar, usa sus pequeños números impresos en orden ascendente.')
      ]),
      section('dessert',L('Desserts, final score & ties','Postres, puntuación final y empates'),[
        L('Keep all dessert cards across rounds; score only the selected type after the third round. Green Tea Ice Cream: each set of four cards scores 12, with incomplete sets scoring zero. Fruit: count watermelon, orange and pineapple icons separately; for each type, 0/1/2/3/4/5 or more icons score −2/0/1/3/6/10.','Conserva todos los postres entre rondas; puntúa solo el tipo elegido después de la tercera. Helado de té verde: cada grupo de cuatro cartas da 12, los grupos incompletos cero. Fruta: cuenta por separado sandía, naranja y piña; para cada tipo, 0/1/2/3/4/5 o más iconos valen −2/0/1/3/6/10.'),
        L('Pudding: most cards +6, fewest cards −6, including zero. Every tied player gains or loses the full amount. There is no negative pudding score at two players. Highest total wins; break a tie by the number of dessert cards collected.','Budín: la mayor cantidad +6, la menor −6, incluso cero. Cada persona empatada suma o pierde la cantidad completa. No hay penalización por budín con dos personas. Gana el mayor total; un empate se resuelve por la cantidad de cartas de postre reunidas.')
      ])
    ],
    sources:[[L('Sushi Go Party! · official Gamewright rules','Sushi Go Party! · reglamento oficial de Gamewright'),'https://gamewright.com/pdfs/Rules/SushiGoPartyTM-RULES.pdf'],[L('Sushi Go Party! · publisher page','Sushi Go Party! · página de la editorial'),'https://gamewright.com/product/Sushi-Go-Party']]
  }
});

Object.assign(NEW_GAME_ART, {
  'skull_king-box':{src:'assets/real/skull-king-box.jpg',title:L('Skull King · current box','Skull King · caja actual'),owner:'Grandpa Beck’s Games',url:'https://www.grandpabecksgames.com/products/skull-king%C2%AE',group:'skull_king',width:990,height:990},
  'skull_king-components':{src:'assets/real/skull-king-components.jpg',title:L('Skull King · cards in play','Skull King · cartas en juego'),owner:'Grandpa Beck’s Games',url:'https://www.grandpabecksgames.com/products/skull-king%C2%AE',group:'skull_king',width:990,height:990},
  'skull_king-expansion':{src:'assets/real/skull-king-expansion.jpg',title:L('Skull King · Expansion Pack','Skull King · paquete de expansión'),owner:'Grandpa Beck’s Games',url:'https://www.grandpabecksgames.com/products/skull-king-expansion-pack',group:'skull_king',width:990,height:990},
  'sushi_go-box':{src:'assets/real/sushi-go-box.jpg',title:L('Sushi Go! · original tin','Sushi Go! · lata original'),owner:'Gamewright · Nan Rangsima',url:'https://gamewright.com/product/Sushi-Go',group:'sushi_go',width:714,height:1000},
  'sushi_go-components':{src:'assets/real/sushi-go-back.jpg',title:L('Sushi Go! · tin back and example cards','Sushi Go! · dorso de la lata y cartas de ejemplo'),owner:'Gamewright · Nan Rangsima',url:'https://gamewright.com/product/Sushi-Go',group:'sushi_go',width:715,height:1000},
  'sushi_go_party-box':{src:'assets/real/sushi-go-party-box.jpg',title:L('Sushi Go Party! · deluxe tin','Sushi Go Party! · lata deluxe'),owner:'Gamewright · Nan Rangsima',url:'https://gamewright.com/product/Sushi-Go-Party',group:'sushi_go_party',width:765,height:1000},
  'sushi_go_party-components':{src:'assets/real/sushi-go-party-back.jpg',title:L('Sushi Go Party! · menu board and example cards','Sushi Go Party! · tablero de menú y cartas de ejemplo'),owner:'Gamewright · Nan Rangsima',url:'https://gamewright.com/product/Sushi-Go-Party',group:'sushi_go_party',width:798,height:1000}
});
