/* Additional bilingual game guides. Each entry follows the same data contract as the original collection. */
Object.assign(GAMES, {
  catan: {
    name:L('Catan','Catan'), subtitle:L('Trade wisely. Build the island.','Negocia bien. Construye la isla.'),
    category:L('Trading & strategy','Negociación y estrategia'), players:'3–4', time:'60–90', icon:'grid', color:'peach',
    edition:L('Base game · 3–4 players','Juego base · 3–4 jugadores'), caption:L('An island of roads, resources and deals','Una isla de caminos, recursos y acuerdos'),
    description:L('Collect resources, trade and connect settlements to reach 10 points.','Consigue recursos, negocia y conecta poblados hasta alcanzar 10 puntos.'),
    goal:L('Be the first player to reach 10 victory points on your turn. Settlements, cities, the longest road, the largest army and some development cards provide points.','Sé la primera persona en alcanzar 10 puntos de victoria durante tu turno. Los poblados, ciudades, el camino más largo, el gran ejército y algunas cartas de desarrollo otorgan puntos.'),
    basics:[
      L('Build the island, place number tokens and put the robber on the desert. Each player places two settlements and two roads in snake order; after placing the second settlement, take one resource from every adjacent producing hex.','Arma la isla, coloca las fichas numéricas y deja al ladrón en el desierto. Cada persona coloca dos poblados y dos caminos en orden de ida y vuelta; al colocar el segundo poblado, recibe un recurso por cada terreno productivo adyacente.'),
      L('On your turn, roll both dice. Every hex with that total produces: each adjacent settlement earns one matching resource and each city earns two. A 7 activates the robber instead.','En tu turno, tira los dos dados. Cada terreno con ese total produce: cada poblado adyacente recibe un recurso correspondiente y cada ciudad recibe dos. Un 7 activa al ladrón.'),
      L('Trade resource cards with other players on your turn, or with the bank at 4:1. Harbors improve the bank rate. Then spend resources to build roads, settlements, cities or development cards.','Negocia cartas de recurso con los demás durante tu turno o cambia con el banco a razón de 4:1. Los puertos mejoran esa tasa. Luego gasta recursos para construir caminos, poblados, ciudades o cartas de desarrollo.'),
      L('Announce the win as soon as your visible and hidden points total 10 during your own turn. Only your own turn can produce the victory.','Anuncia la victoria en cuanto tus puntos visibles y ocultos sumen 10 durante tu propio turno. Solo puedes ganar en tu turno.')
    ],
    lessonTitles:[L('Settle the island','Coloniza la isla'),L('Roll for resources','Produce recursos'),L('Trade and build','Negocia y construye'),L('Reach 10 points','Llega a 10 puntos')],
    reminder:L('Settlements must be at least two edges apart. You may build only along your connected roads, and you cannot trade development cards.','Los poblados deben quedar separados por al menos dos aristas. Solo puedes construir sobre tu red conectada y no se pueden intercambiar cartas de desarrollo.'),
    galleryCopy:L('The hexes produce five resources. Roads connect your buildings; number tokens determine which terrain produces after each roll.','Los hexágonos producen cinco recursos. Los caminos conectan tus construcciones y las fichas numéricas determinan qué terreno produce tras cada tirada.'),
    quick:[
      [L('Roll','Tirar'),'2d6',L('Resolve production, or move the robber on a 7.','Resuelve la producción o mueve al ladrón con un 7.')],
      [L('Trade','Negociar'),'4:1+',L('Trade with players, the bank or a harbor. Only the active player may make player trades.','Intercambia con jugadores, banco o puerto. Solo quien tiene el turno negocia con otros.')],
      [L('Build','Construir'),'1–4',L('Road: brick+lumber. Settlement: brick+lumber+wool+grain. City: 3 ore+2 grain. Development: ore+wool+grain.','Camino: arcilla+madera. Poblado: arcilla+madera+lana+cereal. Ciudad: 3 minerales+2 cereales. Desarrollo: mineral+lana+cereal.')],
      [L('Robber','Ladrón'),'7',L('Players with more than 7 resource cards discard half, rounded down. Move the robber and steal one random card from an adjacent opponent.','Quien tenga más de 7 recursos descarta la mitad, redondeando hacia abajo. Mueve al ladrón y roba una carta al azar a un rival adyacente.')]
    ],
    sections:[
      section('setup',L('Setup & first settlements','Preparación y poblados iniciales'),[
        L('Use the beginner layout or randomize the 19 terrain hexes, surround them with the sea frame and place number tokens. Sort resource and development cards; place Longest Road and Largest Army nearby. Put the robber on the desert.','Usa el mapa inicial o mezcla los 19 terrenos, rodéalos con el marco de mar y coloca los números. Separa recursos y desarrollo; deja a mano Camino más largo y Gran ejército. Pon al ladrón en el desierto.'),
        L('Choose a first player. In clockwise order, each player places one settlement and an adjacent road; then reverse the order for the second settlement and road. Buildings cannot be adjacent: every neighboring intersection must stay empty. Collect starting resources only from the second settlement.','Elijan quién empieza. En sentido horario, cada persona coloca un poblado y un camino adyacente; luego inviertan el orden para el segundo poblado y camino. No puede haber edificios vecinos: cada intersección contigua debe quedar libre. Recibe recursos iniciales solo por el segundo poblado.')
      ]),
      section('turn',L('Turn: produce, trade & build','Turno: producir, negociar y construir'),[
        L('Start by rolling. Give one resource per adjacent settlement and two per adjacent city on every hex showing the result. If the supply lacks enough of one resource for all players, nobody receives that resource; if only one player is owed it, give as much as available.','Comienza tirando. Entrega un recurso por poblado y dos por ciudad adyacente en cada terreno con el resultado. Si no alcanza un tipo de recurso para todos, nadie recibe ese tipo; si solo una persona debe recibirlo, toma lo disponible.'),
        L('After production, trade and build in the order used by your edition. Domestic trades may contain resources only and both sides must agree. Maritime trade is normally 4 identical cards for 1 of your choice; generic harbors give 3:1 and resource harbors give 2:1 for their resource.','Tras producir, negocia y construye en el orden de tu edición. Los intercambios entre jugadores solo incluyen recursos y ambas partes deben aceptar. El comercio marítimo suele ser 4 cartas iguales por 1 cualquiera; los puertos generales dan 3:1 y los específicos 2:1.')
      ]),
      section('building',L('Building, cards & awards','Construcción, cartas y premios'),[
        L('A road connects to your road, settlement or city and cannot pass through an opponent’s building. A settlement costs brick, lumber, wool and grain, follows the distance rule and must connect to your road. Upgrade your own settlement to a city for 3 ore and 2 grain.','Un camino conecta con otro camino o edificio propio y no atraviesa un edificio rival. Un poblado cuesta arcilla, madera, lana y cereal, respeta la distancia y conecta con tu camino. Mejora un poblado propio a ciudad con 3 minerales y 2 cereales.'),
        L('Buy a development card for ore, wool and grain; keep it secret. Except for victory points, play at most one development card per turn and not one bought that same turn. The first player with at least 5 continuous roads claims Longest Road (2 points); the first with 3 played knights claims Largest Army (2 points). A rival must exceed the current length or army size to take an award.','Compra desarrollo por mineral, lana y cereal y mantenlo oculto. Salvo los puntos, juega como máximo una carta de desarrollo por turno y no una comprada ese mismo turno. El primer camino continuo de al menos 5 obtiene Camino más largo (2 puntos); los primeros 3 caballeros jugados obtienen Gran ejército (2 puntos). Para quitar un premio hay que superar su valor actual.')
      ]),
      section('robber',L('Rolling 7, robber & victory','Siete, ladrón y victoria'),[
        L('On a 7, no hex produces. Every player holding more than 7 resource cards discards half, rounded down. Move the robber to another terrain hex and, if possible, steal one random resource from one opponent with a building beside it. That hex produces nothing while blocked.','Con un 7, ningún terreno produce. Quien tenga más de 7 recursos descarta la mitad, redondeando hacia abajo. Mueve al ladrón a otro terreno y, si puedes, roba un recurso al azar a un rival con edificio adyacente. Ese terreno no produce mientras esté bloqueado.'),
        L('Settlements are worth 1 point and cities 2. Awards are worth 2, and victory-point development cards are revealed when they give you the win. You win immediately upon reaching 10 on your own turn, even before rolling if your hidden points already complete the total.','Los poblados valen 1 punto y las ciudades 2. Los premios valen 2 y las cartas de punto se revelan cuando te dan la victoria. Ganas inmediatamente al llegar a 10 en tu turno, incluso antes de tirar si tus puntos ocultos completan el total.')
      ])
    ],
    sources:[[L('CATAN · official rules','CATAN · reglas oficiales'),'https://www.catan.com/understand-catan/game-rules'],[L('CATAN · base game','CATAN · juego base'),'https://www.catan.com/catan']]
  },

  secret_hitler: {
    name:L('Secret Hitler','Secret Hitler'), subtitle:L('Elect a government. Question every vote.','Elige un gobierno. Cuestiona cada voto.'),
    category:L('Social deduction','Deducción social'), players:'5–10', time:'45', icon:'people', color:'lavender',
    edition:L('Base game · 5–10 players','Juego base · 5–10 jugadores'), caption:L('A fragile government of hidden loyalties','Un gobierno frágil de lealtades ocultas'),
    description:L('Pass policies, expose the fascists and keep Hitler from power.','Aprueba políticas, descubre a los fascistas e impide que Hitler llegue al poder.'),
    goal:L('Liberals win by enacting 5 Liberal policies or executing Hitler. Fascists win by enacting 6 Fascist policies, or by electing Hitler Chancellor after 3 Fascist policies are on the board.','Los liberales ganan al aprobar 5 políticas liberales o ejecutar a Hitler. Los fascistas ganan al aprobar 6 políticas fascistas o al elegir a Hitler canciller cuando ya hay 3 políticas fascistas.')
    ,basics:[
      L('Deal one secret role and one matching party membership to each player. Liberals know nobody. Fascists know one another and Hitler, with the special five- and six-player information described in setup.','Reparte un rol secreto y una afiliación correspondiente a cada persona. Los liberales no conocen a nadie. Los fascistas se reconocen y conocen a Hitler, con la información especial para cinco y seis jugadores indicada en la preparación.'),
      L('The President nominates an eligible Chancellor. Everyone votes Ja or Nein at once. A majority of Ja elects the government; a tie fails and advances the election tracker.','El presidente propone a un canciller elegible. Todos votan Ja o Nein a la vez. La mayoría de Ja elige al gobierno; un empate fracasa y avanza el marcador electoral.'),
      L('The President draws three policies, discards one and passes two to the Chancellor. The Chancellor discards one and enacts the other. Players may discuss or lie, but may not show policy cards.','El presidente roba tres políticas, descarta una y pasa dos al canciller. El canciller descarta una y aprueba la restante. Se puede debatir o mentir, pero no mostrar cartas de política.'),
      L('Resolve the power printed under an enacted Fascist policy. Then pass the Presidency clockwise. Always check the instant Hitler election condition after the third Fascist policy.','Resuelve el poder impreso bajo una política fascista aprobada. Luego pasa la presidencia en sentido horario. Tras la tercera política fascista, comprueba siempre la victoria instantánea por elección de Hitler.')
    ],
    lessonTitles:[L('Deal secret loyalties','Reparte lealtades'),L('Elect a government','Elige un gobierno'),L('Pass one policy','Aprueba una política'),L('Watch the victory conditions','Vigila las victorias')],
    reminder:L('After 3 Fascist policies, pause immediately when a government is elected: if the new Chancellor is Hitler, the Fascists win before the legislative session.','Tras 3 políticas fascistas, deténganse al elegir gobierno: si el nuevo canciller es Hitler, los fascistas ganan antes de legislar.'),
    galleryCopy:L('Role envelopes hide loyalty. Ja/Nein ballots elect each government; the policy tracks reveal powers and both teams’ progress.','Los sobres ocultan la lealtad. Las papeletas Ja/Nein eligen cada gobierno y los tableros muestran poderes y progreso.'),
    quick:[
      [L('Nominate','Proponer'),'1',L('President chooses an eligible Chancellor candidate.','El presidente elige un candidato elegible a canciller.')],
      [L('Vote','Votar'),'Ja / Nein',L('Reveal together. More than half Ja elects the government; ties fail.','Revelen a la vez. Más de la mitad en Ja elige el gobierno; empate = fracaso.')],
      [L('Legislate','Legislar'),'3 → 2 → 1',L('President draws 3 and discards 1; Chancellor receives 2, discards 1 and enacts 1.','El presidente roba 3 y descarta 1; el canciller recibe 2, descarta 1 y aprueba 1.')],
      [L('Chaos','Caos'),'3×',L('After three failed elections, enact the top policy automatically and reset term limits.','Tras tres elecciones fallidas, aprueba automáticamente la primera política y reinicia restricciones.')]
    ],
    sections:[
      section('setup',L('Setup, roles & information','Preparación, roles e información'),[
        L('Use these teams: 5 players = 3 Liberals, 1 Fascist, Hitler; 6 = 4, 1, Hitler; 7 = 4, 2, Hitler; 8 = 5, 2, Hitler; 9 = 5, 3, Hitler; 10 = 6, 3, Hitler. Match each role to its party membership, seal pairs in envelopes and deal one per player.','Usa estos equipos: 5 jugadores = 3 liberales, 1 fascista y Hitler; 6 = 4, 1 y Hitler; 7 = 4, 2 y Hitler; 8 = 5, 2 y Hitler; 9 = 5, 3 y Hitler; 10 = 6, 3 y Hitler. Une cada rol con su afiliación, coloca los pares en sobres y reparte uno por persona.'),
        L('At 5–6 players, Hitler and the Fascist recognize each other. At 7–10, the Fascists recognize one another and Hitler, while Hitler keeps eyes closed and does not learn who the Fascists are. Choose the matching Fascist board, shuffle the 6 Liberal and 11 Fascist policies, and pick a first President.','Con 5–6, Hitler y el fascista se reconocen. Con 7–10, los fascistas se reconocen y conocen a Hitler, mientras Hitler mantiene los ojos cerrados y no sabe quiénes son. Usa el tablero fascista correcto, mezcla 6 políticas liberales y 11 fascistas y elige presidente inicial.')
      ]),
      section('election',L('Election & term limits','Elección y restricciones'),[
        L('The President nominates any living eligible player as Chancellor. Normally the last elected President and Chancellor are ineligible for Chancellor; with five living players, only the last Chancellor is ineligible. The outgoing President may still become the next Chancellor when eligible.','El presidente propone como canciller a cualquier persona viva elegible. Normalmente el último presidente y canciller elegidos no pueden ser canciller; con cinco personas vivas, solo queda inhabilitado el último canciller. El presidente saliente puede ser el próximo canciller cuando corresponda.'),
        L('Everyone, including candidates, votes at the same time. A strict majority of Ja elects the government. If it fails, advance the election tracker and pass the Presidency. On the third failure, reveal and enact the top policy without a power; reset the tracker and all term limits.','Todos, incluidos los candidatos, votan a la vez. Una mayoría estricta de Ja elige al gobierno. Si falla, avanza el marcador y pasa la presidencia. Al tercer fracaso, revela y aprueba la primera política sin aplicar poder; reinicia marcador y restricciones.')
      ]),
      section('legislation',L('Legislative session & veto','Sesión legislativa y veto'),[
        L('The President draws the top 3 policy tiles, secretly discards 1 and gives 2 to the Chancellor. The Chancellor secretly discards 1 and enacts the other. Do not communicate during this procedure and never show the choices. Reshuffle the discard pile when fewer than 3 remain.','El presidente roba las 3 primeras políticas, descarta 1 en secreto y pasa 2 al canciller. El canciller descarta 1 en secreto y aprueba la otra. No se comuniquen durante el proceso ni muestren las opciones. Mezcla los descartes cuando queden menos de 3.'),
        L('After 5 Fascist policies, the Chancellor may request a veto. Only if the President agrees are both policies discarded; advance the election tracker as a failed government. If the President refuses, the Chancellor must enact one policy.','Tras 5 políticas fascistas, el canciller puede pedir veto. Solo si el presidente acepta se descartan ambas; avanza el marcador como gobierno fallido. Si el presidente rechaza, el canciller debe aprobar una.')
      ]),
      section('powers',L('Presidential powers & executions','Poderes presidenciales y ejecuciones'),[
        L('When a Fascist policy exposes a power, the President who enacted it must use it before play continues. Depending on player count and position, this may inspect one party membership, call a special election, peek at the next three policies, or execute one player. Follow the printed track; powers do not reveal secret roles.','Cuando una política fascista descubre un poder, el presidente que la aprobó debe usarlo antes de seguir. Según jugadores y casilla, puede examinar una afiliación, convocar elección especial, mirar las tres políticas siguientes o ejecutar a alguien. Sigue el tablero; los poderes no revelan roles secretos.'),
        L('An executed player leaves silently and never speaks, votes or holds office again. If that player is Hitler, Liberals win immediately; otherwise their role remains secret. A special-election President serves once, then the Presidency returns to the player after the President who called it.','Una persona ejecutada sale en silencio y ya no habla, vota ni ocupa cargos. Si era Hitler, los liberales ganan inmediatamente; si no, su rol sigue secreto. El presidente especial actúa una vez y luego la presidencia vuelve a quien seguía al presidente que lo convocó.')
      ]),
      section('victory',L('Victory checks & table conduct','Comprobaciones de victoria y mesa'),[
        L('Five Liberal policies or Hitler’s execution give Liberals an immediate win. Six Fascist policies give Fascists an immediate win. Once 3 Fascist policies are enacted, electing Hitler Chancellor also ends the game immediately, before drawing policies.','Cinco políticas liberales o ejecutar a Hitler dan victoria inmediata a los liberales. Seis fascistas dan victoria inmediata a los fascistas. Con 3 fascistas aprobadas, elegir a Hitler canciller también termina la partida antes de robar políticas.'),
        L('Players may claim anything about hidden information and may keep notes only if the table agrees, but no one may reveal role, membership or policy components. Keep the game fictional and respectful; anyone can stop play if the theme becomes uncomfortable.','Se puede afirmar cualquier cosa sobre información oculta, y tomar notas solo si la mesa lo acuerda, pero nadie puede mostrar componentes secretos. Mantengan el marco ficticio y respetuoso; cualquiera puede detener la partida si el tema resulta incómodo.')
      ])
    ],
    sources:[[L('Secret Hitler · official rules','Secret Hitler · reglas oficiales'),'https://www.secrethitler.com/assets/Secret_Hitler_Rules.pdf'],[L('Secret Hitler · official site','Secret Hitler · sitio oficial'),'https://www.secrethitler.com/']]
  },

  el_camarero: {
    name:L('The Waiter','El Camarero'), subtitle:L('Remember every order. Ring before anyone else.','Recuerda cada pedido. Toca el timbre antes que nadie.'),
    category:L('Memory & party game','Memoria y juego social'), players:'2–10', time:'30–45', icon:'clock', color:'yellow',
    edition:L('Maldón · 2018 edition','Maldón · edición 2018'), caption:L('Orders, trays and a very tempting bell','Pedidos, bandejas y un timbre irresistible'),
    description:L('Memorize the table, serve the right dishes and catch every mistake.','Memoriza la mesa, sirve cada plato y descubre todos los errores.'),
    goal:L('Finish with the highest score by serving correct orders and correctly returning dishes nobody ordered, while avoiding complaint tokens. Order cards score 3, returned food cards score 1 and complaints subtract 2.','Termina con la mayor puntuación sirviendo pedidos correctos y devolviendo platos que nadie pidió, evitando fichas de queja. Las cartas de pedido valen 3, las comidas devueltas 1 y cada queja resta 2.'),
    basics:[
      L('Deal one order card from each category to every player. Each person chooses one of the two variants shown, announces the complete order aloud and leaves the chosen side facing them, face down.','Reparte a cada persona una carta de pedido de cada categoría. Cada una elige una de las dos variantes, anuncia todo su pedido en voz alta y deja la opción elegida orientada hacia sí, boca abajo.'),
      L('Set out 8 face-up food cards as the kitchen. On your turn, either serve one dish to another diner and name its exact variant, or announce that you will return dishes nobody ordered.','Coloca 8 cartas de comida boca arriba como cocina. En tu turno, sirve un plato a otro comensal nombrando la variedad exacta o anuncia que devolverás platos que nadie pidió.'),
      L('If someone sees an error, they must ring the bell first and make the full correction. A correct challenge gives the active waiter a complaint; an incorrect challenge gives the challenger a complaint.','Si alguien detecta un error, debe tocar primero el timbre y hacer la corrección completa. Un reclamo correcto da una queja al camarero activo; uno incorrecto da una queja a quien reclamó.'),
      L('Refill the kitchen after each turn. The game ends when every order is served or the kitchen cannot be refilled. Add 3 per collected order, 1 per returned food card and subtract 2 per complaint.','Repón la cocina tras cada turno. La partida termina cuando se sirven todos los pedidos o no se puede reponer la cocina. Suma 3 por pedido ganado, 1 por comida devuelta y resta 2 por queja.')
    ],
    lessonTitles:[L('Take the orders','Toma los pedidos'),L('Open the kitchen','Abre la cocina'),L('Ring and correct','Toca y corrige'),L('Count the service','Cuenta el servicio')],
    reminder:L('You may inspect your own order only when someone is serving that exact category to you. Looking at any order at another time costs one complaint.','Solo puedes mirar tu pedido cuando te están sirviendo esa categoría. Mirar una comanda en otro momento cuesta una queja.'),
    galleryCopy:L('Order cards show two possible variants. Food cards enter the kitchen face up; the bell makes a correction valid and complaint tokens record mistakes.','Las comandas muestran dos variantes. Las comidas salen a la cocina boca arriba; el timbre valida una corrección y las quejas registran errores.'),
    quick:[
      [L('Serve','Servir'),'1',L('Choose one food, name another diner and the exact variant. You cannot normally serve yourself.','Elige una comida, nombra a otro comensal y la variedad exacta. Normalmente no puedes servirte.')],
      [L('Return','Devolver'),'1–3',L('Claim that fixed number of dishes were ordered by nobody: 3 at 2–4 players, 2 at 5–7, 1 at 8–9, none at 10.','Declara la cantidad fija de platos que nadie pidió: 3 con 2–4, 2 con 5–7, 1 con 8–9 y ninguno con 10.')],
      [L('Challenge','Reclamar'),'🔔',L('Ring first, identify the error and make the full correction. Wrong correction = one complaint.','Toca primero, identifica el error y haz la corrección completa. Corrección errónea = una queja.')],
      [L('Score','Puntuar'),'+3 / +1 / −2',L('Collected order +3; correctly returned food +1; complaint −2.','Pedido ganado +3; comida devuelta +1; queja −2.')]
    ],
    sections:[
      section('orders',L('Order round & memory','Ronda de pedidos y memoria'),[
        L('Separate order cards by category and give one from each category to every player: drink, starter, main dish, side and dessert. Each card offers two variants. Players choose, announce their entire order loudly, and place each card face down with the chosen variant oriented toward themselves.','Separa las comandas por categoría y entrega una de cada tipo a cada persona: bebida, entrada, principal, guarnición y postre. Cada carta ofrece dos variantes. Cada jugador elige, anuncia todo el pedido y deja cada carta boca abajo con la variante elegida hacia sí.'),
        L('Everyone is both diner and waiter, so memorize all orders, including your own. Once the order round ends, do not inspect cards except to verify a dish currently being served to you; an improper look earns a complaint.','Todos son comensales y camareros: memoriza todos los pedidos, incluso el propio. Tras esta ronda, no mires cartas salvo para verificar un plato que te estén sirviendo en ese momento; mirar fuera de turno da una queja.')
      ]),
      section('service',L('Serving or returning dishes','Servir o devolver platos'),[
        L('Shuffle food cards and reveal 8 as the kitchen. The player who most recently visited a restaurant starts; turns move to the right. On a turn announce one action. To serve, take one kitchen card, name another diner and the exact variant, then place it by that order. Only one dish may be served per turn.','Mezcla las comidas y revela 8 como cocina. Empieza quien fue más recientemente a un restaurante; los turnos siguen hacia la derecha. Anuncia una acción. Para servir, toma una comida, nombra a otro comensal y la variedad exacta y colócala junto a su comanda. Solo se sirve un plato por turno.'),
        L('Instead, return dishes you believe nobody ordered: exactly 3 with 2–4 players, 2 with 5–7, 1 with 8–9, and none with 10. Reveal them one at a time. Keep each correct return; the first mistake gives a complaint and ends the turn, but previously correct returns remain yours. Refill the kitchen.','Como alternativa, devuelve platos que crees que nadie pidió: exactamente 3 con 2–4 jugadores, 2 con 5–7, 1 con 8–9 y ninguno con 10. Hazlo de a uno. Conserva cada devolución correcta; el primer error da una queja y termina el turno, pero conservas los anteriores. Repón la cocina.')
      ]),
      section('bell',L('Bell, corrections & complaints','Timbre, correcciones y quejas'),[
        L('A challenge counts only if the player rings first, identifies what is wrong and states the full correction. If correct, the waiter receives a complaint and the challenger completes the service or keeps the correctly rescued dish. If incorrect, the challenger takes a complaint and the original action continues. Further players may challenge a bad correction.','Un reclamo solo vale si primero se toca el timbre, se explica el error y se da la corrección completa. Si acierta, el camarero recibe una queja y quien reclamó completa el servicio o conserva el plato rescatado. Si falla, recibe la queja y la acción original continúa. Otros pueden reclamar una corrección errónea.'),
        L('The owner of a dish may ring to rescue it; this is the only way to serve yourself. A correct dish sent to the correct diner but named as the wrong variant is still served, but the waiter gets a complaint and the order card is discarded if nobody corrected the variant in time.','El dueño de un plato puede tocar para rescatarlo; es la única forma de servirse a sí mismo. Si el plato y comensal son correctos pero la variedad es errónea, el plato se sirve, el camarero recibe una queja y la comanda se descarta si nadie corrigió a tiempo.')
      ]),
      section('scoring',L('End of game & scoring','Fin de partida y puntuación'),[
        L('The game ends when all orders are served or no food remains for the kitchen. Every unserved order gives its diner one complaint. Players keep order cards earned for correct service and food cards earned for correct returns.','La partida termina cuando todos los pedidos se sirvieron o no quedan comidas para la cocina. Cada pedido sin servir da una queja a su comensal. Conserva las comandas ganadas al servir bien y las comidas ganadas al devolver bien.'),
        L('Score 3 points per collected order card, 1 per collected food card and −2 per complaint. Highest total wins. For a tie, share the victory or play another table by agreement.','Suma 3 puntos por comanda ganada, 1 por comida ganada y −2 por queja. Gana el total más alto. En empate, compartan la victoria o jueguen otra mesa si lo acuerdan.')
      ])
    ],
    sources:[[L('El Camarero · official 2018 rules','El Camarero · reglamento oficial 2018'),'https://maldon.com.ar/wp-content/uploads/2018/09/REGLAMENTO-el-Camarero-2018.pdf'],[L('El Camarero · publisher','El Camarero · editorial'),'https://maldon.com.ar/blog/projects/el-camarero/']]
  },

  monopoly: {
    name:L('Monopoly','Monopoly'), subtitle:L('Buy property. Charge rent. Stay solvent.','Compra propiedades. Cobra alquileres. Evita la bancarrota.'),
    category:L('Property & negotiation','Propiedades y negociación'), players:'2–8', time:'60–180', icon:'book', color:'mint',
    edition:L('Classic rules','Reglas clásicas'), caption:L('A city of deeds, deals and rising rents','Una ciudad de títulos, acuerdos y alquileres'),
    description:L('Build monopolies, improve streets and bankrupt your opponents.','Forma monopolios, construye y lleva a tus rivales a la bancarrota.'),
    goal:L('Be the last player who has not gone bankrupt. Buy properties, collect rent, trade complete color groups and build houses and hotels evenly to increase income.','Sé la última persona que no haya quebrado. Compra propiedades, cobra alquiler, negocia grupos de color completos y construye casas y hoteles de forma pareja para aumentar ingresos.'),
    basics:[
      L('Choose a Banker, give each player the starting money listed in your edition and put all tokens on GO. The Banker manages deeds, buildings, auctions and bank money without mixing it with personal funds.','Elijan un banquero, entreguen el dinero inicial indicado en su edición y coloquen las fichas en SALIDA. El banco administra títulos, edificios, subastas y dinero sin mezclarlo con fondos personales.'),
      L('Roll two dice, move clockwise and resolve the space. If an unowned property is declined, the Banker must auction it immediately to all players. Doubles give another turn; three consecutive doubles send you to Jail.','Tira dos dados, avanza en sentido horario y resuelve la casilla. Si rechazas una propiedad libre, el banco debe subastarla de inmediato entre todos. Los dobles dan otro turno; tres dobles seguidos te envían a la cárcel.'),
      L('Pay rent when you land on another player’s unmortgaged property. Complete color groups may build houses, always evenly; sell buildings evenly in reverse before mortgaging a property.','Paga alquiler al caer en una propiedad rival no hipotecada. Los grupos completos pueden construir casas, siempre de forma pareja; vende edificios de manera pareja e inversa antes de hipotecar.'),
      L('If you owe more than you can raise by selling buildings, mortgaging and trading, you are bankrupt. Transfer remaining assets to the creditor; the last solvent player wins.','Si debes más de lo que puedes reunir vendiendo edificios, hipotecando y negociando, quiebras. Entrega tus activos restantes al acreedor; gana la última persona solvente.')
    ],
    lessonTitles:[L('Open the bank','Abre el banco'),L('Roll and resolve','Tira y resuelve'),L('Complete and build','Completa y construye'),L('Avoid bankruptcy','Evita la bancarrota')],
    reminder:L('Free Parking gives no money under the official rules, and declined unowned properties are auctioned. Both omissions make the game much longer.','Estacionamiento Libre no entrega dinero en las reglas oficiales y las propiedades libres rechazadas se subastan. Omitir ambas reglas alarga mucho la partida.'),
    galleryCopy:L('Deeds set purchase prices, rent and mortgage values. Houses and hotels raise rent; Chance and Community Chest interrupt the route.','Los títulos indican precio, alquiler e hipoteca. Casas y hoteles aumentan la renta; Suerte y Caja de Comunidad alteran el recorrido.'),
    quick:[
      [L('Unowned property','Propiedad libre'),'Buy / auction',L('Buy at the printed price or decline; the Banker auctions it immediately.','Compra al precio impreso o rechaza; el banco la subasta de inmediato.')],
      [L('Owned property','Propiedad ajena'),'Rent',L('Pay the deed’s current rent unless it is mortgaged.','Paga el alquiler actual del título salvo que esté hipotecado.')],
      [L('Doubles','Dobles'),'↻',L('Resolve the move and roll again. Three doubles in one turn sends you directly to Jail.','Resuelve el movimiento y vuelve a tirar. Tres dobles en un turno te envían a la cárcel.')],
      [L('Color group','Grupo de color'),'⌂',L('Build evenly across the group; four houses precede one hotel.','Construye de forma pareja; cuatro casas preceden a un hotel.')]
    ],
    sections:[
      section('setup',L('Setup, Banker & money','Preparación, banco y dinero'),[
        L('Lay out the board, shuffle Chance and Community Chest decks and place them face down. Each player chooses a token and receives the starting cash listed in the box. Choose a Banker who keeps the bank’s money, deeds, houses and hotels separate from personal assets. The bank never goes bankrupt; record extra money if needed.','Coloca el tablero, mezcla Suerte y Caja de Comunidad y déjalas boca abajo. Cada persona elige ficha y recibe el efectivo inicial indicado en la caja. El banquero mantiene dinero, títulos, casas y hoteles del banco separados de sus bienes. El banco nunca quiebra; anota dinero adicional si hace falta.'),
        L('Everyone starts on GO. Highest roll begins and play moves clockwise. A player may trade before rolling or after resolving a move when the table permits, but never interrupt the resolution of another player’s debt.','Todos empiezan en SALIDA. Comienza la tirada más alta y siguen en sentido horario. Se puede negociar antes de tirar o tras resolver el movimiento cuando la mesa lo permita, pero nunca interrumpir el pago de una deuda ajena.')
      ]),
      section('movement',L('Movement, spaces & auctions','Movimiento, casillas y subastas'),[
        L('Roll, move the total clockwise and fully resolve the destination. Passing or landing on GO collects the printed salary unless a card says otherwise. Draw and obey cards immediately. Pay taxes to the bank. Free Parking is only a resting space.','Tira, avanza el total y resuelve por completo la casilla final. Pasar o caer en SALIDA cobra el salario impreso salvo que una carta diga otra cosa. Roba y cumple cartas de inmediato. Paga impuestos al banco. Estacionamiento Libre es solo descanso.'),
        L('On an unowned property, buy it for the printed price or decline it. If declined, the Banker auctions it to every player, including the person who declined; bidding may begin at any amount and the highest bidder pays the bank.','En una propiedad libre, cómprala al precio impreso o recházala. Si la rechazas, el banco la subasta entre todos, incluida esa persona; la puja puede comenzar en cualquier valor y la oferta mayor paga al banco.')
      ]),
      section('property',L('Rent, building & shortages','Alquiler, construcción y escasez'),[
        L('Landing on an unmortgaged property means paying its owner the rent on the deed. Owning every property in a color group doubles the unimproved rent, provided none in that group is mortgaged. Railroad/station and utility rents follow their deeds.','Caer en una propiedad no hipotecada obliga a pagar al dueño el alquiler del título. Poseer todo un color duplica el alquiler sin construir si ninguna propiedad del grupo está hipotecada. Ferrocarriles/estaciones y servicios siguen sus títulos.'),
        L('Only complete, unmortgaged color groups may receive buildings. Build evenly: no property may be more than one house ahead of another in its group. After four houses, replace those four with a hotel. If buildings are scarce, auction the available pieces. Sell buildings to the bank for half price, evenly in reverse.','Solo los colores completos y sin hipotecas reciben edificios. Construye parejo: ninguna propiedad puede superar por más de una casa a otra del grupo. Tras cuatro casas, cámbialas por hotel. Si faltan edificios, subasta los disponibles. Véndelos al banco por la mitad y de forma pareja e inversa.')
      ]),
      section('jail',L('Jail, doubles & cards','Cárcel, dobles y cartas'),[
        L('Go to Jail when instructed or after rolling doubles three times in one turn; do not collect GO money on that move. In Jail you may still collect rent, trade, mortgage and build. Leave by paying the fine before rolling, using a Get Out of Jail Free card, or rolling doubles within three attempts.','Ve a la cárcel por instrucción o tras tres dobles en un turno; no cobres SALIDA por ese traslado. En la cárcel puedes cobrar, negociar, hipotecar y construir. Sal pagando antes de tirar, usando una carta o sacando dobles en hasta tres intentos.'),
        L('If the third attempt is not doubles, pay the fine and move by that roll. Doubles used to leave Jail do not grant another roll. Keep Get Out of Jail Free cards until used or traded, then return them to the bottom of their deck.','Si el tercer intento no es doble, paga y avanza esa tirada. Los dobles usados para salir no dan otra tirada. Conserva las cartas de salida hasta usarlas o negociarlas y luego devuélvelas al fondo del mazo.')
      ]),
      section('trading',L('Trading, mortgages & bankruptcy','Negociación, hipotecas y bancarrota'),[
        L('Players may trade cash, unbuilt properties and Get Out of Jail Free cards in any agreed combination. Buildings go only to the bank; sell all buildings in a color group before trading or mortgaging any property in that group. Mortgaged property collects no rent.','Se puede negociar dinero, propiedades sin edificios y cartas de salida en cualquier combinación acordada. Los edificios solo vuelven al banco; vende todos los de un color antes de negociar o hipotecar una propiedad de ese grupo. Una hipotecada no cobra alquiler.'),
        L('To lift a mortgage, pay the bank the mortgage value plus the edition’s interest. If you cannot pay a debt after raising all possible money, declare bankruptcy. Assets go to a player creditor; if the bank is creditor, properties return and are auctioned. The last remaining player wins.','Para cancelar una hipoteca, paga al banco el valor más el interés de la edición. Si no puedes pagar tras reunir todo lo posible, declara bancarrota. Los bienes pasan al jugador acreedor; si es el banco, las propiedades regresan y se subastan. Gana la última persona restante.')
      ])
    ],
    sources:[[L('Monopoly Classic · official instructions','Monopoly Clásico · instrucciones oficiales'),'https://instructions.hasbro.com/es-co/instruction/monopoly-clasico'],[L('Monopoly Classic · product rules','Monopoly Classic · reglas del producto'),'https://instructions.hasbro.com/en-my/instruction/monopoly-classic-game']]
  },

  chess: {
    name:L('Chess','Ajedrez'), subtitle:L('Control the board. Trap the king.','Controla el tablero. Atrapa al rey.'),
    category:L('Abstract strategy','Estrategia abstracta'), players:'2', time:'20–90', icon:'crown', color:'lavender',
    edition:L('FIDE basic over-the-board rules','Reglas básicas FIDE sobre tablero'), caption:L('Sixty-four squares. No hidden information.','Sesenta y cuatro casillas. Sin información oculta.'),
    description:L('Develop your pieces, protect your king and deliver checkmate.','Desarrolla tus piezas, protege a tu rey y da jaque mate.'),
    goal:L('Checkmate the opposing king: attack it so that no legal move removes the threat. A player may also win by resignation or time in a clocked game; several positions end in a draw.','Da jaque mate al rey rival: atácalo de modo que ninguna jugada legal elimine la amenaza. También se gana por abandono o tiempo con reloj; varias posiciones terminan en tablas.'),
    basics:[
      L('Place the board with a light square at each player’s right. Set pieces on the nearest two ranks: rooks in corners, then knights, bishops, queen on her own color, king; pawns in front. White moves first.','Coloca el tablero con una casilla clara a la derecha de cada jugador. Ordena las piezas en dos filas: torres en esquinas, luego caballos, alfiles, dama en su color y rey; peones delante. Blancas empiezan.'),
      L('Move one piece per turn. Sliding pieces cannot jump; knights can. Capture by moving onto an enemy piece. You may never make a move that leaves your own king in check.','Mueve una pieza por turno. Las piezas deslizantes no saltan; los caballos sí. Captura ocupando la casilla rival. Nunca puedes dejar a tu propio rey en jaque.'),
      L('When your king is attacked, answer immediately by moving it, capturing the attacker or blocking the line. If none is legal, it is checkmate and the game ends.','Cuando atacan a tu rey, responde moviéndolo, capturando al atacante o bloqueando la línea. Si nada es legal, es jaque mate y termina la partida.'),
      L('Remember castling, pawn promotion and en passant. Stalemate, insufficient mating material and certain repetition or move-count claims produce a draw.','Recuerda el enroque, la promoción y la captura al paso. Ahogado, material insuficiente y ciertas reclamaciones por repetición o cantidad de jugadas producen tablas.')
    ],
    lessonTitles:[L('Set the board','Arma el tablero'),L('Move and capture','Mueve y captura'),L('Answer check','Responde al jaque'),L('Know special endings','Conoce los finales')],
    reminder:L('Check is not a capture of the king. Stop before any illegal king capture: if the checked player has no legal reply, the position is checkmate.','El jaque no implica capturar al rey. Detente antes de una captura ilegal: si el jugador en jaque no tiene respuesta legal, es mate.'),
    galleryCopy:L('Each side has 16 pieces. Their shapes identify how they move; the clock is optional for casual games and alternates after every move.','Cada bando tiene 16 piezas. Sus formas indican su movimiento; el reloj es opcional en partidas casuales y alterna tras cada jugada.'),
    quick:[
      [L('King','Rey'),'1',L('Moves one square in any direction and may never move onto an attacked square.','Mueve una casilla en cualquier dirección y nunca puede entrar en una casilla atacada.')],
      [L('Queen','Dama'),'∞',L('Slides any distance along a rank, file or diagonal; it cannot jump over pieces.','Se desliza cualquier distancia por fila, columna o diagonal; no puede saltar piezas.')],
      [L('Rook','Torre'),'+',L('Slides any distance along a rank or file; it cannot jump over pieces.','Se desliza cualquier distancia por fila o columna; no puede saltar piezas.')],
      [L('Bishop','Alfil'),'×',L('Slides any distance diagonally and always remains on the same square color.','Se desliza cualquier distancia en diagonal y siempre permanece en el mismo color de casilla.')],
      [L('Knight','Caballo'),'L',L('Two squares in one direction and one perpendicular; it may jump over pieces.','Dos casillas en una dirección y una perpendicular; puede saltar piezas.')],
      [L('Pawn','Peón'),'↑ / ×',L('Moves forward, captures one diagonal forward; promotes on the last rank.','Avanza recto, captura una diagonal hacia delante y promociona al llegar al final.')]
    ],
    sections:[
      section('setup',L('Board setup & turn order','Preparación y turnos'),[
        L('Orient the board so the near-right corner is light. From left to right on White’s back rank: rook, knight, bishop, queen, king, bishop, knight, rook; Black mirrors this. Queens begin on their own color. Put eight pawns in front. White makes the first move, then alternate.','Orienta el tablero con la esquina derecha cercana clara. De izquierda a derecha para blancas: torre, caballo, alfil, dama, rey, alfil, caballo, torre; negras lo refleja. Las damas empiezan en su color. Coloca ocho peones delante. Blancas mueven primero y luego alternan.'),
        L('A legal move transfers one piece to an empty square or a square occupied by an opponent, which is captured and removed. Except for knights and castling, pieces cannot cross occupied squares. A move is illegal if it exposes or leaves your own king under attack.','Una jugada legal lleva una pieza a una casilla vacía o rival, que se captura y retira. Salvo caballos y enroque, no se atraviesan casillas ocupadas. Una jugada es ilegal si expone o deja a tu propio rey atacado.')
      ]),
      section('pieces',L('How every piece moves','Movimiento de cada pieza'),[
        L('The king moves one square in any direction. The queen slides any distance along ranks, files or diagonals. A rook slides along ranks or files; a bishop slides diagonally and therefore stays on one square color. A knight moves in an L: two squares one way and one perpendicular, jumping over intervening pieces.','El rey mueve una casilla en cualquier dirección. La dama se desliza cualquier distancia por filas, columnas o diagonales. La torre va por filas o columnas; el alfil por diagonales y permanece en un color. El caballo mueve en L: dos casillas en un sentido y una perpendicular, saltando piezas intermedias.'),
        L('A pawn moves one square straight forward if empty; from its starting square it may move two if both are empty. It captures one square diagonally forward. Pawns never move backward. On reaching the last rank, replace it immediately with a queen, rook, bishop or knight of the same color; the choice is not limited by captured pieces.','El peón avanza una casilla recta si está vacía; desde su inicio puede avanzar dos si ambas están libres. Captura una diagonal hacia delante y nunca retrocede. Al llegar a la última fila, reemplázalo de inmediato por dama, torre, alfil o caballo del mismo color, sin limitarse a piezas capturadas.')
      ]),
      section('special',L('Castling, en passant & promotion','Enroque, al paso y promoción'),[
        L('Castling moves the king two squares toward a rook, then places that rook on the square crossed by the king. It is legal only if king and rook have never moved, squares between them are empty, the king is not in check, and the king does not cross or land on an attacked square. The rook may cross an attacked square.','El enroque mueve el rey dos casillas hacia una torre y coloca esa torre en la casilla cruzada. Solo es legal si rey y torre no se movieron, no hay piezas entre ellos, el rey no está en jaque ni cruza o termina en casilla atacada. La torre sí puede cruzar una casilla atacada.'),
        L('If an enemy pawn advances two squares and lands beside your pawn, your pawn may capture it as though it had moved only one square. This en passant capture is available only on the immediately following move. Promotion is mandatory on the final rank and completes the move.','Si un peón rival avanza dos y termina junto al tuyo, puedes capturarlo como si hubiera avanzado una sola casilla. La captura al paso solo existe en la jugada inmediatamente siguiente. La promoción es obligatoria al llegar al final y completa la jugada.')
      ]),
      section('check',L('Check, checkmate & stalemate','Jaque, mate y ahogado'),[
        L('A king is in check when attacked. The player must make a legal move that removes every attack: move the king, capture the checking piece or interpose a piece against a sliding attack. Double check can be answered only by moving the king. If no answer exists, checkmate ends the game.','Un rey está en jaque cuando es atacado. Debe hacerse una jugada legal que quite todos los ataques: mover el rey, capturar al atacante o interponer una pieza ante un ataque deslizante. El jaque doble solo se responde moviendo el rey. Sin respuesta, el mate termina la partida.'),
        L('If the player to move is not in check but has no legal move, the game is a draw by stalemate. Players may agree to a draw. Dead positions where no possible sequence can produce mate are also drawn.','Si quien debe mover no está en jaque pero no tiene jugada legal, hay tablas por ahogado. Se pueden acordar tablas. Las posiciones muertas donde ninguna secuencia puede producir mate también son tablas.')
      ]),
      section('draws',L('Draw claims & clocks','Reclamos de tablas y reloj'),[
        L('Under FIDE rules, a player may claim a draw when the same position is about to appear or has appeared for the third time with the same player to move and the same legal possibilities, or after 50 moves by each side without a pawn move or capture. Fivefold repetition and 75 such moves end the game automatically, unless the last move checkmates.','Según FIDE, se pueden reclamar tablas cuando la misma posición va a aparecer o apareció por tercera vez con el mismo turno y posibilidades legales, o tras 50 jugadas de cada bando sin mover peón ni capturar. Cinco repeticiones y 75 jugadas así terminan automáticamente, salvo mate en la última.'),
        L('With a clock, press your side after completing each move. A player whose time expires normally loses if the opponent has any possible mating sequence; otherwise the result is a draw. Agree on the time control and how illegal moves are handled before casual play.','Con reloj, pulsa tu lado tras completar cada jugada. Quien agota su tiempo normalmente pierde si el rival tiene alguna secuencia posible de mate; si no, son tablas. Acuerden el ritmo y el tratamiento de jugadas ilegales antes de una partida casual.')
      ])
    ],
    sources:[[L('FIDE Laws of Chess','Leyes del Ajedrez FIDE'),'https://handbook.fide.com/chapter/E012023']]
  },

  burako: {
    name:L('Burako','Burako'), subtitle:L('Build melds. Reach the dead pile. Close cleanly.','Forma juegos. Llega al muerto. Cierra bien.'),
    category:L('Tile rummy','Rummy de fichas'), players:'2 / 4', time:'60–120', icon:'grid', color:'mint',
    edition:L('Rioplatense tile variant','Variante rioplatense con fichas'), caption:L('Runs, groups and the promise of a canasta','Escaleras, piernas y la promesa de una canasta'),
    description:L('Combine numbered tiles, complete canastas and score over several hands.','Combina fichas numeradas, completa canastas y suma puntos en varias manos.'),
    goal:L('Be the first player or partnership to reach the agreed score, commonly 3000 points. Score tiles laid on the table and bonuses for canastas and closing; subtract tiles left on racks and an unclaimed dead pile.','Sé la primera persona o pareja en alcanzar el puntaje acordado, habitualmente 3000. Suma fichas bajadas y bonos por canastas y cierre; resta fichas del atril y el muerto no levantado.'),
    basics:[
      L('Play with 104 numbered tiles—two copies of 1–13 in four colors—plus 2 jokers. Deal 22 each for two players or 11 each for four; prepare two face-down dead piles of 11.','Juega con 104 fichas numeradas —dos copias del 1 al 13 en cuatro colores— y 2 comodines. Reparte 22 a cada uno con dos jugadores u 11 con cuatro; prepara dos muertos boca abajo de 11 fichas.'),
      L('Begin every turn by drawing one tile from the stock or taking the entire discard pile. Then lay new melds or add to your side’s melds. Finish by discarding one tile face up.','Comienza cada turno robando una ficha de la pila o levantando todo el pozo. Luego baja juegos nuevos o agrega a los de tu lado. Termina descartando una ficha boca arriba.'),
      L('Valid melds contain at least three tiles: equal numbers in different colors, or consecutive numbers of one color. A meld may contain at most one wild tile; a 2 is wild unless it occupies its natural place in a run.','Los juegos válidos tienen al menos tres fichas: números iguales de colores distintos o números consecutivos del mismo color. Puede haber como máximo un comodín; el 2 es comodín salvo en su lugar natural de una escalera.'),
      L('A meld of seven or more is a canasta: clean without a wild tile, dirty with one. After exhausting the first rack, take your team’s dead pile. Once it has been taken, a player may empty the rack to close the hand.','Un juego de siete o más es canasta: limpia sin comodín, sucia con uno. Al vaciar el primer atril, toma el muerto del equipo. Una vez levantado, un jugador puede vaciar su atril para cerrar la mano.')
    ],
    lessonTitles:[L('Deal racks and dead piles','Reparte atriles y muertos'),L('Draw, meld and discard','Roba, baja y descarta'),L('Complete a canasta','Completa una canasta'),L('Take the dead pile and close','Levanta el muerto y cierra')],
    reminder:L('Burako has many house variants. This guide uses the Argentine coastal 2/4-player form: 22 or 11 tiles, 11-tile dead piles, one wild tile per meld and a 3000-point target.','Burako tiene muchas variantes. Esta guía usa la forma argentino-costera para 2/4: 22 u 11 fichas, muertos de 11, un comodín por juego y meta de 3000 puntos.'),
    galleryCopy:L('Numbered tiles form same-number groups or same-color runs. The rack hides your hand; two reserved dead piles extend each side’s hand.','Las fichas forman piernas del mismo número o escaleras del mismo color. El atril oculta la mano y dos muertos reservados prolongan cada lado.'),
    quick:[
      [L('Draw','Levantar'),'1 / all',L('Take one from the stock or the entire face-up discard pile.','Toma una de la pila o todo el pozo boca arriba.')],
      [L('Meld','Bajar'),'3+',L('Same number in different colors, or a consecutive run in one color.','Mismo número en distintos colores o escalera consecutiva de un color.')],
      [L('Canasta','Canasta'),'7+',L('Clean = no wild tile, 200 points. Dirty = one wild tile, 100 points.','Limpia = sin comodín, 200 puntos. Sucia = un comodín, 100 puntos.')],
      [L('Close','Cerrar'),'+100',L('Your side must already have taken its dead pile; empty your rack to end the hand.','Tu lado ya debe haber levantado el muerto; vacía el atril para terminar la mano.')]
    ],
    sections:[
      section('setup',L('Tiles, teams & deal','Fichas, equipos y reparto'),[
        L('Use two identical sets of 1–13 in four colors plus 2 jokers: 106 tiles total. For two players, deal 22 tiles to each; for four, form opposite partnerships and deal 11 each. Make two separate 11-tile dead piles, one for each player or team. Stack the rest face down and begin a face-up discard pile.','Usa dos juegos idénticos del 1 al 13 en cuatro colores más 2 comodines: 106 fichas. Con dos jugadores, reparte 22 a cada uno; con cuatro, forma parejas enfrentadas y reparte 11. Prepara dos muertos separados de 11, uno por jugador o equipo. Apila el resto boca abajo e inicia un pozo boca arriba.'),
        L('Partners share all exposed melds but keep racks private. Choose a first player; turns proceed consistently around the table. Agree on the target score—3000 in this guide—and any house variations before dealing.','Las parejas comparten todos los juegos expuestos, pero mantienen privados sus atriles. Elijan quién empieza y sigan el mismo sentido. Acuerden la meta —3000 en esta guía— y cualquier variante antes de repartir.')
      ]),
      section('turn',L('Draw, meld & discard','Levantar, bajar y descartar'),[
        L('At the start of every turn choose exactly one source: draw the top face-down tile, or take the entire discard pile. You may then create any number of valid melds and add tiles to any meld owned by your side. End by discarding one tile face up.','Al iniciar cada turno elige una fuente: roba la ficha superior boca abajo o toma todo el pozo. Luego puedes crear cualquier cantidad de juegos válidos y agregar fichas a cualquiera de tu lado. Termina descartando una boca arriba.'),
        L('A group uses the same number in different colors; a run uses consecutive numbers of one color. Each begins with at least three tiles. Runs may continue 11–12–13–1, but do not wrap onward from 1 to 2 in the same run under this variant.','Una pierna usa el mismo número de colores distintos; una escalera usa consecutivos de un color. Cada juego empieza con al menos tres. Las escaleras pueden seguir 11–12–13–1, pero en esta variante no continúan del 1 al 2 dentro de la misma vuelta.')
      ]),
      section('wilds',L('Wild tiles & canastas','Comodines y canastas'),[
        L('A joker or a number 2 outside its natural position substitutes for a missing tile. Each meld may contain at most one wild tile. You may move that wild tile within the same meld when adding the natural tile, but may not remove it for another meld. A 2 placed naturally between 1 and 3 is ordinary.','Un comodín o un 2 fuera de su posición sustituye una ficha faltante. Cada juego admite como máximo uno. Al agregar la ficha natural puedes moverlo dentro del mismo juego, pero no retirarlo para otro. Un 2 natural entre 1 y 3 es normal.'),
        L('Seven or more tiles in one meld make a canasta. It is clean when it has no wild tile and scores a 200-point bonus; it is dirty with a wild tile and scores 100. A natural 2 does not make a run dirty.','Siete o más fichas en un juego forman canasta. Es limpia sin comodín y bonifica 200; es sucia con comodín y bonifica 100. Un 2 natural no ensucia la escalera.')
      ]),
      section('dead-pile',L('Dead pile, closing & blocked stock','Muerto, cierre y pila agotada'),[
        L('When a player empties the initial rack by melding every tile, take the side’s dead pile immediately and continue the turn; if the last tile was discarded, take the dead pile but wait until the next turn to play it. Each side takes only one dead pile.','Cuando alguien vacía el atril inicial bajando todo, toma el muerto de su lado y continúa el turno; si la última ficha fue descartada, toma el muerto pero espera al próximo turno para jugarlo. Cada lado toma un solo muerto.'),
        L('After the dead pile has been taken, emptying a rack ends the hand (closing). If the stock runs out first, the hand also ends. Under this scoring variant a canasta is required for exposed tile values to count positively, so check the table before closing.','Después de levantar el muerto, vaciar un atril termina la mano (cierre). Si antes se agota la pila, también termina. En esta puntuación se requiere una canasta para que las fichas bajadas sumen positivo, así que revisa la mesa antes de cerrar.')
      ]),
      section('scoring',L('Scoring a hand','Puntuación de la mano'),[
        L('Add 100 for closing, 100 per dirty canasta and 200 per clean canasta; subtract 100 for an unclaimed dead pile. If the side has at least one canasta, add exposed tile values; otherwise subtract them. Always subtract tiles left on racks.','Suma 100 por cierre, 100 por canasta sucia y 200 por limpia; resta 100 por muerto no levantado. Con al menos una canasta, suma el valor de las fichas bajadas; sin canasta, réstalo. Siempre resta las fichas de los atriles.'),
        L('Tile values: 3–7 = 5 each; 8–13 = 10; ace/1 = 15; 2 = 20; joker = 50. Record totals and deal another hand until a side reaches 3000; the higher total wins if both cross the target together.','Valores: 3–7 = 5; 8–13 = 10; as/1 = 15; 2 = 20; comodín = 50. Registra totales y reparte otra mano hasta que un lado llegue a 3000; si ambos cruzan la meta juntos, gana el total mayor.')
      ])
    ],
    sources:[[L('Al Burako · Argentine coastal rules','Al Burako · reglas argentino-costeras'),'https://alburako.com/es/ayuda'],[L('Pagat · Burako rules','Pagat · reglas de Burako'),'https://www.pagat.com/rummy/burako.html'],[L('Ruibal · Rummy-Burako rules','Ruibal · reglamento Rummy-Burako'),'https://ruibalgames.com/wp-content/uploads/2015/11/Reglas-de-juego-%E2%80%93-Rummy-Burako-Cl%C3%A1sico-y-Profesional.pdf']]
  },

  truco: {
    name:L('Uruguayan Truco','Truco Uruguayo'), subtitle:L('Read the muestra. Sing boldly. Bluff better.','Lee la muestra. Canta fuerte. Miente mejor.'),
    category:L('Trick-taking & bluffing','Bazas y engaño'), players:'2 / 4', time:'30–60', icon:'spade', color:'peach',
    edition:L('Uruguayan variant · muestra & piezas','Variante uruguaya · muestra y piezas'), caption:L('Three cards, two contests and one great bluff','Tres cartas, dos disputas y un gran engaño'),
    description:L('Win tricks, challenge the envido and use the muestra to find the pieces.','Gana bazas, disputa el envido y usa la muestra para descubrir las piezas.'),
    goal:L('Be the first player or partnership to reach the agreed score, commonly 30 points split into 15 malas and 15 buenas. Each hand can score through flor/envido and through truco; declining a challenge also gives points.','Sé la primera persona o pareja en alcanzar el puntaje acordado, normalmente 30: 15 malas y 15 buenas. Cada mano puntúa mediante flor/envido y mediante truco; rechazar un canto también entrega puntos.'),
    basics:[
      L('Use a 40-card Spanish deck. Deal three cards each, then reveal the muestra under the deck. Its suit creates five top pieces: 2, 4, 5, 11 and 10; if the revealed card is one of those ranks, the 12 of that suit replaces it.','Usa baraja española de 40. Reparte tres cartas y revela la muestra bajo el mazo. Su palo crea cinco piezas superiores: 2, 4, 5, 11 y 10; si la propia muestra tiene uno de esos valores, el 12 de ese palo la reemplaza.'),
      L('Before or while playing the first trick, resolve flor if used and then envido according to your table’s calling window. Higher valid count wins; ties go to mano, the first player after the dealer.','Antes o durante la primera baza, resuelve la flor si se usa y luego el envido según la ventana acordada. Gana el tanto mayor; los empates favorecen a mano, quien juega primero tras el repartidor.'),
      L('Play one card each to a trick. Highest rank wins and leads the next. Win two of three tricks; tied tricks are resolved in favor of the hand that won earlier, and if all are tied, mano wins.','Juega una carta cada uno por baza. La mayor gana y sale en la siguiente. Gana dos de tres; las bazas pardas favorecen a quien ganó antes y, si todas empatan, gana mano.'),
      L('The hand is worth 1 point unless Truco is accepted, then 2; Retruco raises it to 3 and Vale Cuatro to 4. A team may decline, conceding the value before the refused raise.','La mano vale 1 punto salvo Truco aceptado, que vale 2; Retruco sube a 3 y Vale Cuatro a 4. Se puede rechazar y conceder el valor anterior al aumento rechazado.')
    ],
    lessonTitles:[L('Deal and reveal the muestra','Reparte y muestra'),L('Count flor and envido','Cuenta flor y envido'),L('Play the three tricks','Juega las tres bazas'),L('Raise the truco','Sube el truco')],
    reminder:L('Truco changes by region and table. Before starting, agree whether flor is used, when envido may be called, the target score and which signals are allowed.','El Truco cambia según región y mesa. Antes de empezar acuerden si hay flor, cuándo se canta envido, el puntaje final y qué señas se permiten.'),
    galleryCopy:L('The face-up muestra defines the five pieces, the strongest cards in the hand. Partners keep cards hidden and communicate only through the signals accepted by the table.','La muestra boca arriba define las cinco piezas, las cartas más fuertes. Las parejas ocultan sus cartas y se comunican solo con las señas aceptadas.'),
    quick:[
      [L('Pieces','Piezas'),'2·4·5·11·10',L('These ranks in the muestra suit outrank every mata; if the muestra is one, the 12 replaces it.','Esos valores del palo de muestra superan todas las matas; si la muestra es una, el 12 la reemplaza.')],
      [L('Envido','Envido'),'20 + 2',L('Two same-suit cards score 20 plus their units; pieces adapt their suit and special values.','Dos del mismo palo suman 20 más sus unidades; las piezas adaptan palo y valores especiales.')],
      [L('Tricks','Bazas'),'2 / 3',L('Win two tricks. A tied trick favors the side that won an earlier one; three ties favor mano.','Gana dos bazas. Una parda favorece a quien ganó antes; tres pardas favorecen a mano.')],
      [L('Truco ladder','Escalera de truco'),'1→2→3→4',L('Uncalled hand 1; accepted Truco 2; Retruco 3; Vale Cuatro 4.','Mano sin canto 1; Truco querido 2; Retruco 3; Vale Cuatro 4.')]
    ],
    sections:[
      section('setup',L('Teams, deal & muestra','Equipos, reparto y muestra'),[
        L('Play one against one or two partnerships with partners opposite. Use a 40-card Spanish deck without 8s and 9s. The dealer gives three cards to each player, then exposes the next card crosswise beneath the deck as the muestra. Mano, to the dealer’s right, leads; deal passes to the right after each hand.','Juega uno contra uno o en dos parejas enfrentadas. Usa baraja española de 40 sin 8 ni 9. El repartidor da tres cartas a cada uno y expone la siguiente cruzada bajo el mazo como muestra. Mano, a su derecha, sale; el reparto pasa a la derecha tras cada mano.'),
        L('Agree on 30 points (15 malas, 15 buenas), whether flor is active and the table’s exact calling conventions. Partners may use agreed traditional signals but never show or explicitly name their cards to one another.','Acuerden 30 puntos (15 malas y 15 buenas), si se juega con flor y las convenciones exactas de canto. Las parejas pueden usar señas tradicionales acordadas, pero nunca mostrar ni nombrar explícitamente sus cartas.')
      ]),
      section('ranking',L('Muestra, pieces & card ranking','Muestra, piezas y jerarquía'),[
        L('The 2, 4, 5, 11 and 10 of the muestra suit become pieces, strongest in that order. If the upcard itself is one of those ranks, the 12 of that suit becomes the missing piece with its value. Then come the matas: ace of swords, ace of clubs, 7 of swords, 7 of coins.','El 2, 4, 5, 11 y 10 del palo de muestra son piezas, fuertes en ese orden. Si la carta mostrada tiene uno de esos valores, el 12 de ese palo se convierte en la pieza faltante con su valor. Luego siguen las matas: as de espadas, as de bastos, 7 de espadas y 7 de oros.'),
        L('After the matas: all 3s, ordinary 2s, ace of cups and coins, kings, ordinary knights, ordinary jacks, ordinary 7s, then 6, 5 and 4. Cards of the same rank tie. The 3, 6, ace and 7 of the muestra suit stay ordinary except when already a mata.','Tras las matas: todos los 3, doses comunes, ases de copa y oro, reyes, caballos comunes, sotas comunes, sietes comunes y luego 6, 5 y 4. Cartas del mismo valor empatan. El 3, 6, as y 7 del palo de muestra siguen normales salvo que ya sean mata.')
      ]),
      section('flor-envido',L('Flor & envido','Flor y envido'),[
        L('For envido, ordinary 10–12 are worth 0 and 1–7 their number. Two cards of one suit score 20 plus their values; otherwise use the highest single value. A piece may join any suit and contributes its special unit: 2=10, 4=9, 5=8, 11 or 10=7. Thus a piece always forms at least a two-card envido. Ties go to mano.','Para envido, 10–12 comunes valen 0 y 1–7 su número. Dos cartas de un palo suman 20 más sus valores; si no, vale la mayor. Una pieza se une a cualquier palo y aporta su unidad especial: 2=10, 4=9, 5=8, 11 o 10=7. Por eso una pieza siempre forma al menos un envido de dos cartas. Empates para mano.'),
        L('With flor enabled, three cards of one suit form flor; so do one piece plus two cards of the same suit, or two pieces with any third card. Flor takes priority over envido. Exact raises such as contra-flor and scoring vary locally, so use the convention agreed before play.','Con flor activa, tres cartas de un palo forman flor; también una pieza con dos del mismo palo o dos piezas con cualquier tercera. La flor tiene prioridad sobre el envido. Aumentos como contra-flor y su puntaje varían, así que usen lo acordado antes de jugar.')
      ]),
      section('tricks',L('Tricks, ties & the hand','Bazas, pardas y la mano'),[
        L('Mano leads any card; each player follows with any card because there is no obligation to follow suit. The highest card wins and its player leads the next trick. The first side to win two tricks wins the hand, so a third trick may be unnecessary.','Mano sale con cualquier carta; los demás juegan cualquiera porque no hay obligación de seguir palo. La carta mayor gana y su jugador sale después. El primer lado que gana dos bazas gana la mano, por lo que puede no hacer falta una tercera.'),
        L('If the first trick ties, the winner of the second wins the hand. If a later trick ties, the side that won the earliest untied trick wins. If all three tie, mano’s side wins. A player may fold to concede the current stake.','Si la primera es parda, quien gana la segunda gana la mano. Si una baza posterior empata, gana el lado que obtuvo la primera baza no empatada. Si las tres son pardas, gana el lado de mano. Un jugador puede irse al mazo y ceder lo apostado.')
      ]),
      section('bidding',L('Truco, Retruco & Vale Cuatro','Truco, Retruco y Vale Cuatro'),[
        L('Without a challenge, the hand is worth 1. Either side may call Truco; if accepted it is worth 2. The accepting side may later call Retruco for 3, and the other side may answer Vale Cuatro for 4. A call must be answered before play continues. Bluffing is allowed.','Sin canto, la mano vale 1. Cualquier lado puede cantar Truco; querido vale 2. El lado que aceptó puede cantar luego Retruco por 3 y el otro responder Vale Cuatro por 4. Cada canto se responde antes de seguir. Se permite mentir.'),
        L('If Truco is declined, the caller scores 1. If Retruco is declined, the side that called it scores the previously accepted 2; if Vale Cuatro is declined, its caller scores the previously accepted 3. Keep flor/envido points separate from the trick stake.','Si no quieren Truco, quien cantó suma 1. Si rechazan Retruco, quien lo cantó suma los 2 ya aceptados; si rechazan Vale Cuatro, suma los 3 aceptados. Mantén flor/envido separado del valor de las bazas.')
      ])
    ],
    sources:[[L('Pagat · Uruguayan Truco','Pagat · Truco uruguayo'),'https://www.pagat.com/put/truco_ur.html'],[L('Quiero Truco · Uruguayan rules','Quiero Truco · reglas uruguayas'),'https://quierotruco.com/reglas-del-truco-uruguayo']]
  }
});

const NEW_GAME_ART = {
  'catan-box':{src:'assets/real/catan-box-cutout.png',title:L('CATAN · sixth-edition box','CATAN · caja de la sexta edición'),owner:'CATAN Studio',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:880,height:882},
  'catan-board':{src:'assets/real/catan-board.jpg',title:L('CATAN · board and components','CATAN · tablero y componentes'),owner:'CATAN Studio',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:1000,height:1000},
  'catan-cards':{src:'assets/real/catan-cards.jpg',title:L('CATAN · resource cards','CATAN · cartas de recursos'),owner:'CATAN Studio · product photograph via Cape Fear Games',url:'https://www.capefeargamesilm.com/catan-6th-edition-base-game-card-accessory.html',group:'catan',width:2000,height:2000},
  'catan-roll':{src:'assets/real/catan-roll.png',title:L('CATAN · dice and resource production','CATAN · dados y producción de recursos'),owner:'CATAN Studio · contextual crop from the product photograph',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:600,height:600,credit:false},
  'catan-trade':{src:'assets/real/catan-trade.png',title:L('CATAN · resource cards for trading','CATAN · cartas de recursos para comerciar'),owner:'CATAN Studio · contextual crop from the product photograph',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:600,height:600,credit:false},
  'catan-build':{src:'assets/real/catan-build.png',title:L('CATAN · roads and settlements','CATAN · caminos y poblados'),owner:'CATAN Studio · contextual crop from the product photograph',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:600,height:600,credit:false},
  'catan-robber':{src:'assets/real/catan-robber.png',title:L('CATAN · robber and desert hex','CATAN · ladrón y hexágono de desierto'),owner:'CATAN Studio · contextual crop from the product photograph',url:'https://www.catan.com/catan-fans/news/catans-6th-edition-released',group:'catan',width:600,height:600,credit:false},

  'secret_hitler-box':{src:'assets/real/secret-hitler-box-cutout.png',title:L('Secret Hitler · retail box','Secret Hitler · caja comercial'),owner:'Goat, Wolf & Cabbage · photograph via Dragon’s Den Games',url:'https://dragonsdengames.com/products/secret-hitler',group:'secret_hitler',width:1006,height:338},
  'secret_hitler-components':{src:'assets/real/secret-hitler-components.jpg',title:L('Secret Hitler · policies, roles and office placards','Secret Hitler · políticas, roles y cargos'),owner:'Goat, Wolf & Cabbage · product photograph',url:'https://www.ubuy.ie/en/product/2L9DRY6-secret-hitler',group:'secret_hitler',width:1000,height:1000},
  'secret_hitler-nominate':{src:'assets/real/secret-hitler-nominate.png',title:L('Secret Hitler · President and Chancellor placards','Secret Hitler · placas de presidente y canciller'),owner:'Secret Hitler · official Print & Play · CC BY-NC-SA 4.0',url:'https://www.secrethitler.com/assets/Secret_Hitler_Print_and_Play.pdf',group:'secret_hitler',width:600,height:600,credit:false},
  'secret_hitler-vote':{src:'assets/real/secret-hitler-vote.png',title:L('Secret Hitler · Ja! and Nein ballots','Secret Hitler · papeletas Ja! y Nein'),owner:'Secret Hitler · official Print & Play · CC BY-NC-SA 4.0',url:'https://www.secrethitler.com/assets/Secret_Hitler_Print_and_Play.pdf',group:'secret_hitler',width:600,height:600,credit:false},
  'secret_hitler-legislate':{src:'assets/real/secret-hitler-legislate.png',title:L('Secret Hitler · Liberal and Fascist policies','Secret Hitler · políticas liberales y fascistas'),owner:'Secret Hitler · official Print & Play · CC BY-NC-SA 4.0',url:'https://www.secrethitler.com/assets/Secret_Hitler_Print_and_Play.pdf',group:'secret_hitler',width:600,height:600,credit:false},
  'secret_hitler-chaos':{src:'assets/real/secret-hitler-chaos.png',title:L('Secret Hitler · Election Tracker','Secret Hitler · marcador electoral'),owner:'Secret Hitler · official Print & Play · CC BY-NC-SA 4.0',url:'https://www.secrethitler.com/assets/Secret_Hitler_Print_and_Play.pdf',group:'secret_hitler',width:600,height:600,credit:false},

  'el_camarero-box':{src:'assets/real/el-camarero-box-cutout.png',title:L('El Camarero · original box','El Camarero · caja original'),owner:'Maldón',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:875,height:630},
  'el_camarero-components':{src:'assets/real/el-camarero-components.jpg',title:L('El Camarero · box insert, decks and bell','El Camarero · inserto, mazos y timbre'),owner:'Maldón',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:1300,height:731},
  'el_camarero-cards':{src:'assets/real/el-camarero-cards.jpg',title:L('El Camarero · food cards and service bell','El Camarero · cartas de comidas y timbre'),owner:'Maldón',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:1300,height:731},
  'el_camarero-pair':{src:'assets/real/el-camarero-play.jpg',title:L('El Camarero · matching dish cards','El Camarero · pareja de cartas de plato'),owner:'Maldón',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:1300,height:731},
  'el_camarero-serve':{src:'assets/real/el-camarero-serve.png',title:L('El Camarero · food cards ready to serve','El Camarero · cartas de comidas listas para servir'),owner:'Maldón · contextual crop from the product photograph',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:600,height:600,credit:false},
  'el_camarero-challenge':{src:'assets/real/el-camarero-challenge.png',title:L('El Camarero · service bell','El Camarero · timbre de servicio'),owner:'Maldón · contextual crop from the product photograph',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:600,height:600,credit:false},
  'el_camarero-score':{src:'assets/real/el-camarero-score.png',title:L('El Camarero · order card','El Camarero · carta de pedido'),owner:'Maldón · contextual crop from the product photograph',url:'https://maldon.com.ar/blog/projects/el-camarero/',group:'el_camarero',width:600,height:600,credit:false},

  'monopoly-box':{src:'assets/real/monopoly-box-cutout.png',title:L('Monopoly Classic · Spanish-language box','Monopoly Clásico · caja en español'),owner:'Hasbro',url:'https://instructions.hasbro.com/es-mx/instruction/monopoly-clasico',group:'monopoly',width:844,height:731},
  'monopoly-components':{src:'assets/real/monopoly-components.jpg',title:L('Monopoly Classic · board, deeds, cards, money and buildings','Monopoly Clásico · tablero, títulos, cartas, dinero y edificios'),owner:'Hasbro · product photograph via Best Buy',url:'https://www.bestbuy.com/product/hasbro-gaming-monopoly-board-game-games-misc-multicolor/JJ8VP7TCWS/sku/12195608',group:'monopoly',width:1500,height:1306},
  'monopoly-unowned':{src:'assets/real/monopoly-unowned.png',title:L('Monopoly · title deeds and money','Monopoly · títulos de propiedad y dinero'),owner:'Hasbro · contextual crop from the product photograph via Best Buy',url:'https://www.bestbuy.com/product/hasbro-gaming-monopoly-board-game-games-misc-multicolor/JJ8VP7TCWS/sku/12195608',group:'monopoly',width:600,height:600,credit:false},
  'monopoly-owned':{src:'assets/real/monopoly-owned.png',title:L('Monopoly · owned property on the board','Monopoly · propiedad con dueño en el tablero'),owner:'Hasbro · contextual crop from the product photograph via Best Buy',url:'https://www.bestbuy.com/product/hasbro-gaming-monopoly-board-game-games-misc-multicolor/JJ8VP7TCWS/sku/12195608',group:'monopoly',width:600,height:600,credit:false},
  'monopoly-doubles':{src:'assets/real/monopoly-doubles.png',title:L('Monopoly · pair of dice','Monopoly · pareja de dados'),owner:'Hasbro · contextual crop from the product photograph via Best Buy',url:'https://www.bestbuy.com/product/hasbro-gaming-monopoly-board-game-games-misc-multicolor/JJ8VP7TCWS/sku/12195608',group:'monopoly',width:600,height:600,credit:false},
  'monopoly-color-group':{src:'assets/real/monopoly-color-group.png',title:L('Monopoly · color group, houses and hotels','Monopoly · grupo de color, casas y hoteles'),owner:'Hasbro · contextual crop from the product photograph via Best Buy',url:'https://www.bestbuy.com/product/hasbro-gaming-monopoly-board-game-games-misc-multicolor/JJ8VP7TCWS/sku/12195608',group:'monopoly',width:600,height:600,credit:false},

  'chess-box':{src:'assets/real/chess-pieces.jpg',title:L('Staunton chess pieces','Piezas de ajedrez Staunton'),owner:'Alan Light · Wikimedia Commons · CC BY-SA 3.0',url:'https://commons.wikimedia.org/wiki/File:ChessSet.jpg',group:'chess',width:828,height:762},
  'chess-overview':{src:'assets/real/chess-pieces.jpg',title:L('King, rook, queen, pawn, knight and bishop','Rey, torre, dama, peón, caballo y alfil'),owner:'Alan Light · Wikimedia Commons · CC BY-SA 3.0',url:'https://commons.wikimedia.org/wiki/File:ChessSet.jpg',group:'chess',width:828,height:762},
  'chess-king':{src:'assets/real/chess-king.png',title:L('King · one square in any direction','Rey · una casilla en cualquier dirección'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},
  'chess-queen':{src:'assets/real/chess-queen.png',title:L('Queen · ranks, files and diagonals','Dama · filas, columnas y diagonales'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},
  'chess-rook':{src:'assets/real/chess-rook.png',title:L('Rook · ranks and files','Torre · filas y columnas'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},
  'chess-bishop':{src:'assets/real/chess-bishop.png',title:L('Bishop · diagonals','Alfil · diagonales'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},
  'chess-knight':{src:'assets/real/chess-knight.png',title:L('Knight · L-shaped jump','Caballo · salto en L'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},
  'chess-pawn':{src:'assets/real/chess-pawn.png',title:L('Pawn · advances straight, captures diagonally','Peón · avanza recto y captura en diagonal'),owner:'Chess Villa India · product photograph cropped for identification',url:'https://www.etsy.com/listing/1643537021/39-imperial-series-reproduced-staunton',group:'chess',width:500,height:500},

  'burako-box':{src:'assets/real/burako-box-cutout.png',title:L('Rummy & Burako Clásico · box','Rummy & Burako Clásico · caja'),owner:'Ruibal · product photograph via ApioVerde',url:'https://apioverde.com/products/rummy-burako-modelo-clasico-original-de-ruibal',group:'burako',width:468,height:228},
  'burako-components':{src:'assets/real/burako-box-components.jpg',title:L('Burako · racks, tiles, wilds and rules','Burako · atriles, fichas, comodines y reglas'),owner:'Ruibal · product photograph via ApioVerde',url:'https://apioverde.com/products/rummy-burako-modelo-clasico-original-de-ruibal',group:'burako',width:800,height:800},
  'burako-rack':{src:'assets/real/burako-rack.jpg',title:L('Burako · numbered tiles and wild tile','Burako · fichas numeradas y comodín'),owner:'Ruibal',url:'https://ruibalgames.com/rummy-burako-clasico/',group:'burako',width:650,height:485},
  'burako-draw':{src:'assets/real/burako-draw.png',title:L('Burako · stock and discard piles','Burako · pozo y pila de descarte'),owner:'Ruibal · contextual crop from the product photograph via ApioVerde',url:'https://apioverde.com/products/rummy-burako-modelo-clasico-original-de-ruibal',group:'burako',width:600,height:600,credit:false},
  'burako-meld':{src:'assets/real/burako-meld.png',title:L('Burako · runs and groups','Burako · escaleras y grupos'),owner:'Ruibal · contextual crop from the product photograph via ApioVerde',url:'https://apioverde.com/products/rummy-burako-modelo-clasico-original-de-ruibal',group:'burako',width:600,height:600,credit:false},
  'burako-canasta':{src:'assets/real/burako-canasta.png',title:L('Burako · completed meld','Burako · canasta completa'),owner:'Ruibal · contextual crop from the product photograph via ApioVerde',url:'https://apioverde.com/products/rummy-burako-modelo-clasico-original-de-ruibal',group:'burako',width:600,height:600,credit:false},
  'burako-close':{src:'assets/real/burako-close.png',title:L('Burako · rack at the end of a hand','Burako · atril al terminar la mano'),owner:'Ruibal · contextual crop from the product photograph',url:'https://ruibalgames.com/rummy-burako-clasico/',group:'burako',width:600,height:600,credit:false},

  'truco-box':{src:'assets/real/truco-box-cutout.png',title:L('Mazo Yorugua · Uruguayan Spanish-style deck','Mazo Yorugua · baraja de estilo español uruguayo'),owner:'Mazo Yorugua / Poppular Shop',url:'https://www.poppularshop.com/mazo-yorugua',group:'truco',width:681,height:1027},
  'truco-deck':{src:'assets/real/truco-deck.png',title:L('Spanish deck · complete visual reference','Baraja española · referencia visual completa'),owner:'Germarquezm and contributors · Wikimedia Commons · CC BY-SA 3.0',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:2496,height:1595},
  'truco-matas':{src:'assets/real/truco-matas.jpg',title:L('Truco · the four matas','Truco · las cuatro matas'),owner:'Wikimedia Commons contributor · published photograph',url:'https://commons.wikimedia.org/wiki/File:Cuatro_grandes_del_truco.JPG',group:'truco',width:640,height:480},
  'truco-piece-2':{src:'assets/real/truco-piece-2.png',title:L('Piece 2 · 30 envido points','Pieza 2 · 30 de envido'),owner:'Germarquezm and contributors · crop from CC BY-SA 3.0 deck',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:208,height:319},
  'truco-piece-4':{src:'assets/real/truco-piece-4.png',title:L('Piece 4 · 29 envido points','Pieza 4 · 29 de envido'),owner:'Germarquezm and contributors · crop from CC BY-SA 3.0 deck',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:208,height:319},
  'truco-piece-5':{src:'assets/real/truco-piece-5.png',title:L('Piece 5 · 28 envido points','Pieza 5 · 28 de envido'),owner:'Germarquezm and contributors · crop from CC BY-SA 3.0 deck',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:208,height:319},
  'truco-piece-11':{src:'assets/real/truco-piece-11.png',title:L('Piece 11 · 27 envido points','Pieza 11 · 27 de envido'),owner:'Germarquezm and contributors · crop from CC BY-SA 3.0 deck',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:208,height:319},
  'truco-piece-10':{src:'assets/real/truco-piece-10.png',title:L('Piece 10 · 27 envido points','Pieza 10 · 27 de envido'),owner:'Germarquezm and contributors · crop from CC BY-SA 3.0 deck',url:'https://commons.wikimedia.org/wiki/File:Baraja_espa%C3%B1ola_completa.png',group:'truco',width:208,height:319}
};
